<?php
$validFrom = date_create()->format('d-m-Y');
$validTo = sprintf($this->translate("per %d gg"), $this->package->getDuration());

$nowFree = date_create();
$start = date_create('2018-03-08 06:00:00');
$end = date_create('2018-03-09 04:55:00');

?>
<div id="pack-popup-container" class="sng-pack-popup-container">
    <div class="sng-pack-popup-inner">
        <!-- Actual container -->
        <div class="sng-pack-popup">
            <!-- Top-right button to close popup -->
            <a id="close-btn" class="sng-close-btn"><i class="fa fa-close"></i></a>

            <h1 class="sng-headers sng-w-1-1 sng-padding-top"><?= $this->translate("Riepilogo") ?></h1>
            <div class="sng-separator-line"></div>

            <div class="sng-summary">
                <h2 class="sng-headers"><?= $this->translate("Descrizione") ?>:</h2>
                <p id="description" class="sng-text"><?= $this->package->getDescription() ?></p>

                <table class="sng-table">
                    <tr>
                        <td class="sng-w-1-2">
                            <h2><?= $this->translate("Minuti") ?>:</h2>
                            <p id="minutes" class="sng-text"><?= $this->package->getMinutes() ?></p>
                        </td>
                        <td class="sng-w-1-2">
                            <h2><?= $this->translate("Prezzo") ?>:</h2>
                            <?php if($this->package->getType() === "Pacchetto"){ ?>
                                <p id="cost" class="sng-text"><?= ($this->package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end)) ? $this->translate("GRATUITO") : "&euro; ".number_format($this->package->getCost() / 100, 2, ',', '.') ?></p>
                            <?php }else{ ?>
                                <p id="cost" class="sng-text">&euro; 0</p>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="sng-w-1-2">
                            <h2><?= $this->translate("Valido dal") ?>:</h2>
                            <p id="valid-from" class="sng-text"><?= $validFrom ?></p>
                        </td>
                        <td class="sng-w-1-2">
                            <h2><?= $this->translate("Valido al") ?>:</h2>
                            <p id="valid-to" class="sng-text"><?= $validTo ?></p>
                        </td>
                    </tr>
                </table>

            </div>

            <div class="sng-footer">
                <?php if($this->package->getType() === "Pacchetto"){ ?>
                    <?php if ($this->hasContract || ($this->package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end))): ?>
                        <?php if ($this->package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end)) {?>
                            <p class="sng-text"><?= $this->translate("Vuoi confermare questo pacchetto?") ?></p>
                            <?php } else { ?>
                            <p class="sng-text"><?= $this->translate("Confermare l'acquisto utilizzando carta di credito?") ?></p>
                            <?php } ?>
                        <button id="confirm-btn" class="big green" data-href="<?= $this->url('area-utente/buy-package') ?>" data-package-id="<?= $this->package->getId() ?>"><?= $this->translate("Conferma") ?></button>
                    <?php else: ?>
                        <?php if(!is_null($this->serverInstance) && $this->serverInstance == "sk_SK"){ ?>
                        <p class="sng-text" style="color: red"> <?= $this->translate('Occorre effettuare l\'acquisto del Pacchetto Benvenuto prima di poter acquistare un pacchetto');?></p>
                        <?} else { ?>
                        <p class="sng-text"><?= $this->translate("Confermare l'acquisto registrando una carta di credito") ?></p>

                        <a id="confirm-btn" class="big green" href="<?= $this->url('cartasi/primo-pagamento-pacchetto', ['package' => $this->package->getId().$this->serverInstance]) ?>"><?= $this->translate("Conferma") ?></a>
                    <?php } endif; ?>
                <?php }else{ ?>
                    <button id="confirm-btn" class="big green" data-href="<?= $this->url('area-utente/buy-package') ?>" data-package-id="<?= $this->package->getId() ?>"><?= $this->translate("Conferma") ?></button>
                <?php } ?>
            </div>

        </div>
        <!-- actual container -->
    </div>
</div>
