<?= $this->translate('Gentile cliente,<br>abbiamo ricevuto la sua richiesta di recupero password.<br>Clicchi il link seguente per poterla reimpostare.'); ?>
    <br><br>
<?= $this->serverUrl(
    $this->url(
        'reset',
        [
            'userId' => $this->record->getUserId(),
            'token' => $this->record->getRequestKey()
        ]
    )
); ?>
    <br><br>
<?= $this->translate('Cordiali Saluti,<br><br>Sharengo car Servizio Clienti<br><br>Email: servizioclienti@sharengo.it<br><br>Web: www.sharengo.it<br>'); ?>