<?= $this->translate(
    'Gentile cliente,

abbiamo ricevuto la sua richiesta di recupero password.

Clicchi il link seguente per poterla reimpostare.

');
?>

<?= $this->serverUrl(
    $this->url(
        'reset',
        [
            'userId' => $this->record->getUserId(),
            'token' => $this->record->getRequestKey()
        ],
        [
            'query' => [
                'lang' => 'nl_NL'
            ]
        ]
    )
); ?>

<?= $this->translate(
    '
Cordiali Saluti,

Sharengo car Servizio Clienti

Email: servizioclienti@sharengo.it
Info e contratti: www.sharengo.it');
?>