version: '2'
services:
  public-fpm:
    image: cup-public-fpm
    container_name: public-fpm
    volumes:
      - .:/srv/apps/sharengo
    external_links:
      - sharengo-redis
      - sharengo-postgres
    networks:
      - back-tier
  public-nginx:
    image: cup-public-nginx
    container_name: public-nginx
    volumes_from:
      - public-fpm
    links:
      - public-fpm:fpm
    networks:
      - front-tier
      - back-tier
networks:
  front-tier:
    external:
      name: sharengo-front-tier
  back-tier:
    external:
      name: sharengo-back-tier
