ALTER SEQUENCE invoices_id_seq INCREMENT BY 1;
ALTER SEQUENCE drivers_license_validations_id_seq INCREMENT BY 1;
ALTER SEQUENCE contracts_id_seq INCREMENT BY 1;
ALTER SEQUENCE transactions_id_seq INCREMENT BY 1;
CREATE TABLE user_provider (user_id INT NOT NULL, provider_id VARCHAR(50) NOT NULL, provider VARCHAR(255) NOT NULL, PRIMARY KEY(user_id, provider_id));
DROP INDEX "primary";
ALTER TABLE cards ALTER is_assigned DROP DEFAULT;
ALTER TABLE cards ALTER assignable DROP DEFAULT;
ALTER TABLE cards ALTER assignable SET NOT NULL;
ALTER TABLE cards ADD PRIMARY KEY (code);
ALTER TABLE customers DROP CONSTRAINT authority_fk;
ALTER TABLE customers DROP CONSTRAINT birth_province_fk;
DROP INDEX IDX_62534E219ABEFD70;
DROP INDEX IDX_62534E21F3C71DAE;
DROP INDEX IDX_62534E219B26323A;
ALTER TABLE customers DROP driver_license_name;
ALTER TABLE customers ALTER fleet_id DROP DEFAULT;
ALTER TABLE customers ALTER pin TYPE TEXT;
ALTER TABLE customers ALTER pin DROP DEFAULT;
ALTER TABLE customers ALTER inserted_ts TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
ALTER TABLE customers ALTER inserted_ts DROP DEFAULT;
ALTER TABLE customers ALTER registration_completed DROP DEFAULT;
ALTER TABLE customers ALTER first_payment_completed DROP DEFAULT;
ALTER TABLE customers ALTER reprofiling_option DROP DEFAULT;
ALTER TABLE customers ALTER profiling_counter DROP DEFAULT;
ALTER TABLE customers ALTER enabled DROP DEFAULT;
ALTER TABLE customers ALTER gold_list DROP DEFAULT;
ALTER TABLE customers ALTER maintainer DROP DEFAULT;
ALTER TABLE customers ALTER driver_license_foreign DROP DEFAULT;
CREATE UNIQUE INDEX UNIQ_62534E219B26323A ON customers (card_code);
CREATE UNIQUE INDEX email_uk ON customers (email);
CREATE UNIQUE INDEX tax_code_uk ON customers (tax_code);
DROP INDEX idx_cd83a822a5bc2e0e;
CREATE UNIQUE INDEX UNIQ_CD83A822A5BC2E0E ON trip_payments (trip_id);
DROP INDEX idx_trips_timestamp_beginning;
ALTER TABLE trips DROP error_code;
ALTER TABLE trips ALTER id DROP DEFAULT;
ALTER TABLE trips ALTER car_plate DROP NOT NULL;
ALTER TABLE trips ALTER customer_id DROP NOT NULL;
ALTER TABLE trips ALTER timestamp_end SET NOT NULL;
ALTER TABLE trips ALTER km_end SET NOT NULL;
ALTER TABLE trips ALTER battery_end SET NOT NULL;
ALTER TABLE trips ALTER longitude_end SET NOT NULL;
ALTER TABLE trips ALTER latitude_end SET NOT NULL;
ALTER TABLE trips ALTER geo_end SET NOT NULL;
ALTER TABLE trips ALTER end_tx SET NOT NULL;
ALTER TABLE trips ALTER park_seconds SET NOT NULL;
ALTER TABLE trips ALTER payable DROP DEFAULT;
ALTER TABLE trips ADD CONSTRAINT FK_AA7370DA727ACA70 FOREIGN KEY (parent_id) REFERENCES trips (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX IDX_AA7370DA727ACA70 ON trips (parent_id);
ALTER INDEX idx_trips_car_plate RENAME TO IDX_AA7370DAAE35528C;
ALTER INDEX idx_trips_customer_id RENAME TO IDX_AA7370DA9395C3F3;
DROP INDEX unique_invoice_number;
ALTER TABLE invoices ALTER id DROP DEFAULT;
ALTER TABLE invoices ALTER customer_id DROP NOT NULL;
ALTER TABLE invoices ALTER invoice_number TYPE VARCHAR(255);
ALTER TABLE invoices ALTER invoice_number DROP DEFAULT;
ALTER TABLE invoices ALTER generated_ts TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
ALTER TABLE invoices ALTER generated_ts DROP DEFAULT;
ALTER TABLE invoices ALTER content TYPE JSON;
ALTER TABLE invoices ALTER content DROP DEFAULT;
ALTER TABLE customers_bonus DROP CONSTRAINT fk_ac781c5f2989f1fd;
ALTER TABLE customers_bonus DROP CONSTRAINT fk_ac781c5f2fc0cb0f;
ALTER TABLE customers_bonus DROP CONSTRAINT fk_ac781c5ff44cabff;
DROP INDEX uniq_ac781c5f2fc0cb0f;
DROP INDEX idx_ac781c5f2989f1fd;
DROP INDEX IDX_AC781C5FF44CABFF;
ALTER TABLE customers_bonus DROP invoice_id;
ALTER TABLE customers_bonus DROP transaction_id;
ALTER TABLE customers_bonus DROP package_id;
ALTER TABLE customers_bonus DROP invoiced_at;
DROP INDEX fleets_int_code_key;
DROP INDEX unique_code;
ALTER TABLE fleets DROP choropleth_params;
ALTER TABLE fleets ALTER int_code TYPE VARCHAR(255);
ALTER TABLE fleets ALTER int_code DROP DEFAULT;
ALTER TABLE zone_alarms_fleets DROP CONSTRAINT zone_alarms_fleets_fleet_id_fkey;
ALTER TABLE zone_alarms_fleets DROP CONSTRAINT zone_alarms_fleets_zone_alarm_id_fkey;
ALTER TABLE zone_alarms_fleets ADD CONSTRAINT FK_9515B62AD3F89EC FOREIGN KEY (zone_alarm_id) REFERENCES fleets (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE zone_alarms_fleets ADD CONSTRAINT FK_9515B62A4B061DF9 FOREIGN KEY (fleet_id) REFERENCES zone_alarms (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE foreign_drivers_license_upload ALTER customer_id DROP NOT NULL;
ALTER TABLE foreign_drivers_license_upload ALTER customer_birth_country TYPE VARCHAR(255);
ALTER TABLE old_customer_discounts ALTER id DROP DEFAULT;
ALTER TABLE old_customer_discounts ALTER discount SET NOT NULL;
ALTER TABLE old_customer_discounts ALTER obsolete_from SET NOT NULL;
DROP INDEX IDX_88B90A6C9395C3F3;
ALTER TABLE discount_state ALTER id TYPE BIGINT;
ALTER TABLE discount_state ALTER id DROP DEFAULT;
ALTER TABLE discount_state ALTER id DROP DEFAULT;
ALTER TABLE discount_state ALTER customer_id SET NOT NULL;
ALTER TABLE discount_state ALTER discount_state SET NOT NULL;
CREATE UNIQUE INDEX UNIQ_88B90A6C9395C3F3 ON discount_state (customer_id);
ALTER TABLE countries ALTER mctc TYPE VARCHAR(3);
ALTER TABLE countries ALTER mctc DROP DEFAULT;
ALTER TABLE drivers_license_validations ALTER id DROP DEFAULT;
ALTER TABLE drivers_license_validations ALTER customer_id DROP NOT NULL;
ALTER TABLE drivers_license_validations ALTER data TYPE JSON;
ALTER TABLE drivers_license_validations ALTER data DROP DEFAULT;
ALTER TABLE drivers_license_validations ALTER generated_ts TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
ALTER TABLE drivers_license_validations ALTER generated_ts DROP DEFAULT;
ALTER TABLE provider_authenticated_customers ALTER inserted_ts SET NOT NULL;
COMMENT ON COLUMN messages_types.default_transport IS NULL;
DROP INDEX customers_bonus_packages_code_key;
ALTER TABLE customers_bonus_packages ALTER id DROP DEFAULT;
ALTER TABLE customers_bonus_packages ALTER code TYPE VARCHAR(255);
ALTER TABLE customers_bonus_packages ALTER display_priority DROP DEFAULT;
ALTER TABLE cars_info DROP CONSTRAINT fk_cars;
ALTER TABLE cars_info ALTER int_lat TYPE NUMERIC(10, 0);
ALTER TABLE cars_info ALTER int_lat DROP DEFAULT;
ALTER TABLE cars_info ALTER int_lon TYPE NUMERIC(10, 0);
ALTER TABLE cars_info ALTER int_lon DROP DEFAULT;
ALTER TABLE cars_info ALTER gprs_lat TYPE NUMERIC(10, 0);
ALTER TABLE cars_info ALTER gprs_lat DROP DEFAULT;
ALTER TABLE cars_info ALTER gprs_lon TYPE NUMERIC(10, 0);
ALTER TABLE cars_info ALTER gprs_lon DROP DEFAULT;
ALTER TABLE cars_info ALTER lastupdate TYPE TIMESTAMP(0) WITHOUT TIME ZONE;
ALTER TABLE cars_info ALTER lastupdate DROP DEFAULT;
COMMENT ON COLUMN cars_info.fw_ver IS NULL;
COMMENT ON COLUMN cars_info.hw_ver IS NULL;
COMMENT ON COLUMN cars_info.sw_ver IS NULL;
COMMENT ON COLUMN cars_info.sdk IS NULL;
COMMENT ON COLUMN cars_info.gsm_ver IS NULL;
COMMENT ON COLUMN cars_info.android_device IS NULL;
COMMENT ON COLUMN cars_info.android_build IS NULL;
COMMENT ON COLUMN cars_info.tbox_sw IS NULL;
COMMENT ON COLUMN cars_info.tbox_hw IS NULL;
COMMENT ON COLUMN cars_info.mcu_model IS NULL;
COMMENT ON COLUMN cars_info.mcu IS NULL;
COMMENT ON COLUMN cars_info.vehicle_type IS NULL;
COMMENT ON COLUMN cars_info.gps IS NULL;
ALTER TABLE cars_info ADD CONSTRAINT FK_396901D6AE35528C FOREIGN KEY (car_plate) REFERENCES cars (plate) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE reservations ALTER id DROP DEFAULT;
ALTER TABLE reservations ALTER car_plate DROP NOT NULL;
ALTER TABLE reservations ALTER active DROP DEFAULT;
ALTER TABLE reservations ALTER cards TYPE TEXT;
ALTER TABLE reservations ALTER cards DROP DEFAULT;
ALTER TABLE reservations ALTER to_send DROP DEFAULT;
ALTER TABLE reservations ALTER sent_ts SET NOT NULL;
ALTER TABLE reservations ALTER consumed_ts SET NOT NULL;
ALTER TABLE reservations ALTER deleted_ts SET NOT NULL;
DROP INDEX idx_3396b6374adad40b;
ALTER TABLE extra_payments ALTER fleet_id DROP DEFAULT;
ALTER TABLE extra_payments ALTER reasons TYPE JSON;
ALTER TABLE extra_payments ALTER reasons DROP DEFAULT;
ALTER TABLE pois DROP type_group;
ALTER TABLE pois ALTER id DROP DEFAULT;
ALTER TABLE pois ALTER update DROP DEFAULT;
ALTER TABLE zone DROP id_parent;
ALTER TABLE zone ALTER id DROP DEFAULT;
ALTER TABLE zone ALTER name TYPE VARCHAR(255);
ALTER TABLE zone ALTER name DROP DEFAULT;
ALTER TABLE zone ALTER name SET NOT NULL;
ALTER TABLE zone ALTER area_invoice TYPE Geometry;
ALTER TABLE zone ALTER area_invoice DROP DEFAULT;
ALTER TABLE zone ALTER area_invoice SET NOT NULL;
ALTER TABLE zone ALTER active SET NOT NULL;
ALTER TABLE zone ALTER hidden SET NOT NULL;
ALTER TABLE zone ALTER invoice_description TYPE VARCHAR(255);
ALTER TABLE zone ALTER invoice_description DROP DEFAULT;
ALTER TABLE zone ALTER invoice_description SET NOT NULL;
ALTER TABLE zone ALTER rev_geo DROP DEFAULT;
ALTER TABLE zone ALTER area_use TYPE Geometry;
ALTER TABLE zone ALTER area_use DROP DEFAULT;
ALTER TABLE zone ALTER area_use SET NOT NULL;
ALTER TABLE messages_outbox ALTER id DROP DEFAULT;
ALTER TABLE messages_outbox ALTER meta TYPE JSON;
ALTER TABLE messages_outbox ALTER meta DROP DEFAULT;
ALTER TABLE messages_outbox ALTER sent_meta TYPE JSON;
ALTER TABLE messages_outbox ALTER sent_meta DROP DEFAULT;
COMMENT ON COLUMN messages_outbox.sent_meta IS NULL;
ALTER TABLE foreign_drivers_license_validation ALTER id DROP DEFAULT;
ALTER TABLE free_fares ALTER active DROP DEFAULT;
ALTER TABLE trip_payments_canceled ALTER id DROP DEFAULT;
ALTER TABLE commands ALTER id DROP DEFAULT;
ALTER TABLE commands ALTER intarg1 DROP DEFAULT;
ALTER TABLE commands ALTER intarg2 DROP DEFAULT;
ALTER TABLE commands ALTER to_send DROP DEFAULT;
ALTER TABLE commands ALTER ttl DROP DEFAULT;
ALTER TABLE cars DROP battery_offset;
ALTER TABLE cars DROP gps_data;
ALTER TABLE cars DROP park_enabled;
ALTER TABLE cars DROP plug;
ALTER TABLE cars ALTER manufactures DROP DEFAULT;
ALTER TABLE cars ALTER label DROP DEFAULT;
ALTER TABLE cars ALTER active DROP DEFAULT;
ALTER TABLE cars ALTER int_cleanliness DROP DEFAULT;
ALTER TABLE cars ALTER ext_cleanliness DROP DEFAULT;
ALTER TABLE cars ALTER damages TYPE TEXT;
ALTER TABLE cars ALTER damages DROP DEFAULT;
ALTER TABLE cars ALTER battery DROP DEFAULT;
ALTER TABLE cars ALTER busy DROP DEFAULT;
ALTER TABLE cars ALTER hidden DROP DEFAULT;
ALTER TABLE cars ALTER rpm DROP DEFAULT;
ALTER TABLE cars ALTER speed DROP DEFAULT;
ALTER TABLE cars ALTER obc_in_use DROP DEFAULT;
ALTER TABLE cars ALTER obc_wl_size DROP DEFAULT;
ALTER TABLE cars ALTER km DROP DEFAULT;
ALTER TABLE cars ALTER running DROP DEFAULT;
ALTER TABLE cars ALTER parking DROP DEFAULT;
ALTER TABLE cars ALTER status DROP DEFAULT;
ALTER TABLE cars ALTER soc DROP DEFAULT;
ALTER TABLE cars ALTER charging DROP DEFAULT;
ALTER TABLE cars ALTER charging DROP NOT NULL;
ALTER TABLE messages_transports DROP options;
ALTER TABLE customer_notes ALTER id DROP DEFAULT;
ALTER TABLE customer_notes ALTER note TYPE VARCHAR(255);
ALTER TABLE customer_notes ALTER note DROP DEFAULT;
ALTER TABLE promo_codes_info ALTER no_standard_bonus TYPE INT;
ALTER TABLE promo_codes_info ALTER no_standard_bonus SET DEFAULT ;
ALTER TABLE promo_codes_info ALTER no_standard_bonus SET NOT NULL;
ALTER TABLE cars_configurations DROP CONSTRAINT fk_cars;
ALTER TABLE cars_configurations DROP CONSTRAINT fk_fleets;
ALTER TABLE cars_configurations ALTER id DROP DEFAULT;
ALTER TABLE cars_configurations ALTER value DROP NOT NULL;
ALTER TABLE cars_configurations ADD CONSTRAINT FK_54DBC6A54B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleets (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cars_configurations ADD CONSTRAINT FK_54DBC6A5AE35528C FOREIGN KEY (car_plate) REFERENCES cars (plate) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE cars_maintenance ALTER id DROP DEFAULT;
ALTER TABLE cars_maintenance ALTER car_plate DROP NOT NULL;
ALTER TABLE cars_maintenance ALTER webuser_id DROP NOT NULL;
ALTER INDEX idx_12407f1ae35528c RENAME TO IDX_41AB4A8BAE35528C;
ALTER INDEX idx_12407f149279951 RENAME TO IDX_41AB4A8B49279951;
ALTER TABLE zone_alarms ALTER id DROP DEFAULT;
ALTER TABLE zone_alarms ALTER active DROP DEFAULT;
ALTER TABLE zone_alarms ALTER description TYPE VARCHAR(255);
ALTER TABLE zone_alarms ALTER description DROP DEFAULT;
COMMENT ON COLUMN zone_alarms.description IS NULL;
ALTER TABLE reservations_archive ALTER id DROP DEFAULT;
ALTER TABLE reservations_archive ALTER car_plate DROP NOT NULL;
ALTER TABLE reservations_archive ALTER active DROP DEFAULT;
ALTER TABLE reservations_archive ALTER cards TYPE TEXT;
ALTER TABLE reservations_archive ALTER cards DROP DEFAULT;
ALTER TABLE reservations_archive ALTER to_send DROP DEFAULT;
ALTER TABLE reservations_archive ALTER sent_ts SET NOT NULL;
ALTER TABLE reservations_archive ALTER consumed_ts SET NOT NULL;
ALTER TABLE configurations ALTER id DROP DEFAULT;
ALTER TABLE cartasi_csv_anomalies_notes ALTER id DROP DEFAULT;
ALTER TABLE cartasi_csv_anomalies_notes ALTER note TYPE TEXT;
ALTER TABLE cartasi_csv_anomalies_notes ALTER note DROP DEFAULT;
ALTER TABLE cartasi_csv_files ALTER id DROP DEFAULT;
ALTER TABLE cartasi_csv_files ALTER webuser_id DROP NOT NULL;
ALTER TABLE cartasi_csv_files ALTER filename TYPE VARCHAR(255);
ALTER TABLE cartasi_csv_files ALTER filename DROP DEFAULT;
ALTER TABLE cartasi_csv_anomalies ALTER id DROP DEFAULT;
ALTER TABLE cartasi_csv_anomalies ALTER cartasi_csv_file_id DROP NOT NULL;
ALTER TABLE cartasi_csv_anomalies ALTER resolved DROP DEFAULT;
ALTER TABLE cartasi_csv_anomalies ALTER csv_data TYPE JSON;
ALTER TABLE cartasi_csv_anomalies ALTER csv_data DROP DEFAULT;
DROP INDEX carrefour_used_codes_code_key;
ALTER TABLE carrefour_used_codes ALTER id DROP DEFAULT;
ALTER TABLE carrefour_used_codes ALTER customer_id DROP NOT NULL;
ALTER TABLE carrefour_used_codes ALTER customers_bonus_id DROP NOT NULL;
DROP INDEX unique_zone_price;
ALTER TABLE zone_price ALTER id DROP DEFAULT;
ALTER TABLE zone_price ALTER cost TYPE INT;
ALTER TABLE zone_price ALTER cost DROP DEFAULT;
ALTER TABLE zone_price ALTER cost SET NOT NULL;
ALTER TABLE zone_price ALTER bonus TYPE INT;
ALTER TABLE zone_price ALTER bonus DROP DEFAULT;
ALTER TABLE zone_price ALTER bonus SET NOT NULL;
ALTER TABLE zone_price ALTER note TYPE VARCHAR(255);
ALTER TABLE zone_price ALTER note DROP DEFAULT;
ALTER TABLE zone_price ALTER note SET NOT NULL;
ALTER TABLE zone_price ADD CONSTRAINT FK_6CE68D7F28A05803 FOREIGN KEY (id_group_open) REFERENCES zone_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE zone_price ADD CONSTRAINT FK_6CE68D7F5B3F6754 FOREIGN KEY (id_group_close) REFERENCES zone_groups (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX IDX_6CE68D7F28A05803 ON zone_price (id_group_open);
CREATE INDEX IDX_6CE68D7F5B3F6754 ON zone_price (id_group_close);
ALTER TABLE customer_deactivations ALTER id DROP DEFAULT;
ALTER TABLE customer_deactivations ALTER reason TYPE TEXT;
ALTER TABLE customer_deactivations ALTER reason DROP DEFAULT;
ALTER TABLE customer_deactivations ALTER details TYPE JSON;
ALTER TABLE customer_deactivations ALTER details DROP DEFAULT;
DROP INDEX IDX_59BF7BEA69545666;
DROP INDEX IDX_59BF7BEA2FC0CB0F;
ALTER TABLE bonus_package_payments ALTER id DROP DEFAULT;
CREATE UNIQUE INDEX UNIQ_59BF7BEA69545666 ON bonus_package_payments (bonus_id);
CREATE UNIQUE INDEX UNIQ_59BF7BEA2FC0CB0F ON bonus_package_payments (transaction_id);
DROP INDEX promo_codes_once_unique;
ALTER TABLE zone_groups ALTER id DROP DEFAULT;
ALTER TABLE zone_groups ALTER description TYPE VARCHAR(255);
ALTER TABLE zone_groups ALTER description DROP DEFAULT;
ALTER TABLE zone_groups ALTER description SET NOT NULL;
ALTER TABLE zone_groups ALTER company_id SET NOT NULL;
ALTER TABLE zone_groups ALTER close_trip DROP DEFAULT;
ALTER TABLE zone_groups ALTER id_zone SET NOT NULL;
ALTER TABLE zone_groups ADD CONSTRAINT FK_CF7E11024B061DF9 FOREIGN KEY (fleet_id) REFERENCES fleets (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
CREATE INDEX IDX_CF7E11024B061DF9 ON zone_groups (fleet_id);
ALTER TABLE trip_payment_tries_canceled ALTER id DROP DEFAULT;
