<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/aldai/application/css/style.css" rel="stylesheet">

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body class="bg-blue">
        <div class="container-fluid lato-bold">
            <div class="row bg-grey  bg-blue">
                <div class="col-lg-7 col-md-8">
                    <img src="/aldai/application/images/sharengo_img.jpg" class="img-responsive" style="width:100%"/>
                </div>
                <div class="col-lg-5 col-md-4 text-center" >
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-bold strong-more-big white">SOLO PER <br>ISCRITTI </span>
                    <span class="lato-bold strong-more-big yellow">ALDAI
                    </span>

                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <div class="text-center space">
                        <span class="lato-bold strong-more-small white">CODICE PROMO
                        </span>
                        <br>
                        <a href="<?= $this->url('promocode-signup', ['promocode' => 'ALDAI']); ?>" id="submit" class="button" onClick="ga('send', 'event', {eventCategory: 'landing', eventAction: 'click', eventLabel: 'ALDAI'});">ALDAI</a>
                        </a>
                    </div>
                </div>
                <!-------->
                <div class="col-lg-5 col-md-4 text-left" >
                    <div id="first-paragraph">
                        <span class="lato-regular strong-big white">
                            <ul>
                                <li>
                                    <span class="lato-regular strong-big yellow">ISCRIZIONE RIDOTTA AL 50%
                                    </span>
                                    <br>
                                    <span class="lato-regular strong white">(5€ invece di 10€)
                                    </span>
                                </li>
                                <br>
                                <li>
                                    <span class="lato-regular strong-big yellow">21% DI SCONTO SULLA TARIFFA CHE PERMETTE DI VIAGGIARE A 0,22€/MINUTI
                                    </span>
                                </li>
                                <br>
                                <li>
                                    <span class="lato-regular strong-big yellow">30 MINUTI DI CORSE GRATIS
                                    </span>
                                </li>
                                <br>
                            </ul>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>