<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

         <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/anteo/application/css/style.css" rel="stylesheet">

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-63160906-2', 'auto');
          ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-blue">
    <div class="container-fluid lato-bold">
        <div class="row bg-grey  bg-blue">
            <div class="col-lg-7 col-md-8">
                <img src="/anteo/application/images/sharengo_img.jpg" class="img-responsive"/>
            </div>
            <div class="col-lg-5 col-md-4 text-center" >

                <div id="first-paragraph">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">

                    <img src="/anteo/application/images/logo.png" width="350" height="64" alt="logo Cinema">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">Arrivare e parcheggiare</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">al Palazzo del cinema</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">è facile e conveniente</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">con il car sharing</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">che non inquina</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">A tutti i nuovi abbonati</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">Palazzo del cinema Anteo</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big white">Share'ngo offre:</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">

                    <div id="container-paragraph">
                        <div id="first-paragraph-due" style="text-align:left;">
                    <span class="lato-regular strong-big white">
                    <ul class="lato-regular strong-big white marginleft" style="list-style-type:none; padding-bottom:10px;">
                     <li>&#8226; Iscrizione ridotta da 10 a 1€</li>
                     <li>&#8226; 15 minuti di corse gratuite</li>
                        <?php
                        $now = new \DateTime();
                        $start = new \DateTime('2017-11-01 00:00:00');

                        if($now >= $start) { ?>
                            <li>&#8226; 15% di sconto sulle tariffe di noleggio</li>
                        <?php
                        }
                        ?>
                     </ul>
                     </span>
                        </div>
                    </div>



                    <span class="lato-regular strong-big white">Registrati oggi con il
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        codice promo</span>
                    <div class="text-center space">
                        <a href="<?= $this->url('promocode-signup',['promocode' => 'ANTEO']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'ANTEO'});">ANTEO</a>
                    </div>
                    <!--<div id="container-paragraph">
                        <div id="first-paragraph-due" style="text-align:left;">

                    <span class="lato-bold strong-small grey">Entro il 7 dicembre 2016:</span>
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">

                        <ul class="lato-regular strong-small yellow" style="padding-top:20px; padding-left:22px;">
                        <li><span class="lato-bold strong-small grey">Iscrizione ridotta a 5€ <span class="lato-regular strong-small grey">(anziché 10€)</span></span><br/></li>

                        <li style="padding-top:20px;"><span class="lato-bold strong-small grey"> Tariffa scontata a 22cent./min</span><br/>
                        </li>

                        <li style="padding-top:20px;"><span class="lato-regular strong-small grey">Subito <span class="lato-bold strong-small grey">30 minuti bonus</span></span></li>
                        </ul>

                  <!-- <li style="padding-top:20px;"><span class="lato-bold strong-small grey">Di notte le donne viaggiano gratis</span><br/><span class="lato-regular strong-more-small grey">(dalle ore 1:00 alle 6:00 del mattino - fino a 100 minuti al mese)</span></li>
                        </ul>

                    <span class="lato-bold strong-small grey">Dal 8 dicembre iscrizione ridotta del 50%<br/></span>
                           <span class="lato-regular strong-small grey">(5€ invece di 10€)</span>
                        </div> -->

                </div>




                <!--
                <p class="white" id="paragraph1a">
                <br class="visible-md visible-lg">
                <br class="visible-xs visible-sm">
                <span class="lato-regular strong-small mobile">
                La pi&ugrave; bella citt&agrave; del mondo si merita la mobilit&agrave;<br class="visible-xs visible-sm"> pi&ugrave; bella del mondo. Finalmente Roma sar&agrave;<br class="visible-xs visible-sm"> tutta tua e penserai a quanto &egrave; dolce la vita.
                <br class="visible-md visible-lg">
             </p>

                <p class="white" id="paragraph1a">
                <br class="visible-md visible-lg">
                <br class="visible-xs visible-sm">
                <span class="lato-regular strong-small">
                La pi&ugrave; bella citt&agrave; del mondo si merita la mobilit&agrave;
                <br class="visible-md visible-lg">
                <br class="visible-xs visible-sm">
                pi&ugrave; bella del mondo. Finalmente Roma sar&agrave;
                <br class="visible-md visible-lg">
                <br class="visible-xs visible-sm">
                tutta tua e penserai a quanto &egrave; dolce la vita.
                <br class="visible-md visible-lg">
             </p>

             <span class="strong-small desk-block lato-regular">
                    <span class="yellow">30' DI CORSE GRATUITE</span> e iscrizione
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    a met&agrave; prezzo (€5 invece di €10)
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="yellow">15% DI SCONTO SULLA TARIFFA</span>
                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <spam class="strong-more-small">(0,24cent./minuto invece di 0,28cent./minuto)</
                </span> -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </body>