<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/arci/application/css/style.css" rel="stylesheet">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-blue">
        <div class="container-fluid lato-bold">
            <div class="row bg-grey  bg-blue">
                <div class="col-lg-7 col-md-8">
                    <img src="/arci/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
                <div class="col-lg-5 col-md-4 text-center" >

                    <br class="visible-md visible-lg">
                    <br class="visible-xs visible-sm">
                    <span class="lato-bold strong black">Gli associati</span>

                    <div class="wrapper">
                        <img class="classname" src="/arci/application/images/logo.png" alt="" />
                    </div>

                    <div id="first-paragraph">
                        <span class="lato-bold strong black">utilizzano a Milano, Firenze e Roma le auto elettriche e condivise di</span></div>

                    <div class="wrapper">
                        <img class="classname" src="/arci/application/images/logo_Sharengo.png" alt="" />
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                    </div>

                    <div id="first-paragraph">
                        <span class="lato-bold strong black">con l'iscrizione ridotta da 10 a 5€, 30 minuti bonus e la tariffa scontata del 20% (22 cent/minuto)</span>
                    </div>

                    <div id="first-paragraph">
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        <span class="lato-bold strong black">Registrati oggi!</span>
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        <span class="lato-bold strong black">con il codice PROMO</span>
                    </div>

                    <div class="text-center space">
                        <a href="<?= $this->url('promocode-signup',['promocode' => 'ARCI']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'ARCI'});">ARCI</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>