<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <img src="https://secure.adnxs.com/px?id=878412&t=2" width="1" height="1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SHARE'NGO</title>
    <link href="/b2bpromo/application/css/style.css" rel="stylesheet">
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>

</head>

<body>
<a href="mailto:aziende@sharengo.it"><div class="visore"></div></a> <!-- fine visore -->


<div class="container" style="max-width:1000px; margin:0 auto;">
    <ul class="testo" style="padding-top:20px; padding-left:22px; padding-right:10px; list-style: none outside none;">
        <li><table cellpadding="0" cellspacing="0">
                <tr>
                    <td width="110"><img src="/b2bpromo/application/images/Icone1.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Taglio dei costi fissi</span><br>Il car sharing riduce gli oneri delle flotte e le fatiche dei rimborsi perché tutto è pay as you go e pienamente deducibile. Con una tariffa di soli 20 cent/min + IVA
                        si risparmia tanto, ogni giorno. Per scoprire tutti i dettagli <a href="http://site.sharengo.it/aziende/">visitate il nostro sito.</a>
                    </td>
                </tr>
            </table></li>

        <li style="padding-top: 30px;">

            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td width="110"><img src="/b2bpromo/application/images/Icone2.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Mobilità aziendale più efficiente</span><br>Le auto elettriche di Share’ngo sono sempre cariche, parcheggiano gratis ovunque e vanno dappertutto, anche in ZTL (a Modena, Firenze e Roma) e in Area C (a Milano). Ne abbiamo 2.000 in strada e le prenotate con il cellulare. Immaginate quanto tempo e quanto stress potrete evitare.
                    </td>
                </tr>
            </table>
        </li>

        <li style="padding-top: 30px;">

            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td width="110"><img src="/b2bpromo/application/images/Icone3.png" class="img-responsive" style="float:left;"></td>

                    <td><span class="titolo">Ogni chilometro, 150 grammi di emissioni nocive risparmiate
</span><br>La mobilità sostenibile è una scelta di buon senso e di responsabilità per ogni azienda, un contributo concreto e misurabile al miglioramento dell’ambiente urbano. Ecco la presentazione <a href="http://site.sharengo.it/wp-content/uploads/2017/11/Leaflet-B2B_297x210_15-nov_LR-x-sito.pdf">SHARE’NGO per le AZIENDE.</a>
                        <br/><span class="parentesi"></span></span><br/></td>
                </tr>
            </table>
        </li>

        <li style="padding-top: 30px;">

            <table cellpadding="0" cellspacing="0">
                <tr>
                    <td width="110"><img src="/b2bpromo/application/images/Icone4.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">I vantaggi di aprire  oggi un account aziendale Share’ngo
</span><br>Costi di attivazione ridotti del 50%, parcheggi di prossimità, bonus pubblicitario per promuovere le vostre attività retail verso i nostri 100.000 clienti… Sono tanti i vantaggi di chi attiva un account Share’ngo per primo.
                        <strong>Per scoprirli tutti basta una mail</strong>.

                    </td>
                </tr>
            </table>
        </li>

    </ul>

    <div class="" style="position:relative; bottom:0; margin:auto; max-width:100%; text-align:center;">
        <table cellpadding="0" cellspacing="0" align="center">
            <tr>
                <td colspan="5" style="max-width:600px; width:600px; max-height:161px; background-color:#FFFFFF;"><a href="mailto:aziende@sharengo.eu"><img src="/b2bpromo/application/images/scaricapp/ScaricaAPP_01.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></td>

            </tr>
            <tr>
                <td style="max-width:35px; width:35px; max-height:39px;  background-color:#FFFFFF;"><img src="/b2bpromo/application/images/scaricapp/ScaricaAPP_02.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></td>
                <td style="max-width:109px; width:109px; max-height:39px;  background-color:#FFFFFF;"><a href="itms://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8"><img src="/b2bpromo/application/images/scaricapp/ScaricaAPP_03.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></a></td>

                <td style="max-width:8px; width:8px; max-height:39px;  background-color:#FFFFFF;"></td>

                <td style="max-width:100px; width:100px; max-height:39px;  background-color:#FFFFFF;"><a href="https://play.google.com/store/apps/details?id=it.sharengo.eteria"<img src="/b2bpromo/application/images/scaricapp/ScaricaAPP_05.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></a></td>

            </tr>
        </table>


    </div>

</div> <!-- container chiuso -->


</body>
</html>
