<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

         <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/coin/application/css/style.css" rel="stylesheet">

        <script>

            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');

        </script>
    </head>

        <body class="bg-white">
    	<div class="container-fluid lato-bold">
    		<div class="row bg-grey  bg-white">
                <div class="col-lg-7 col-md-8 content">
                    <img src="/coin/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div> <!-- col-lg-7 col-md-8 -->

    			<div class="col-lg-5 col-md-4 text-center sidebar" >
    				<div id="first-paragraph" style="text-align:center; padding-left:10px; padding-top:10px;">

                    	<span class="lato-bold strong-big grey">
						<span class="lato-bold strong-big green" >
							Con COIN l'iscrizione a
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							Share'ngo è ridotta del 50%
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							con uno sconto
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							del 20% sulle tariffe
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							di noleggio.</span>
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							SI REGISTRI OGGI
                            <br class="visible-md visible-lg">
							<br class="visible-xs visible-sm">
							CON IL CODICE PROMO
						</span>
						<div class="text-center space">
                        <a href="<?= $this->url('promocode-signup',['promocode' => 'COIN17']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'COIN17'});">COIN17</a>
                        </div>
							<span class="lato-BOLD strong grey">
                            Bastano 5 minuti... E un click
                            </span>
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
						<br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">

                    <img src="/coin/application/images/ScaricaAPP.jpg"  usemap="#Map" alt="scarica l'app" class="img-responsive img_btn" style="text-align:center;">
                    <map name="Map" id="Map">
                        <area alt="" title="" href="https://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8" shape="rect" coords="34,160,142,193" />
                        <area alt="" title="" href="https://play.google.com/store/apps/details?id=it.sharengo.eteria" shape="rect" coords="152,161,252,194" />
                    </map>

                     </div> <!-- first-paragraph-due -->
                     </div> <!-- container-paragraph -->


    		</div> <!-- row bg-grey  bg-white -->
    	</div> <!-- container-fluid lato-bold -->
    </body>