<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="/comunedifirenze/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>

</head>

    <body class="bg-green">
    	<div class="container-fluid lato-bold">
    		<div class="row bg-grey  bg-green">
                <div class="col-lg-7 col-md-8">
                    <img src="/comunedifirenze/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
    			<div class="col-lg-5 col-md-4 text-center" >                    
    				
                    <div id="first-paragraph"> 	
                    
                    	
                        <span class="lato-BOLD strong grey">
                        
                      
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        I dipendenti del comune
						<br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        di Firenze e i loro familiari
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        utilizzano il car sharing
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        elettrico di
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        <img src="/comunedifirenze/application/images/logo_sharengo.png" width="250" height="118" alt="logo_sharengo">
                        <br class="visible-md visible-lg">
						<br class="visible-xs visible-sm">
                        <p></p>
                        
                        </div>
                    
                     <div id="container-paragraph">
                     <div id="first-paragraph-due" style="text-align:center; padding-left:10px; padding-top:10px;">
                     
                     
                     <span class="lato-BOLD strong grey">
                     Con l'iscrizione ridotta
                     <br class="visible-md visible-lg">
					 <br class="visible-xs visible-sm">
                     da 10€ a 1€ e lo sconto del 20%
                     <br class="visible-md visible-lg">
					 <br class="visible-xs visible-sm">
                     sulle tariffe di noleggio (0,22€/min)</span>
                     <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                        <p></p>
                     <span class="lato-regular strong grey">REGISTRATI OGGI
                     <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    CON IL CODICE PROMO</span>
                        
                        <div class="text-center space">
                            <a href="<?= $this->url('promocode-signup',['promocode' => 'FIDIP']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'FIDIP'});">FIDIP</a>
                        </div>
                     </div>
                     
</div>
    			</div>  			
    		</div>
    	</div>
    </body>