<!DOCTYPE html>
<html lang="en">
  	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	
		<script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>


		 <!-- Bootstrap -->
		<link href="/common/application/css/bootstrap.css" rel="stylesheet">
		<script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

		<link href="/firenze/application/css/style.css" rel="stylesheet">

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-63160906-2', 'auto');
          ga('send', 'pageview');

        </script>
    </head>

    <body class="bg-grey">
    	<div class="container-fluid lato-bold">
    		<div class="col-sm-12 bg-grey">
    			<div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
    				<p class="blu semistrong" id="tit">
    					<span id="intro lato-regular">PRESENTAZIONE UFFICIALE</span>

    				</p>
    				<p class="blu" id="paragraph1">
                        <span class="semistrong desk-block lato-regular">del servizio di Car Sharing elettrico</span>
    					<span class="semistrong desk-block lato-regular">SHARE’NGO a Firenze</span>
                        <span class="semistrong desk-block lato-regular"><span class="lato-bold">MERCOLED&Igrave; 14 OTTOBRE, ORE 12.00</span></span>
                        <span class="semistrong desk-block lato-regular">Palazzo Vecchio, Sala Degli Elementi</span>
					</p>
                    <p class="blu" id="paragraph1a">
                        <span class="semistrong2 desk-block lato-bold">VUOLE ESSERE TRA I PRIMI</span>
                        <span class="semistrong2 desk-block lato-bold">100 FIORENTINI</span>
                        <span class="semistrong2 desk-block lato-bold">A GUIDARLA USCENDO DA</span>
                        <span class="semistrong2 desk-block lato-bold">PALAZZO VECCHIO? </span>
                    </p>
    			</div>
    			<div class="col-sm-7 col-sm-pull-5 img-desk">
    				<img src="/firenze/application/images/firenze-top.jpg" class="img-responsive"/>
    			</div>
    			<div class="col-sm-7 col-sm-pull-5 img-mobile">
    				<img src="/firenze/application/images/firenze-top.jpg" class="img-responsive"/>
    			</div>
    		</div>
    		<div class="col-sm-12 bg-grey">
    			<div class="col-sm-7 img-desk">
    				<img src="/firenze/application/images/firenze-bottom.jpg" class="img-responsive"/>
    			</div>
    			<div class="col-sm-7 img-mobile">
    				<img src="/firenze/application/images/firenze-bottom.jpg" class="img-responsive"/>
    			</div>
    			<div class="col-sm-5 text-center p-top-5" id="second-paragraph">

    				<p class="blu semistrong" id="registrati">
    					<a href="http://www.equomobili.it/?codice_sconto=100FI" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: '100FI 1'});">
    						<span class="lato-regular">BASTA CHE SI REGISTRI</span>
                            <span class="lato-regular">A SHARE’NGO</span>
                            <span class="lato-regular">OGGI O DOMANI</span>
                            <span class="lato-regular">CON IL CODICE SPECIALE</span>
    					</a>
					</p>
					<a href="http://www.equomobili.it/?codice_sconto=100FI" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: '100FI 2'});">
						<button class="semistrong">100FI</button>
					</a>

                    <p class="blu smaller">
                        <span class="lato-regular">CON 1 € AVRÀ I SUOI PRIMI 100 MINUTI</span>
                        <span class="lato-regular">GRATUITI + LA SMART CARD APRIPORTA</span>
                        <span class="lato-regular">CHE LE CONSEGNEREMO AL SUO ARRIVO</span>
                        <span class="lato-regular">IN SALA DEGLI ELEMENTI.</span>
                    </p>

                   <div id="logo"></div>
    			</div>

    		</div>
    	</div>
    </body>