<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/falacosagiusta/application/css/style.css" rel="stylesheet">

        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-grey">
        <div class="container-fluid lato-bold">
            <div class="col-sm-12 bg-grey">
                <div class="col-sm-7 col-sm-pull-5 img-mobile">
                    <img src="/falacosagiusta/application/images/lifegate-top.jpg" class="img-responsive"/>
                </div>
                <div class="col-sm-7 img-mobile">
                    <img src="/falacosagiusta/application/images/lifegate-bottom.jpg" class="img-responsive"/>
                </div>
                <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">



                    <p class="white" id="paragraph1">
                        <span class="strong desk-block lato-regular">Se sei un fan o un amico di</span>


                        <span class="lato-bold strong-big">FA' LA COSA GIUSTA!</span></p>

                    <p class="white" id="paragraph1a">

                        <span class="strong desk-block lato-regular">Iscriviti oggi con 1 €
                            <span class="strong desk-block lato-regular">usi
                                a MILANO, FIRENZE e ROMA</span>
                            <span class="strong desk-block lato-regular">le auto elettriche</span>
                            <span class="strong desk-block lato-regular">e condivise di SHARE’NGO</span>
                            <span class="strong desk-block lato-regular">col 15% di sconto sulle corse!</span>

                    </p>
                </div>
                <div class="col-sm-7 col-sm-pull-5 img-desk">
                    <img src="/falacosagiusta/application/images/lifegate-top.jpg" class="img-responsive"/>
                </div>

            </div>
            <div class="col-sm-12 bg-grey">
                <div class="col-sm-7 img-desk">
                    <img src="/falacosagiusta/application/images/lifegate-bottom.jpg" class="img-responsive"/>
                </div>

                <div class="col-sm-5 text-center p-top-5" id="second-paragraph">

                    <p class="white strong" id="registrati">
                        <span class="lato-bold">ISCRIVITI OGGI SU:</span>
                    </p>


                    <a href="<?= $this->url('promocode-signup',['promocode' => 'FLCG']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'FAO'});"><button class="strong">FLCG</button></a>
                        
                    </a>
                    <p></p>
                    <p class="white strong" id="paragraph2">
                        <span class="lato-regular">BASTANO 5 MINUTI E UN CLICK</span>
                    </p>


                </div>

            </div>
        </div>
    </body>
</html>