<!DOCTYPE html>
<html lang="en">
  	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	
		<script type="text/javascript" src="js/jquery.1.11.3.min.js"></script>
		
		
		 <!-- Bootstrap -->
		<link href="css/bootstrap.css" rel="stylesheet">
		<script type="text/javascript" src="js/bootstrap.js"></script>
   
		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		
		<link href="css/style.css" rel="stylesheet">

        <script>
        
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');

        </script>

    </head>
    
    <body class="bg-blue">
    	<div class="container-fluid lato-bold">
    		<div class="row bg-white">
                <div class="col-lg-7 col-md-8">
                    <img src="img/sharengo_img.jpg" class="img-responsive"/>
                </div>
    			<div class="col-lg-5 col-md-4 text-center" >                    
    				
                    <div id="first-paragraph"> 	
                    
                    <span class="lato-regular strong-big blue">TUTTO IL PERSONALE DEL</span>
                    
                    
                    <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    <img src="img/logo_gemelli.png" width="299" height="154" alt="logo policlinico gemelli"> 
                    
                    
                    <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    <span class="lato-regular strong-big blue">UTILIZZA LE AUTO ELETTRICHE<br/>E CONDIVISE DI</span>
                    <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    <img src="img/logo_sharengo.png" width="299" height="126" alt="logo sharengo"> 
                    </div>
                    
                    <div id="container-paragraph">
                    <div id="first-paragraph-due" style="text-align:left;">
                    </div>
                    </div>
                    
                    <span class="lato-regular strong-small blue">A QUESTE CONDIZIONI:</span>
                    
                    <br class="visible-md visible-lg">
					<br class="visible-xs visible-sm">
                    
                    <div id="container-paragraph">
                    <div id="first-paragraph-due" style="text-align:left;">
                    <span class="lato-regular strong-small blue">
                    <ul class="lato-regular strong-small blue marginleft" style="list-style-type:none; padding-bottom:10px;padding-top:10px;">
                     <li>&#8226; ISCRIZIONE RIDOTTA DA 10 A 5€</li>
                     <li>&#8226; TARIFFA A 0,22€/MIN INVECE DI 0,28€/MIN</li>
                     <li>&#8226; 15 MINUTI DI CORSA GRATUITA</li>
                     </ul>
                     </span>
                     </div>
                     </div>                                    
                        
                        <span class="lato-regular strong-more-small grey">
                        
                        CODICE PROMO</span>
                        <div class="text-center space">
                        <a href="http://www.sharengo.it/signup" id="submit" class="button">FPG17</a>
                        </div>
				</div>
                        </p>
                    </div>
    			</div>  			
    		</div>
    	</div>
    </body>
    
