<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

         <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/green/application/css/style.css" rel="stylesheet">

        <script>

            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');

        </script>
    </head>

        <body class="bg-white">
    	<div class="container-fluid lato-bold">
    		<div class="row bg-grey  bg-white">
                <div class="col-lg-7 col-md-8 content">
                    <a href="https://www.sharengo.it/signup"><img src="/green/application/images/sharengo_img_fi.png" class="img-responsive"/></a>
                </div> <!-- col-lg-7 col-md-8 -->

    			<div class="col-lg-5 col-md-4 text-center sidebar" >
    				<div id="first-paragraph" style="text-align:left; padding-left:10px; padding-top:10px;">

                    	<span class="lato-BOLD strong-big grey">



                        <ul class="lato-regular strong-small grey" style="padding-top:20px; padding-left:22px; padding-right:10px; list-style: none outside none;">
                        <li><img src="/green/application/images/Icone1.png" class="img-responsive" style="float:left;"><span class="lato-regular strong-small green" >Inquinamento zero<br><span class="strong-more-small grey">Le nostre auto sono amiche dell'ambiente perché sono elettriche, senza emissioni e silenziose.</span></span></li>

                        <li class="li"><img src="/green/application/images/Icone2.png" class="img-responsive" style="float:left;"><span class="lato-regular strong-small green" >Molto divertimento<br><span class="strong-more-small grey">Le trovi sotto casa e le lasci dove vuoi. Entri in ZTL e parcheggi sempre gratis. E sono facili e divertenti da guidare.</span></span><br/>
                     </li>

                        <li class="li"><img src="/green/application/images/Icone3.png" class="img-responsive" style="float:left;"><span class="lato-regular strong-small green" style="">Soldi risparmiati</span><br><span class="strong-more-small grey">Un'auto privata in città non conviene più. Una Share'ngo la usi solo quando ti serve e più ne hai bisogno e meno costa!</span></span><br/></li>
                     </ul>

                        <br class="visible-md visible-lg">
			<br class="visible-xs visible-sm">


                     <img src="/green/application/images/ScaricaAPP.jpg"  usemap="#Map" alt="scarica l'app" class="img-responsive img_btn" style="margin:auto; text-align:center;">
                     <map name="Map" id="Map">
                        <area alt="" title="" href="https://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8" shape="rect" coords="34,160,142,193" />
                        <area alt="" title="" href="https://play.google.com/store/apps/details?id=it.sharengo.eteria" shape="rect" coords="152,161,252,194" />
                     </map>
                     </div> <!-- first-paragraph-due -->
                     </div> <!-- container-paragraph -->


    		</div> <!-- row bg-grey  bg-white -->
    	</div> <!-- container-fluid lato-bold -->
        <img src="https://secure.adnxs.com/px?id=878412&t=2" width="1" height="1" />
        <img src="https://secure.adnxs.com/seg?add=9599541&t=2" width="1" height="1" />
    </body>