<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

    <!-- Bootstrap -->
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link href="/jwt/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/jwt/application/images/JWT-top.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/jwt/application/images/JWT-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
                <p class="white" id="paragraph1a">
                    <span class="strong desk-block lato-regular">I dipendenti</span></p>
                <div id="logo"></div>
                <p class="white" id="paragraph1a">
                    <span class="strong desk-block lato-regular">usano a MILANO, FIRENZE e ROMA</span>
                    <span class="strong desk-block lato-regular">le auto elettriche e condivise</span>
                    <span class="strong desk-block lato-regular">di <span class="lato-bold strong-big">SHARE’NGO</span></span>
                    <span class="strong desk-block lato-regular">con l'iscrizione ridotta</span>
                    <span class="strong desk-block lato-regular">da 10 a 1€, 100 minuti bonus</span>
                    <span class="strong desk-block lato-regular">e la tariffa scontata del 35%</span>
                    <span class="strong desk-block lato-regular">(18cent./minuto).</span>
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/jwt/application/images/JWT-top.jpg" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/jwt/application/images/JWT-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-5 text-center p-top-5" id="second-paragraph">
                <a href="http://www.sharengo.it/promocode-signup/JWT16" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'JWT16'});">
                    <p class="yellow strong" id="registrati">
                        <span class="lato-bold">REGISTRATI OGGI!<br/></span>
                        <span class="white strong lato-regular">CODICE PROMO</span>
                    </p>
                    <button class="strong">JWT16</button>
                </a>
            </div>
        </div>
    </div>
</body>