<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>


         <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/lifegate/application/css/style.css" rel="stylesheet">

        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-63160906-2', 'auto');
          ga('send', 'pageview');

        </script>
    </head>

    <body class="bg-grey">
    	<div class="container-fluid lato-bold">
    		<div class="col-sm-12 bg-grey">
                <div class="col-sm-7 col-sm-pull-5 img-mobile">
                    <img src="/lifegate/application/img/lifegate-top.jpg" class="img-responsive"/>
                </div>
                <div class="col-sm-7 img-mobile">
                    <img src="/lifegate/application/img/lifegate-bottom.jpg" class="img-responsive"/>
                </div>
    			<div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">



    				<p class="white" id="paragraph1">
                        <span class="strong desk-block lato-regular">Se sei un fan o un amico di</span>
					</p>

                    <div id="logo"></div>

                    <p class="white" id="paragraph1a">

                    <span class="strong desk-block lato-regular">Con un click e 1 € usi
                        a <span class="lato-bold">MILANO</span>, <span class="lato-bold">FIRENZE</span> e presto
                        anche a <span class="lato-bold">ROMA</span> le Equomobili
                        elettriche e condivise
                        di <span class="lato-bold strong-big">SHARE’NGO</span>
                        con 100 minuti gratis!</span>

                        <!--<span class="strong desk-block lato-regular">Con un click e 1 € usi</span>
                        <span class="strong desk-block lato-regular">a <span class="lato-bold">MILANO</span>, <span class="lato-bold">FIRENZE</span> e presto</span>
                        <span class="strong desk-block lato-regular">anche a <span class="lato-bold">ROMA</span> le Equomobili</span>
                        <span class="strong desk-block lato-regular">elettriche e condivise</span>
                        <span class="strong desk-block lato-regular">di <span class="lato-bold strong-big">SHARE’NGO</span></span>
                        <span class="strong desk-block lato-regular">con 100 minuti gratis!</span>    -->
                    </p>
    			</div>
    			<div class="col-sm-7 col-sm-pull-5 img-desk">
    				<img src="/lifegate/application/img/lifegate-top.jpg" class="img-responsive"/>
    			</div>

    		</div>
    		<div class="col-sm-12 bg-grey">
    			<div class="col-sm-7 img-desk">
    				<img src="/lifegate/application/img/lifegate-bottom.jpg" class="img-responsive"/>
    			</div>

    			<div class="col-sm-5 text-center p-top-5" id="second-paragraph">

    				<p class="yellow strong" id="registrati">
    					<a href="http://www.equomobili.it/?codice_sconto=GATE" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'GATE 1'});">
    						<span class="lato-bold">REGISTRATI OGGI!</span>
    					</a>
					</p>

                    <p class="white strong" id="paragraph2">
                        <span class="lato-regular">Per te il costo di iscrizione è ridotto</span>
                        <span class="lato-regular">da 10 € a 1 € (fino al 31/03/2016)</span>
                    </p>




					<a href="http://www.equomobili.it/?codice_sconto=GATE" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'GATE 2'});">
                         <p class="white strong" id="paragraph3">
                            <span class="lato-regular">www.equomobili.it</span><br>
                            <span class="lato-regular semistrong">CODICE PROMO</span>
                        </p>
						<button class="strong">GATE</button>
					</a>




    			</div>

    		</div>
    	</div>
    </body>
