<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/market/application/css/style.css" rel="stylesheet">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-blue">
        <div class="container-fluid lato-bold">
            <div class="row bg-grey  bg-blue">
                <div class="col-lg-7 col-md-8">
                    <img src="/market/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
                <div class="col-lg-5 col-md-4 text-center" >
                    <div class="banner">
                        <img src="/market/application/images/logo1.jpg" width = "100%" height = "100%">
                    </div>

                    <div id="first-paragraph">
<!--                    <img src="img/logo.jpg" width="400" height="150" alt="logo gymnasium">-->
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">

                        <span class="lato-regular strong white">Iscriviti subito a <span class="lato-bold strong white">SHARE'NGO</span>
                            <br class="visible-md visible-lg">
                            <br class="visible-xs visible-sm">
                            con solo 5€ e questo codice promo</span>
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">

                        <div class="text-center space">
                            <a href="<?= $this->url('promocode-signup',['promocode' => 'MARKET']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'MARKET'});">MARKET</a>
                        </div>

                        <div id="container-paragraph">
                            <div id="first-paragraph-due" style="text-align:left; padding-left:10px;">
                                <span class="lato-regular strong white">Per i clienti <span class="lato-bold strong white">Carrefour market:</span></span>

                                <br class="visible-md visible-lg">
                                <br class="visible-xs visible-sm">

                                <ul class="lato-regular strong-small white" style="padding-top:10px; padding-left:22px;">
                                    <li><span class="lato-bold strong white">30 minuti di corsa omaggio</span><br/></li>
                                    <li style="padding-top:20px;"><span class="lato-bold strong white">tariffe scontate del 20%</span><br><span class="lato-Light strong white" >(21 Cent/min)</span><br/></li>
                                    <li style="padding-top:20px;"><span class="lato-Light strong white" >ogni <span class="lato-bold strong white">1000 punti</span> PAYBACK  puoi acquistare 50 minuti di corse</li>
                                    <li style="padding-top:20px;"><span class="lato-bold strong white">30 minuti di sosta gratuita</span> <span class="lato-Light strong white" >ogni spesa effettuata nei market</span><br/>
                                     <!--<span class="lato-regular strong-more-small white" >(0,21cent./minuto invece di 0,28cent./minuto)</span>--></li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
