<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>

        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/ordpro/application/css/style.css" rel="stylesheet">

        <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-blue">
        <div class="container-fluid lato-bold">
            <div class="row bg-grey  bg-blue">
                <div class="col-lg-7 col-md-8">
                    <img src="/ordpro/application/images/sharengo_img.jpg" class="img-responsive"/>
                </div>
                <div class="col-lg-5 col-md-4 text-center" >
                    <div id="first-paragraph">
                        <span class="lato-regular strong white">
                        GLI ISCRITTI AL
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        COLLEGIO DEI PERITI
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        INDUSTRIALI E DEI
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        PERITI INDUSTRIALI
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        LAUREATI DI MILANO
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        E LODI
                        <p></p>
                        usano a MILANO,
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        ROMA e FIRENZE
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        le auto elettriche
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        e condivise di
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        </span>
                     	<span class="lato-bold strong-more-big white">SHARE'NGO</span>
                       <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        <span class="lato-regular strong white">
                        con l’iscrizione ridotta
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        da 10 a 1 €, 100 minuti
                        <br class="visible-md visible-lg">
                        <br class="visible-xs visible-sm">
                        bonus e la tariffa
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        scontata del 35%</span>
                        <br class="visible-md visible-lg">
                     	<br class="visible-xs visible-sm">
                        <span class="lato-regular strong-small white">(18 cent./minuto)</span>
                        <p></p>
                        <span class="lato-bold strong-big yellow">Registrati oggi!</span>
                        <div class="text-center space">
                            <p class="strongyellow">
                                <a href="<?= $this->url('promocode-signup',['promocode' => 'ORDPRO']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'ORDPRO'});">ORDPRO</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>