<!DOCTYPE html>
<html lang="it"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Una rivoluzione silenziosa. La mobilità urbana a quattro ruote sarà elettrica e condivisa: zero emissioni, zero rumore, l’auto solo quando serve.">
	<meta name="robots" content="noodp">
	<link rel="canonical" href="https://site.sharengo.it/">
	<link rel="shortcut icon" type="image/x-icon" href="/politecnico/application/images/favicon.png">
	<meta property="og:locale" content="it_IT">
	<meta property="og:type" content="website">
	<meta property="og:title" content="Sharengo. Elettrica, condivisa e sottocasa.">
	<meta property="og:description" content="Una rivoluzione silenziosa. La mobilità urbana a quattro ruote sarà elettrica e condivisa: zero emissioni, zero rumore, l’auto solo quando serve.">
	<meta property="og:url" content="https://site.sharengo.it/">
	<meta property="og:site_name" content="Sharengo">
	<meta property="og:image" content="http://site.sharengo.it/wp-content/uploads/2016/12/20161214_Facebook_Preview.jpg">
	<meta name="twitter:card" content="summary">
	<meta name="twitter:description" content="Una rivoluzione silenziosa. La mobilità urbana a quattro ruote sarà elettrica e condivisa: zero emissioni, zero rumore, l’auto solo quando serve.">
	<meta name="twitter:title" content="Sharengo. Elettrica, condivisa e sottocasa.">
	<meta name="twitter:site" content="@Share_N_Go">
	<meta name="twitter:image" content="http://site.sharengo.it/wp-content/uploads/2016/12/20161214_Facebook_Preview.jpg">
	<meta name="twitter:creator" content="@Share_N_Go">

    <title>POLIMI e Sharengo</title>

    <!-- Bootstrap core CSS -->
    <link href="/politecnico/application/css/bootstrap.min.css" rel="stylesheet"> 
	<!-- Custom -->
	<link href="/politecnico/application/css/style.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-63160906-2', 'auto');
		ga('send', 'pageview');
	</script>
  </head>

  <body id="page-top">

    <!-- Header -->
    <header id="top" class="text-center">
      <div class="container">
		<hr class="line50">
		<h1>POLIMI e <img src="/politecnico/application/images/logo.png" alt="sharengo"></h1>
		<h2>insieme per la mobilità sostenibile</h2>
		<hr class="line80">
		<h3>Tariffa scontata del 15% a 0,24€/min per<br>
		tutti gli studenti e il personale dell’Ateneo.</h3>
      </div>
    </header>

    <!-- Tariffa e call to action -->
    <section id="tariffa" class="text-center">
      <div class="container">
		<div class="row">
			<div class="center_table">
			<ul>
				<li>Registrati a Sharengo con la tua mail del Politecnico<br></li>
				<li>Inserisci il codice promo <strong>POLIMI</strong><br></li>
				<li>Attiva la promozione acquistando il Pacchetto Benvenuto<br></li>
			</ul>
			</div>
			
		</div>
		<a href="<?= $this->url('promocode-signup',['promocode' => 'POLIMI']); ?>" id="submit" class="button" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'POLIMI'});"><img id="btn_provala" src="/politecnico/application/images/button.png" alt="Provala oggi"></a>
      </div>
    </section>
	
	<!-- Vantaggi -->
    <section id="vantaggi" class="text-center">
      <div class="container">
		
		<h2 class="text-center">Sharengo è:</h2>
		
		<div class="row litem">
			<img src="/politecnico/application/images/icon_car.png" alt="facile">
			<h3>Facile</h3>
			<div class="testo">
			Iscriverti non costa nulla e dopo aver inserito il promo code POLIMI attiva il tuo account acquistando il Pacchetto Benvenuto a 5€ e 21 minuti. 
			</div>
		</div>
		<div class="row litem">
			<img src="/politecnico/application/images/icon_park.png" alt="facile">
			<h3>Comoda</h3>
			<div class="testo">
			Entri in Area C. Parcheggi gratis sulle strisce blu e nei posteggi dei residenti.<br>
			E non ti preoccupare della ricarica, a quella ci pensiamo noi.
			</div>
		</div>
		<div class="row litem">
			<img src="/politecnico/application/images/icon_money.png" alt="facile">
			<h3>Conveniente</h3>
			<div class="testo">
			Con i Pacchetti Minuti corri fino a 0,22€/min. Cerca le Free 5' e Free 10' sull’App o su <a href="https://mobile.sharengo.it/">https://mobile.sharengo.it</a> i primi 5’ o 10’ minuti sono gratis.
			</div>
		</div>
		<div class="row litem">
			<img src="/politecnico/application/images/icon_female.png" alt="facile">
			<h3>Amica delle Donne</h3>
			<div class="testo">
			Le donne possono uscire la sera e tornare a casa in sicurezza con 3€ e 30 min (0,10€/min).<br>
			Il car sharing elettrico di Sharengo non inquina ed è amico dell’ambiente.
			</div>
		</div>

      </div>
    </section>

    <!-- Immagine del footer -->
    <section id="footer" class="text-center">
     <img src="/politecnico/application/images/footer.png" class="img-fluid" alt="polimi">
    </section>
</body></html>