<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>


    <!-- Bootstrap -->
    <link href="/common/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

    <link href="/roma/application/css/style.css" rel="stylesheet">

    <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-63160906-2', 'auto');
        ga('send', 'pageview');
    </script>
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/roma/application/images/lifegate-top.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/roma/application/images/lifegate-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-6 col-sm-push-6 text-center" id="first-paragraph">
                <p class="white" id="paragraph1"><span class="strong desk-block lato-regular">Se hai ricevuto il nostro invito con un click e 1 € entri nello</span></p>
                <p class="strongyellowTitolo">SHARE'NGO CLUB di Roma</p>
                <p class="white" id="paragraph2"><span class="strong desk-block lato-regular">e da oggi usi le nostre auto elettriche e condivise con 250 minuti di test drive gratuito, utilizzabili per 90 giorni.</span>
                </p>
            </div>
            <div class="col-sm-6 col-sm-pull-6 img-desk">
                <img src="/roma/application/images/lifegate-top.jpg" class="img-responsive" />
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-6 img-desk">
                <img src="/roma/application/images/lifegate-bottom.jpg" class="img-responsive" />
            </div>
            <div class="col-sm-6 text-center p-top-6" id="second-paragraph">
                <a href="http://www.equomobili.it/?codice_sconto=ROMA!" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'ROMA 1'});">
                    <p class="strongyellow">REGISTRATI!</p>
                </a>
                <p class="white strong" id="paragraph3">
                    <span class="lato-regular">La libertà di movimento nel centro di Roma è a distanza di un click.</span></p>
                <p class="yellow strong" id="registrati">
                    <a href="http://www.equomobili.it/?codice_sconto=ROMA!" id="submit" onClick="ga('send', 'event', { eventCategory: 'landing', eventAction: 'click', eventLabel: 'ROMA 2'});">
                        <p class="white strong" id="paragraph4">
                            <span class="lato-regularbt semistrong">CODICE PROMO</span>
                        </p>
                        <p id="paragraph4">
                            <button class="strong">ROMA!</button>
                        </p>
                    </a>
            </div>
        </div>
    </div>
</body>