<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script type="text/javascript" src="/common/application/js/jquery.1.11.3.min.js"></script>
        <!-- Bootstrap -->
        <link href="/common/application/css/bootstrap.css" rel="stylesheet">
        <script type="text/javascript" src="/common/application/js/bootstrap.js"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <link href="/teatro-elfo/application/css/style.css" rel="stylesheet">
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments);
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m);
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>

    <body class="bg-grey">
        <div class="container-fluid lato-bold">
            <div class="col-sm-12 bg-grey">
                <div class="col-sm-7 col-sm-pull-5 img-mobile">
                    <img src="/teatro-elfo/application/images/elfo-top.jpg" class="img-responsive" />
                </div>
                <div class="col-sm-7 img-mobile">
                    <img src="/teatro-elfo/application/images/elfo-bottom.jpg" class="img-responsive" />
                </div>
                <div class="col-sm-5 col-sm-push-7 text-center" id="first-paragraph">
                    <p class="white strong">
                        <span id="intro">Se siete spettatori del Teatro</span>
                    <div id="logo"></div>
                    </p>
                    <p class="white" id="paragraph1">
                        <span class="strong lato-regular">con un click e 5 €* andate o tornate dal teatro con</span>
                        <span class="strong-big lato-bold">SHARE'NGO</span>
                    </p>
                </div>
                <div class="col-sm-7 col-sm-pull-5 img-desk">
                    <img src="/teatro-elfo/application/images/elfo-top.jpg" class="img-responsive" />
                </div>
            </div>
            <div class="col-sm-12 bg-grey">
                <div class="col-sm-7 img-desk">
                    <img src="/teatro-elfo/application/images/elfo-bottom.jpg" class="img-responsive" />
                </div>
                <div class="col-sm-5 text-center p-top-5" id="second-paragraph">
                    <p class="black semistrong">
                        <span class="lato-bold"><strong class="strong-big">REGISTRATEVI OGGI!</strong></span>
                        <br><br>
                        <span class="lato-regular-bold">Per voi il costo di iscrizione è ridotto da 10 a 5 € fino al 31 dicembre 2017 con 30 minuti bonus e lo sconto del 20% sulle tariffe al minuto.</span>
                        <br><br>
                        <span class="white lato-regular">CODICE PROMO</span>
                        <div class="semistrong">
                            <a href="<?= $this->url('promocode-signup', ['promocode' => 'ELFO']); ?>" id="submit" class="button" onClick="ga('send', 'event', {eventCategory: 'landing', eventAction: 'click', eventLabel: 'ELFO'});">
                                <button>ELFO</button>
                            </a>
                        </div>
                    </p>
                    <p class="black semistrong lato-regular" id="nota">* SHARE’NGO ha tariffe personalizzate. Una corsa di 25/30 minuti costa mediamente 5 € (3 € con i minuti a pacchetto).</p>
                </div>
            </div>
        </div>
    </body>