<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link href="/wave5/application/css/style.css" rel="stylesheet">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments);},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m);
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
<a href=" https://www.sharengo.it/signup"><div class="visore"></div></a> <!-- fine visore -->
                       

<div class="container" style="max-width:750px; margin:0 auto;">
<ul class="testo" style="padding-top:20px; padding-left:22px; padding-right:10px; list-style: none outside none;">
                        <li><table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone1.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Inquinamento zero</span><br>Il car sharing amico dell'ambiente lo trovi sotto casa: è elettrico, senza emissioni e silenzioso.</td>
                        </tr>
                        </table></li>
                    
                        <li style="padding-top: 30px;">
                        
                        <table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone2.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Più guidi e più guadagni</span><br>Più conveniente dell’auto privata, con i PUNTI OSSIGENO ti regaliamo corse gratis ogni mese.</td>
                        </tr>
                        </table>
                     </li>
                    
                        <li style="padding-top: 30px;">
                        
                        <table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone3.png" class="img-responsive" style="float:left;"></td>
                        
                        <td><span class="titolo">Bonus da prendere al volo</span><br>Con i bonus da 5,10 o 15 minuti il costo della tua corsa scende fino al 70%.<br/><span class="parentesi">(Su una corsa media da 22 minuti).</span></span><br/></td>
                        </tr>
                        </table>
                        </li>
                     </ul>
                     
                     <div class="" style="position:relative; bottom:0; margin:auto; max-width:100%; text-align:center;">
                     <img src="/wave5/application/images/ScaricaAPP.jpg" alt="scarica l'app" usemap="#Map" class="" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0">
                     <map name="Map" id="Map">
                        <area alt="" title="" href="https://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8" shape="rect" coords="34,160,142,193" />
                        <area alt="" title="" href="https://play.google.com/store/apps/details?id=it.sharengo.eteria" shape="rect" coords="152,161,252,194" />
                     </map>
                     </div>
                     
</div> <!-- container chiuso -->
</body>
</html>