<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<img src="https://secure.adnxs.com/px?id=878412&t=2" width="1" height="1" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SHARE'NGO</title>
<link href="/wave5/application/css/style.css" rel="stylesheet">

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-63160906-2', 'auto');
            ga('send', 'pageview');
        </script>
		<!-- Facebook Pixel Code -->
		<script>
			!function(f,b,e,v,n,t,s)
			{if(f.fbq)return;n=f.fbq=function()
			{n.callMethod? n.callMethod.apply(n,arguments):n.queue.push(arguments)}
			;
			if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
			n.queue=[];t=b.createElement(e);t.async=!0;
			t.src=v;s=b.getElementsByTagName(e)[0];
			s.parentNode.insertBefore(t,s)}(window, document,'script',
			'https://connect.facebook.net/en_US/fbevents.js');
			fbq('init', '423565347840059');
			fbq('track', 'PageView');
		</script>
		<noscript><img height="1" width="1" style="display:none"
			src="https://www.facebook.com/tr?id=423565347840059&ev=PageView&noscript=1"
		/></noscript>
		<!-- End Facebook Pixel Code -->
</head>

<body>
<a href=" https://www.sharengo.it/signup"><div class="visore"></div></a> <!-- fine visore -->
                       

<div class="container" style="max-width:1000px; margin:0 auto;">
<ul class="testo" style="padding-top:20px; padding-left:22px; padding-right:10px; list-style: none outside none;">
                        <li><table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone1.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Inquinamento zero</span><br>Il car sharing amico dell'ambiente lo trovi sotto casa: è elettrico, senza emissioni e silenzioso.</td>
                        </tr>
                        </table></li>
                    
                        <li style="padding-top: 30px;">
                        
                        <table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone2.png" class="img-responsive" style="float:left;"></td><td><span class="titolo">Più guidi e più guadagni</span><br>Più conveniente dell’auto privata, con i PUNTI OSSIGENO ti regaliamo corse gratis ogni mese.</td>
                        </tr>
                        </table>
                     </li>
                    
                        <li style="padding-top: 30px;">
                        
                        <table cellpadding="0" cellspacing="0">                        
                        <tr>
                        <td width="110"><img src="/wave5/application/images/Icone3.png" class="img-responsive" style="float:left;"></td>
                        
                        <td><span class="titolo">Bonus da prendere al volo</span><br>Con i bonus da 5,10 o 15 minuti il costo della tua corsa scende fino al 70%.<br/><span class="parentesi">(Su una corsa media da 22 minuti).</span></span><br/></td>
                        </tr>
                        </table>
                        </li>
                     </ul>
                     
                     <div class="" style="position:relative; bottom:0; margin:auto; max-width:100%; text-align:center;">
                     <table cellpadding="0" cellspacing="0" align="center">
                     <tr>
                     <td colspan="5" style="max-width:600px; width:600px; max-height:161px; background-color:#FFFFFF;"><a href="https://www.sharengo.it/signup"><img src="/wave5/application/images/scaricapp/ScaricaAPP_01.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></td>
                     
                     </tr>
                     <tr>
                     <td style="max-width:35px; width:35px; max-height:39px;  background-color:#FFFFFF;"><img src="/wave5/application/images/scaricapp/ScaricaAPP_02.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></td>
                     <td style="max-width:109px; width:109px; max-height:39px;  background-color:#FFFFFF;"><a href="itms://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8"><img src="/wave5/application/images/scaricapp/ScaricaAPP_03.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></a></td>
                     
                     <td style="max-width:8px; width:8px; max-height:39px;  background-color:#FFFFFF;"></td>
                     
                     <td style="max-width:100px; width:100px; max-height:39px;  background-color:#FFFFFF;"><a href="https://play.google.com/store/apps/details?id=it.sharengo.eteria"><img src="/wave5/application/images/scaricapp/ScaricaAPP_05.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></a></td>
                     <td style="max-width:348px; width:348px; max-height:39px;  background-color:#FFFFFF;"><img src="/wave5/application/images/scaricapp/ScaricaAPP_06.jpg" style="position: relative; bottom: 0; margin:auto; max-width:100%;" border="0" /></td>
                     </tr>
                     </table>
                     
                     
                     </div>
                     
</div> <!-- container chiuso -->


</body>
</html>
