
<!-- Header -->
<header class="main_head">

    <div class="boxed" style="max-width: 1500px;">
        <div class="top_head">
            <h1 class="logo">
            <span>Share'n Go</span>
            <a href="http://sharengo.sk" class="custom-logo-link" rel="home" itemprop="url"><img width="384" height="76" src="/images/logo-1.png" class="custom-logo" alt="logo" itemprop="logo" srcset="/images/logo-1.png 384w, /images/logo-1-150x30.png 150w, /images/logo-1-150x30@2x.png 300w" sizes="(max-width: 384px) 100vw, 384px"></a></h1>
        </div>

        <div class="button_container" id="toggle">
            <span class="top"></span>
            <span class="middle"></span>
            <span class="bottom"></span>
        </div>

        <nav class="menu_main">
            <ul class="menu">
                <li id="menu-item-18" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-18"><a href="http://sharengo.sk/come-funziona/"><?= $this->translate('Come funziona Sharengo')?></a></li>
                <li id="menu-item-17" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-17"><a href="http://sharengo.sk/pacchetti-e-promozioni/"><?= $this->translate('Pacchetti &amp; promozioni')?></a></li>
                <li id="menu-item-258" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-258"><a href="http://sharengo.sk/la-citta-cambia/"><?= $this->translate('La città cambia')?></a></li>
                <li id="menu-item-259" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-259"><a href="http://sharengo.sk/chi-e-sharen-go/"><?= $this->translate('Chi è SharenGo')?></a></li>
                <li id="menu-item-749" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-749"><a href="http://sharengo.sk/vantaggi-per-te/"><?= $this->translate('Vantaggi per te')?></a></li>
                <li id="menu-item-1012" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1012"><a href="http://sharengo.sk/aziende/"><?= $this->translate('Aziende')?></a></li>
                <?php if($this->loggedUser): ?>
                <li id="menu-item-30" class="login menu-item menu-item-type-custom menu-item-object-custom menu-item-30"><a href="<?= $this->url('logout'); ?>"><?= $this->translate('Logout')?></a></li>
                <li id="menu-item-29" class="bottone register menu-item menu-item-type-custom menu-item-object-custom menu-item-29"><a href="<?= $this->url('login'); ?>"><?= $this->translate('Area riservata')?></a></li>
                <?php else: ?>
                <li id="menu-item-30" class="login menu-item menu-item-type-custom menu-item-object-custom menu-item-30"><a href="<?= $this->url('login'); ?>"><?= $this->translate('Accedi')?></a></li>
                <li id="menu-item-29" class="bottone register menu-item menu-item-type-custom menu-item-object-custom menu-item-29"><a href="<?= $this->url('signup'); ?>"><?= $this->translate('Iscriviti')?></a></li>
                <?php endif; ?>

                <select onchange="location = this.value;" style="width: 70px;height: 32px;background: #ffffff;color: #888;font-size: 12px;border: 0;font-weight: 500;">
                    <?php
                    echo '<option selected>'.$this->languageMenuHelper()->getCurrentLanguageLabel().'</option>';
                    foreach ($this->languageMenuHelper()->getLanguages() as $lang) {
                        //echo var_dump($lang);
                        echo '<option value="'.$lang['url'].'">'.$lang['label'].'</option>';
                    } ?>
                </select>
            </ul>
        </nav>
    </div>
</header>
<!-- Header -->
