<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('servizi aggiuntivi'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <!-- Promo code section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!--
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-star"></i> Convenzione aziendale</h2>
                        </div>
                        <form method=post action="#">
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <p> <label>Inserisci il codice azienda</label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type=text class=required name="">
                                    </p>
                                </div>
                                <div class="block-field bw-f w-2-4">
                                    <p> <label>Inserisci la tua email aziendale</label>
                                        <input type=text name="" class=required value="">
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type=submit name="" value=Valida>
                            </div>
                        </form>
                        -->

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-4-4">
                                    <p> <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                        $promoCode = $form->get('promocode')->get('promocode');
                                        echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($promoCode, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type=submit name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->

                    <!-- Margin -->
                    <div class="block-form bw-f margin-separator"></div>

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista Pacchetti'); ?></h2>
                        </div>
                        <!-- title -->

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <!-- Description -->
                        <div>
                            <p>In questa sezione puoi acquistare dei pacchetti promozionali di minuti bonus a dei prezzi vantaggiosi.</p>
                            <p>Nella seguente tabella trovi i pacchetti disponibili con i relativi dati.</p>
                            <p>Clicca sul bottone nella colonna "Acquista" per accedere alla schermata di conferma dove potrai acquistare il pacchetto</p>
                        </div>
                        <!-- description -->

                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">

                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-6">Minuti</div>
                                <div class="block-data-table-th cw-1-6">Prezzo</div>
                                <div class="block-data-table-th cw-1-6">Valido dal</div>
                                <div class="block-data-table-th cw-1-6">Valido fino</div>
                                <div class="block-data-table-th cw-1-6">Disponibile fino</div>
                                <div class="block-data-table-th cw-1-6">Acquista</div>
                            </div>
                            <!-- table header -->

                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                    $i++;
                            ?>

                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-6"><?= $package->getMinutes() . (" min.") ?></div>
                                <div class="block-data-table-td cw-1-6"><?= sprintf("%.2f &euro;", $package->getCost() / 100) ?></div>
                                <div class="block-data-table-td cw-1-6"><?= date_create()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-6">per 90 gg</div>
                                <div class="block-data-table-td cw-1-6"><?= $package->getBuyableUntil()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-6">
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->

                            <?php
                                // end foreach
                                }
                            ?>

                        </div>
                        <!-- table -->

                    </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="bw-f w-1-3 last clearfix"></div>
                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }

    .errors li {
        color: red;
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
?>
