<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', array('route' => 'additional-services')); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('servizi aggiuntivi'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <!-- Promo code section -->
                    <div class="block-form bw-f w-2-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <!--
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-star"></i> Convenzione aziendale</h2>
                        </div>
                        <form method=post action="#">
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <p> <label>Inserisci il codice azienda</label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type=text class=required name="">
                                    </p>
                                </div>
                                <div class="block-field bw-f w-2-4">
                                    <p> <label>Inserisci la tua email aziendale</label>
                                        <input type=text name="" class=required value="">
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type=submit name="" value=Valida>
                            </div>
                        </form>
                        -->

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                        $promoCode = $form->get('promocode')->get('promocode');
                                        echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($promoCode, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type=submit name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->

                    <!-- Margin -->
                    <div class="block-form bw-f margin-separator"></div>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista Pacchetti'); ?></h2>
                        </div>
                        <!-- title -->

                        <?php
                            if (count($bonusPackages) > 0) {
                        ?>

                        <!-- Description -->
                        <div>
                            <p>In questa sezione puoi acquistare dei pacchetti promozionali di minuti bonus a dei prezzi vantaggiosi.</p>
                            <p>Nella seguente tabella trovi i pacchetti disponibili con i relativi dati.</p>
                            <p>Clicca sul bottone dell'ultima colonna per accedere alla schermata di conferma dove potrai acquistare il pacchetto</p>
                        </div>
                        <!-- description -->

                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom">

                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-6">Minuti</div>
                                <div class="block-data-table-th cw-1-6">Prezzo</div>
                                <div class="block-data-table-th cw-1-6">Valido dal</div>
                                <div class="block-data-table-th cw-1-6">Valido fino</div>
                                <div class="block-data-table-th cw-1-6">Disponibile fino</div>
                                <div class="block-data-table-th cw-1-6">Acquista</div>
                            </div>
                            <!-- table header -->

                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                    $i++;
                            ?>

                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7"><?= $package->getMinutes() ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getCost() ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getValidFrom() ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getValidTo() ?></div>
                                <div class="block-data-table-td cw-1-7"><?= 'n.a.' ?></div>
                                <div class="block-data-table-td cw-1-7"><?= 'button' ?></div>
                            </div>
                            <!-- table body -->

                            <?php
                                // end foreach
                                }
                            ?>

                        </div>
                        <!-- table -->

                        <?php
                            // if no packages are available
                            } else {
                        ?>

                        <!-- Description -->
                        <div>
                            <p>In questa sezione troverai i pacchetti di minuti bonus acquistabili ad un prezzo vantaggioso.</p>
                            <p>Al momento non sono disponibili pacchetti promozionali.</p>
                        </div>
                        <!-- description -->

                        <?php
                            }
                        ?>

                    </div>
                    <!-- bonus packages section -->

                    <div class="bw-f w-1-3 last clearfix"></div>
                </div>
            </div>
        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->
</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }

    .errors li {
        color: red;
    }
<?php $this->headStyle()->captureEnd() ?>
