<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <!--<a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>-->

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', array('route' => 'dati-pagamento')); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Dati pagamento'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-3  clearfix">

                        <?php if($this->customer->getFirstPaymentCompleted()): ?>

                            <div class="block-alert margin-bottom info">
                                <p>
                                    <?= $this->translate('Ciao la quota di iscrizione di 10€ è stata regolarmente pagata. Grazie'); ?>.
                                </p>
                            </div>

                        <?php else: ?>

                            <div class="block-alert margin-bottom info">
                                <p><?= $this->translate('Ciao, la quota di iscrizione di 10€ non risulta ancora pagata. Potrai farlo dal 22 al 30 giugno rientrando in area riservata. Grazie'); ?>
                                    <?php /*
                                    <a href="<?php echo $this->url('pay', array('email' => $this->customer->getEmail())); ?>"><button class="medium red"><?= $this->translate("Clicca qui"); ?></button></a> <?= $this->translate("per completare l'attivazione del servizio"); ?>.
                                     */ ?>
                                </p>
                            </div>
                        <?php endif; ?>

                    </div>
                    <!-- block-form -->

                    <!-- block -->
                    <div class="bw-f w-1-3 last  clearfix">

                    </div>
                    <!-- block -->

                </div>
                <!-- module-manage-card -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->