<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Dati pagamento'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-3-3 clearfix">
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-money"></i> <?= $this->translate('Stato pagamenti') ?></h2>
                        </div>

                        <div class="block-alert margin-bottom info">
                        <?php if($this->customer->getFirstPaymentCompleted()): ?>
                            
                                <p>
                                    <?= $this->translate('Il pagamento della quota di iscrizione &egrave; andato a buon fine, grazie'); ?>.
                                </p>
                        <?php else: ?>
                                <p><?= $this->translate('La quota di iscrizione non risulta ancora pagata'); ?>, <a href="<?= $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]) ?>"><button class="medium red"><?= $this->translate("Clicca qui"); ?></button></a> <?= $this->translate("per completare l&#39;attivazione del servizio"); ?>.</p><br>
                                <p><font color="red"><?= $this->translate('Attenzione!') ?></font> <?= $this->translate(' Per completare il pagamento dell’iscrizione e registrare la tua carta di credito (o prepagata) potrebbe esserti chiesto il Secure Code (il codice di sicurezza per i pagamenti online).'); ?></p><br>
                                <p><?= $this->translate('Se non avessi il Secure Code o non l&#39;avessi mai utilizzato, chiedine l&#39;attivazione al gestore della tua carta, prima di proseguire '); ?>(<b><a href="payment-securecode-cartasi">maggiori info</a></b>)</p>
                        <?php endif; ?>
                        </div>
                    </div>
                    <!-- block-form -->
                </div>
                <!-- module-manage-card -->
            </div>
            <!-- module-column-app-content -->
        <?php
        // if necessary create link to the activation page
            if ($this->activateLink) {
        ?>
            <div class="module-column-app-content clearfix">
                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">
                    <p>Hai esaurito i tuoi minuti bonus e hai effettuato una o più corse "a debito". Puoi effettuare manualmente il primo pagamento cliccando sul seguente link.</p>
                    <!-- Activation button -->
                    <div class="block-wrapper-button content-align-center margin-top-custom">
                        <a href="<?= $this->url('area-utente/activate-payments') ?>"><button><?= $this->translate("Maggiori informazioni"); ?></button></a>
                    </div>
                    <!-- activation button -->
                </div>
            </div>
        <?php
            }
        ?>
            <div class="module-column-app-content clearfix">

                <!-- module-manage-card -->
                <div class="module-manage-card padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-3-3 clearfix">

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-credit-card"></i> <?= $this->translate("Carta di credito"); ?></h2>
                        </div>

                        <div class="margin-bottom info">
                            <?php if ($this->contract): ?>
                                <table id ="contract" align="center" class="bw-f" style="width: 70%">
                                    <tbody>
                                        <tr>
                                            <td><?= $this->translate("Data attivazione carta"); ?></td>
                                            <td><?= $this->contract->getInsertedTs()->format('d/m/Y'); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?= $this->translate("Numero carta"); ?></td>
                                            <td><?= $this->contract->getPan(); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?= $this->translate("Scadenza"); ?></td>
                                            <td><?= implode('/', str_split($this->contract->getPanExpiry(), 4)); ?></td>
                                        </tr>
                                        <tr>
                                            <td><?= $this->translate("Stato"); ?></td>
                                            <td>
                                                <?php if ($this->contract->getDisabledDate()): ?>
                                                    <?= $this->translate("Carta disabilitata "); ?> <?= $this->contract->getDisabledDate()->format('Y-m-d H:i:s'); ?>
                                                <?php else: ?>
                                                    <?= $this->translate("Carta attiva "); ?>
                                                <?php endif; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td></td>
                                            <td>
                                                <a href="<?= $this->url('area-utente/disable-contract', [], ['query' => ['contractId' => $this->contract->getId()]]) ?>"><button class="medium red" onclick="return confirm('<?= $this->translate("Voi cambiare la carta di credito?"); ?>')"><?= $this->translate("Cambia carta"); ?></button></a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            <?php else: ?>
                                <div class="col-lg-12"><?= $this->translate("Non hai ancora inserito una carta di credito o prepagata sul tuo profilo."); ?></div>
                            <?php endif; ?>

                        </div>
                    </div>
                    <!-- block-form -->
                </div>
                <!-- module-manage-card -->
            </div>
        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->
</div>
<!-- main -->
