<?php
    // get data
    $customer = $this->customer;
    $contract = $this->contract;
    $tripPayment = $this->tripPayment;
    $tripsToBePayedAndWrong = $this->tripsToBePayedAndWrong;
    $extraPayments = $this->extraPayments;
    $scriptIsRunning = $this->scriptIsRunning;
    $totalCost = $this->totalCost;
    $totalExtraCost = $this->totalExtraCost;
    $serverInstance = $this->serverInstance;

    // parse data
    $name = ucwords(strtolower($customer->getName() . ' ' . $customer->getSurname()));
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Pagamenti in sospeso'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume content -->
                <div class="module-sharing-resmume padding-top">
                    <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                    <!-- Description -->
                    <div>
                    <p><?= $this->translate("Ciao")?> <?= $name ?>,</p><br>
                        <?php if ($customer->getFirstPaymentCompleted()) {
                            if ($totalCost===0) {?>
                                <p style="text-align: justify"><?= $this->translate("complimenti, tutte le tue corse risultano regolarmente pagate.") ?></p>
                                <hr>
                            <?php } else { ?>

                                <p style="text-align: justify"><?= $this->translate("hai esaurito i tuoi crediti e hai effettuato corse a debito.") ?></p>
                                <p style="text-align: justify"><?= $this->translate("Ti invitiamo ad effettuare il pagamento con un carta di credito valida (anche pre-pagata), ricordiamo che &egrave; possibile cambiare la propria carta di credito nella sezione 'Dati di Pagamento' dell'area riservata.") ?></p><br>
                                <p style="text-align: justify"><?= $this->translate("Di seguito i dettagli:") ?></p>
                                <!-- map popup -->
                                <div id="map-popup" class="map-popup"></div>
                                <!-- map popup -->

                                <!-- Trip table -->
                                <div class="block-data-table clearboth clearfix margin-top-custom">

                                    <!-- Trip table headers -->
                                    <div class="block-data-table-row clearfix">
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("ID") ?></div>
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("Inizio") ?></div>
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("Fine") ?></div>
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("Durata (min.)") ?></div>
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("Sosta (min.)") ?></div>
                                        <div class="block-data-table-th cw-1-6 text-center"><?= $this->translate("Importo") ?></div>
                                    </div>
                                    <!-- Trip table headers -->

                                    <!-- Trip table body -->
                                    <div class="block-data-table-row-group clearfix">
                                        <?php
                                        foreach ($tripsToBePayedAndWrong as $trip){
                                            echo('<div class="block-data-table-row clearfix even">');
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-center">%s</div>', $trip->getId());
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-center" onclick="loadMapPopup(%s, %s)"><span class="fa fa-map-marker"></span> %s</div>',
                                                $trip->getLatitudeBeginning(),
                                                $trip->getLongitudeBeginning(),
                                                $trip->getTimestampBeginning()->format('d/m/y H:i'));
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-center" onclick="loadMapPopup(%s, %s)"><span class="fa fa-map-marker"></span> %s</div>',
                                                $trip->getLatitudeEnd(),
                                                $trip->getLongitudeEnd(),
                                                $trip->getTimestampEnd()->format('d/m/y H:i'));
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-center">%d</div>', $trip->getDurationMinutes());
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-center">%d</div>', $trip->getParkSeconds()/60);
                                            echo sprintf('<div class="block-data-table-td cw-1-6 text-right">&euro; %s</div>', $trip->getTripPayment()->getTotalCost()/100);
                                            echo('</div>');
                                        }
                                        ?>
                                    </div>
                                    <!-- Trip table body -->
                                    <div class="block-data-table-row-group clearfix border-top">
                                        <div class="block-data-table-row clearfix odd">
                                            <div class="block-data-table-td cw-1-6"></div>
                                            <div class="block-data-table-td cw-1-6"></div>
                                            <div class="block-data-table-td cw-1-6"></div>
                                            <div class="block-data-table-td cw-1-6"></div>
                                            <div class="block-data-table-td cw-1-6 text-center"><?= $this->translate("TOTALE") ?></div>
                                            <div class="block-data-table-td cw-1-6 text-right">&euro; <?=$totalCost/100; ?></div>
                                        </div>
                                    </div>

                                </div>
                                <?php if($scriptIsRunning) { ?>
                                <div style="margin-top: 20px;margin-bottom: 20px">
                                    <span class="block-sub-title">
                                        <b style="color:red"><?= $this->translate("Attenzione:") ?> </b> <?= $this->translate("Pagamento momentaneamente sospeso, riprova più tardi.") ?>
                                    </span>
                                </div>
                                <?php } else { ?>
                                <!-- Confirm button -->
                                <div class="block-wrapper-button content-align-center margin-top-custom">
                                    <?php if(is_null($contract)) { ?>
                                        <a href="<?= $this->url('cartasi/primo-pagamento-corsa-multi') ?>"><button><?= $this->translate("Pagamento corse"); ?></button></a>
                                    <?php } else { ?>
                                        <a href="<?= $this->url('area-utente/debt-collection-payment', [], ['query' => ['mobile' => $this->mobile]]) ?>"><button onclick="return confirm('Procedere con il pagamento?')"><?= $this->translate("Pagamento corse"); ?></button></a>
                                    <?php }?>
                                </div><br>
                                <!-- confirm button -->
                                <?php }?>
                            <?php }
                                  if($totalExtraCost > 0){ ?>
                                      <p style="text-align: justify"><?= $this->translate("Sono presenti penali da pagare.") ?></p>
                                      <p style="text-align: justify"><?= $this->translate("Ti invitiamo ad effettuare il pagamento con un carta di credito valida (anche pre-pagata), ricordiamo che &egrave; possibile cambiare la propria carta di credito nella sezione 'Dati di Pagamento' dell'area riservata.") ?></p><br>
                                      <p style="text-align: justify"><?= $this->translate("Di seguito i dettagli:") ?></p>
                                      <!-- map popup -->
                                      <div id="map-popup" class="map-popup"></div>
                                      <!-- map popup -->

                                      <!-- Trip table -->
                                      <div class="block-data-table clearboth clearfix margin-top-custom">

                                          <!-- Trip table headers -->
                                          <div class="block-data-table-row clearfix">
                                              <div class="block-data-table-th cw-1-4 text-center"><?= $this->translate("ID") ?></div>
                                              <div class="block-data-table-th cw-1-4 text-center"><?= $this->translate("Data generazione") ?></div>
                                              <div class="block-data-table-th cw-1-4 text-center"><?= $this->translate("Descrizione") ?></div>
                                              <div class="block-data-table-th cw-1-4 text-center"><?= $this->translate("Importo") ?></div>
                                          </div>
                                          <!-- Trip table headers -->

                                          <!-- Trip table body -->
                                          <div class="block-data-table-row-group clearfix">
                                              <?php
                                              foreach ($extraPayments as $extraPayment){
                                                  echo('<div class="block-data-table-row clearfix even">');
                                                  echo sprintf('<div class="block-data-table-td cw-1-4 text-center">%s</div>', $extraPayment->getId());
                                                  echo sprintf('<div class="block-data-table-td cw-1-4 text-center">%s</div>', $extraPayment->getGeneratedTs()->format('d/m/Y'));
                                                    $as = '';
                                                    foreach ($extraPayment->getReasons() as $reason){
                                                        $as .= $reason[0][0] . ' || ';
                                                    }
                                                  echo sprintf('<div class="block-data-table-td cw-1-4 text-center">%s</div>', rtrim($as,' || '));
                                                  echo sprintf('<div class="block-data-table-td cw-1-4 text-right">&euro; %d</div>', $extraPayment->getAmount()/100);
                                                  echo('</div>');
                                              }
                                              ?>
                                          </div>
                                          <!-- Trip table body -->
                                          <div class="block-data-table-row-group clearfix border-top">
                                              <div class="block-data-table-row clearfix odd">
                                                  <div class="block-data-table-td cw-1-4"></div>
                                                  <div class="block-data-table-td cw-1-4"></div>
                                                  <div class="block-data-table-td cw-1-4 text-center"><?= $this->translate("TOTALE") ?></div>
                                                  <div class="block-data-table-td cw-1-4 text-right">&euro; <?=$totalExtraCost/100; ?></div>
                                              </div>
                                          </div>

                                      </div>
                                      <?php if($scriptIsRunning) { ?>
                                          <div style="margin-top: 20px;margin-bottom: 20px">
                                    <span class="block-sub-title">
                                        <b style="color:red"><?= $this->translate("Attenzione:") ?> </b> <?= $this->translate("Pagamento momentaneamente sospeso, riprova più tardi.") ?>
                                    </span>
                                          </div>
                                      <?php } else { ?>
                                          <!-- Confirm button -->
                                          <div class="block-wrapper-button content-align-center margin-top-custom">
                                              <?php if(is_null($contract)) { ?>
                                                  <a href="<?= $this->url('cartasi/primo-pagamento-penale-multi') ?>"><button><?= $this->translate("Pagamento penali"); ?></button></a>
                                              <?php } else { ?>
                                                  <a href="<?= $this->url('area-utente/debt-collection-extra-payment', [], ['query' => ['mobile' => $this->mobile]]) ?>"><button onclick="return confirm('Procedere con il pagamento?')"><?= $this->translate("Pagamento penali"); ?></button></a>
                                              <?php }?>
                                          </div><br>
                                          <!-- confirm button -->
                                      <?php }?>

                            <?php } ?>

                            <p style="text-align: justify">
                                <?= $this->translate("Nel caso in cui il tuo debito non venisse saldato, e non avessimo quindi una carta di credito valida associata al tuo profilo utente, l&#39;account sar&agrave; sospeso fino all&#39;avvenuto pagamento (potrai accedere all&#39;area riservata ma non fare il log-in sull&#39;App).") ?>
                            </p><br>

                        <?php } else {  // getFirstPaymentCompleted() false?>
                        <p>
                            <?= $this->translate("benvenuto in Sharengo! Per attivare il tuo account è necessario che acquisti, con carta di credito anche prepagata, il Pacchetto Benvenuto: con 5&euro; hai i primi 21 minuti di corsa ad una tariffa scontata (0,24&euro;/min invece di 0,28&euro;/min) e provi subito la tua Sharengo.") ?>
                        </p>
                        <br>
                        <!-- Confirm button -->
                        <div class="module-wrapper-button margin-bottom content-align-center">
                            <a href="<?= (!is_null($serverInstance) && $serverInstance == "sk_SK") ? $this->url('gpwebpay/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]) : $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]); ?>" class="btn-link x-large ct2"><?= $this->translate('Pacchetto Benvenuto'); ?> <i class="fa fa-plus-circle"></i></a>
                        </div>
                        <!-- confirm button -->
                        <?php } ?>
                    </div>
                    <!-- description -->

                    <?php
                        // close no credit card if

                    ?>


                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
<script type="text/javascript" src="<?= $this->basePath(); ?>/js/debt-collection.js"></script>