<?php
$form = $this->driverLicenseForm->prepare();
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'));
?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <!--<a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>-->

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', array('route' => 'patente')); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('PATENTE'); ?></h1>
                <div class="block-user-info-app">
                    <p class="welcome-message"><?= $this->translate('Ciao'); ?>! <a href="#"> <?= $this->layout()->loggedUser->getName() ?> <?= $this->layout()->loggedUser->getSurname() ?></a></p>
                </div>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-manage-driver-license -->
                <div class="module-manage-driver-license padding-top">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-car"></i> <?= $this->translate('I dati della tua patente'); ?></h2>
                        </div>

                        <div id="viewDriverLicense">
                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Numero patente'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type="text" class="required disabled" name="" value="<?= $this->customer->getDriverLicense(); ?>" >
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilascio da autorit&agrave;'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseAuthority = $form->get('driver')->get('driverLicenseAuthority');
                                        echo $this->formElement($driverLicenseAuthority->setAttribute('class', 'disabled'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata il'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <input type="text" class="required disabled" name="" value="<?= $this->customer->getDriverLicenseReleaseDate()->format('d-m-Y'); ?>" >
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Nome sulla patente'); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getDriverLicenseName(); ?>" >
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata (nazione)'); ?></label>
                                        <?php
                                        $driverLicenseCountry= $form->get('driver')->get('driverLicenseCountry');
                                        echo $this->formElement($driverLicenseCountry->setAttribute('class', 'disabled'));
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Data di scadenza'); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getDriverLicenseExpire()->format('d-m-Y'); ?>" >
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-form-section content-align-center margin-bottom">
                                <h2><i class="fa fa-folder-open"></i> <?= $this->translate('Categoria patente'); ?></h2>
                            </div>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field content-align-center bw-f w-4-4">
                                    <p>
                                        <?php
                                        $value = str_replace("{","", $this->customer->getDriverLicenseCategories());
                                        $value = str_replace("}","",$value);
                                        $driverLicense = explode(',', $value);
                                        $driverLicenseCategories = $form->get('driver')->get('driverLicenseCategories');
                                        foreach ($driverLicenseCategories->getValueOptions() as $key => $value): ?>
                                            <?php echo $key; ?>
                                            <input type='checkbox' class="disabled" name="<?php echo $driverLicenseCategories->getName() ?>[]" value="<?php echo $value; ?>" <?= in_array($key, $driverLicense) ? 'checked' : ''; ?>>
                                        <?php endforeach; ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button id="js-edit" type="button"><?= $this->translate('Modifica'); ?></button>
                            </div>
                        </div>

                        <div id="editDriverLicense" style="display: none;">

                            <?= $this->form()->openTag($form); ?>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Numero patente'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicense = $form->get('driver')->get('driverLicense');
                                        echo $this->formElement($driverLicense);
                                        echo $this->formElementErrors($driverLicense, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilascio da autorit&agrave;'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseAuthority = $form->get('driver')->get('driverLicenseAuthority');
                                        echo $this->formElement($driverLicenseAuthority->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($driverLicenseAuthority, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata il'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                                        <?php
                                        $driverLicenseReleaseDate = $form->get('driver')->get('driverLicenseReleaseDate');
                                        echo $this->formElement($driverLicenseReleaseDate);
                                        echo $this->formElementErrors($driverLicenseReleaseDate, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Nome sulla patente'); ?></label>
                                        <?php
                                        $driverLicenseName = $form->get('driver')->get('driverLicenseName');
                                        echo $this->formElement($driverLicenseName);
                                        echo $this->formElementErrors($driverLicenseName, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Rilasciata (nazione)'); ?></label>
                                        <?php
                                        $driverLicenseCountry= $form->get('driver')->get('driverLicenseCountry');
                                        echo $this->formElement($driverLicenseCountry->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($driverLicenseCountry, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-2-4">
                                    <p> <label><?= $this->translate('Data di scadenza'); ?></label>
                                        <?php
                                        $driverLicenseExpire = $form->get('driver')->get('driverLicenseExpire');
                                        echo $this->formElement($driverLicenseExpire);
                                        echo $this->formElementErrors($driverLicenseExpire, array('class' => 'errors'));
                                        ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-form-section content-align-center margin-bottom">
                                <h2><i class="fa fa-folder-open"></i> <?= $this->translate('Categoria patente'); ?></h2>
                            </div>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field content-align-center bw-f w-4-4">
                                    <p>
                                        <?php
                                        $value = str_replace("{","", $this->customer->getDriverLicenseCategories());
                                        $value = str_replace("}","",$value);
                                        $driverLicense = explode(',', $value);
                                        $driverLicenseCategories = $form->get('driver')->get('driverLicenseCategories');
                                        foreach ($driverLicenseCategories->getValueOptions() as $key => $value): ?>
                                            <?php echo $key; ?>
                                            <label class='control checkbox checkbox--patente'>
                                                <input type='checkbox' name="<?php echo $driverLicenseCategories->getName() ?>[]" value="<?php echo $value; ?>" <?= in_array($key, $driverLicense) ? 'checked' : ''; ?>>
                                            </label>
                                        <?php endforeach; ?>
                                        <?php echo $this->formElementErrors($driverLicenseCategories, array('class' => 'errors')); ?>
                                    </p>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button class="reset" id="js-reset" type="button"><?= $this->translate('Annulla'); ?></button>
                                <button type="submit"><?= $this->translate('Salva modifiche'); ?></button>
                            </div>

                            <?php echo $this->form()->closeTag(); ?>
                        </div>

                    </div>
                    <!-- block-form -->

                    <!-- block -->
                    <div class="bw-f w-1-3 last  clearfix"></div>
                    <!-- block -->
                </div>
                <!-- module-manage-driver-license -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
<?php
if($this->showError) {
    $this->inlineScript()->captureStart();

    echo <<<JS
    $(document).ready(function() {
        $('#viewDriverLicense, #editDriverLicense').toggle();
    });
JS;
    $this->inlineScript()->captureEnd();
}
?>
<?php $this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function() {
        $("#driverLicenseReleaseDate" ).datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0",
            maxDate: "0d"
        });

         $("#driverLicenseExpire" ).datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "+0:+100",
            minDate: "0d"
        });

        $("#js-edit, #js-reset").click(function() {
            $("#viewDriverLicense, #editDriverLicense").toggle();
        });
    });
JS;
$this->inlineScript()->captureEnd(); ?>

