<?php
$this->headScript()
        ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
        ->appendFile($this->basePath('js/ui.datepicker-it.js'))
        ->appendFile($this->basePath('js/signup.js?v=1.7'))
        ->appendFile($this->basePath('js/points.js'))
        ->appendFile($this->basePath('js/banner.js'))
        ->appendFile($this->basePath('js/phone.js'));
$this->headLink()
        ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'));

?>

<!-- main -->
<div id="main" class="detect-window-height" >

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Profilo'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <!-- module-column-app-content -->
            <div class="module-column-app-content clearfix">

                <!-- module-profile -->
                <div class="module-profile clearfix">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-3  clearfix">
                        <br>
                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-user"></i><?= $this->translate("I tuoi dati personali"); ?></h2>
                        </div>

                        <div id="viewProfile">

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Email"); ?></label>
                                        <input type="text" name="" class="disabled" value="<?= $this->customer->getEmail(); ?>" >
                                </div>
                                <div class="block-field bw-f w-2-4"></div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Titolo"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getGender() == 'male' ? $this->translate('Signore') : $this->translate('Signora'); ?>" >
                                </div>
                                <div class="block-field bw-f w-3-4 last">
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Nome"); ?></label>
                                        <input type="text" name="" class="required disabled"  value="<?= $this->customer->getName(); ?>" >
                                    </div>
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Cognome"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getSurname(); ?>" >
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati di nascita"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Stato di nascita"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->profileForm->get('customer')->get('birthCountry')->getValue(); ?>" >
                                </div>
                                <div class="block-field bw-f w-3-4 last">
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Provincia di nascita"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->profileForm->get('customer')->get('birthProvince')->getValue(); ?>" >
                                    </div>
                                    <div class="block-field bw-f w-2-4 last">
                                        <label><?= $this->translate("Comune di nascita"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getBirthTown(); ?>" >
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Data di nascita"); ?></label>
                                    <input type="text" name="" class="required datepicker-date disabled" value="<?= $this->customer->getBirthDate()->format('d-m-Y'); ?>">
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati di residenza"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Stato"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getCountry(); ?>">
                                </div>
                                <div class="block-field bw-f w-3-4 last">
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Provincia"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getProvince(); ?>">
                                    </div>
                                    <div class="block-field bw-f w-2-4 last">
                                        <label><?= $this->translate("Citt&agrave;"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getTown(); ?>">
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Indirizzo"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getAddressName(); ?>" >
                                </div>
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Civico"); ?></label>
                                    <input type="text" name="" class="disabled" value="<?= $this->customer->getAddressNumber(); ?>" >
                                </div>
                                <div class="block-field bw-f w-1-4 last">
                                    <label><?= $this->translate("Cap"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getZipCode(); ?>" >
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Info aggiuntive"); ?></label>
                                    <input type="text" name="" class="disabled" value="<?= $this->customer->getAddressInfo(); ?>" >
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati fiscali"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Codice fiscale"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getTaxCode(); ?>" >
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Preferenze"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Lingua"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->longLanguage($this->customer->getLanguage()); ?>" >
                                </div>
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Citt&agrave; preferita"); ?></label>
                                    <input type="text" name="" class="required disabled" value="<?= $this->customer->getFleet()->getName(); ?>">
                                </div>
                            </div>

                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Condizioni contrattuali"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <input type="checkbox" name="" class="required disabled" <?= $this->customer->getNewsletter()?'checked':'' ?>>
                                    <label><?= $this->profileForm->get('customer')->get('newsletter')->getLabel(); ?></label>
                                </div>
                                <div class="block-field bw-f w-2-4">
                                    <input type="checkbox" name="" class="required disabled" <?= $this->customer->getGeneralCondition1()?'checked':'' ?>>
                                    <label><?= $this->profileForm->get('customer')->get('generalCondition1')->getLabel(); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-wrapper-button content-align-center">
                                <button type="button" id="js-edit-form"><?= $this->translate("Modifica profilo"); ?></button>
                            </div>
                            <!-- block-row-field -->


                        </div><!-- end viewProfile -->

                        <div id="editProfile" style="display: none;">

                            <?php
                            $this->profileForm->prepare();
                            echo $this->form()->openTag($this->profileForm);
                            ?>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Email"); ?></label>
                                        <?php
                                        $email = $this->profileForm->get('customer')->get('email');
                                        $email->setValue($this->customer->getEmail());
                                        echo $this->formElement($email->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($email, ['class' => 'error-sign-up']);
                                        ?>
                                </div>

                                <div class="block-field bw-f w-2-4">

                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Titolo"); ?></label>
                                        <input type="text" name="" class="required disabled" value="<?= $this->customer->getGender() == 'male' ? $this->translate('Signore') : $this->translate('Signora'); ?>" >
                                </div>

                                <div class="block-field bw-f w-3-4 last">

                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Nome"); ?></label>
                                            <?php
                                            $name = $this->profileForm->get('customer')->get('name');
                                            $name->setValue($this->customer->getName());
                                            echo $this->formElement($name->setAttribute('class', 'required'));
                                            echo $this->formElementErrors($name, ['class' => 'error-sign-up']);
                                            ?>
                                    </div>

                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Cognome"); ?></label>
                                        <?php
                                        $surname = $this->profileForm->get('customer')->get('surname');
                                        $surname->setValue($this->customer->getSurname());
                                        echo $this->formElement($surname->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($surname, ['class' => 'error-sign-up']);
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati di nascita"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Stato di nascita"); ?></label>
                                        <?php
                                        $birthCountry = $this->profileForm->get('customer')->get('birthCountry');
                                        $birthCountry->setValue($this->customer->getBirthCountry());
                                        echo $this->formElement($birthCountry->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($birthCountry, ['class' => 'error-sign-up']);
                                        ?>
                                </div>
                                <div class="block-field bw-f w-3-4 last">
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Provincia di nascita"); ?></label>
                                            <?php
                                            $birthProvince = $this->profileForm->get('customer')->get('birthProvince');
                                            $birthProvince->setValue($this->customer->getBirthProvince());
                                            echo $this->formElement($birthProvince->setAttribute('class', 'required'));
                                            echo $this->formElementErrors($birthProvince, ['class' => 'error-sign-up']);
                                            ?>

                                    </div>

                                    <div class="block-field bw-f w-2-4 last">
                                        <label><?= $this->translate("Comune di nascita"); ?></label>
                                            <?php
                                            $birthTown = $this->profileForm->get('customer')->get('birthTown');
                                            $select = '<select name="' . $birthTown->getName() . '" ';
                                            foreach ($birthTown->getAttributes() as $attribute => $value) {
                                                $select .= $attribute . '="' . $value . '" ';
                                            }
                                            $select .= '><option></option></select>';
                                            echo $select;
                                            $input = '<input name="' . $birthTown->getName() . '" ';
                                            foreach ($birthTown->getAttributes() as $attribute => $value) {
                                                $input .= $attribute . '="' . $value . '" ';
                                            }
                                            $input .= ' style="display: none;" value="' . $birthTown->getValue() . '" disabled></ipnut>';
                                            echo $input;
                                            echo $this->formElementErrors($birthTown, ['class' => 'errors']);
                                            ?>
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Data di nascita"); ?></label>
                                        <?php
                                        $birthDate = $this->profileForm->get('customer')->get('birthDate');
                                        $birthDate->setValue($this->customer->getBirthDate()->format('d-m-Y'));
                                        echo $this->formElement($birthDate->setAttribute('class', 'required datepicker-date'));
                                        echo $this->formElementErrors($birthDate, ['class' => 'error-sign-up']);
                                        ?>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati di residenza"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Stato"); ?></label>
                                    <?php
                                    $country = $this->profileForm->get('customer')->get('country');
                                    $country->setValue($this->customer->getCountry());
                                    echo $this->formElement($country->setAttribute('class', 'required'));
                                    echo $this->formElementErrors($country, ['class' => 'error-sign-up']);
                                    ?>
                                </div>
                                <div class="block-field bw-f w-3-4 last">
                                    <div class="block-field bw-f w-2-4">
                                        <label><?= $this->translate("Provincia"); ?></label>
                                        <?php
                                        $province = $this->profileForm->get('customer')->get('province');
                                        $province->setValue($this->customer->getProvince());
                                        echo $this->formElement($province->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($province, ['class' => 'error-sign-up']);
                                        ?>
                                    </div>
                                    <div class="block-field bw-f w-2-4 last">
                                        <label><?= $this->translate("Citt&agrave;"); ?></label>
                                        <?php
                                        $town = $this->profileForm->get('customer')->get('town');
                                        $select = '<select name="' . $town->getName() . '" ';
                                        foreach ($town->getAttributes() as $attribute => $value) {
                                            $select .= $attribute . '="' . $value . '" ';
                                        }
                                        $select .= '><option></option></select>';
                                        echo $select;
                                        $input = '<input name="' . $town->getName() . '" ';
                                        foreach ($town->getAttributes() as $attribute => $value) {
                                            $input .= $attribute . '="' . $value . '" ';
                                        }
                                        $input .= ' style="display: none;" value="' . $town->getValue() . '" disabled></ipnut>';
                                        echo $input;
                                        echo $this->formElementErrors($town, ['class' => 'errors']);
                                        ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Indirizzo"); ?></label>
                                        <?php
                                        $address = $this->profileForm->get('customer')->get('address');
                                        $address->setValue($this->customer->getAddressName());
                                        echo $this->formElement($address->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($address, ['class' => 'error-sign-up']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Civico"); ?></label>
                                    <?php
                                    $address = $this->profileForm->get('customer')->get('addressNumber');
                                    $address->setValue($this->customer->getAddressNumber());
                                    echo $this->formElement($address->setAttribute('class', 'required'));
                                    echo $this->formElementErrors($address, ['class' => 'error-sign-up']);
                                    ?>
                                </div>
                                <div class="block-field bw-f w-1-4 last">
                                    <label><?= $this->translate("Cap"); ?></label>
                                    <?php

                                    $zipCode = $this->profileForm->get('customer')->get('zipCode');
                                    $select = '<select name="' . $zipCode->getName() . '" ';
                                    foreach ($zipCode->getAttributes() as $attribute => $value) {
                                        $select .= $attribute . '="' . $value . '" ';
                                    }
                                    $select .= '><option></option></select>';
                                    echo $select;
                                    $input = '<input name="' . $zipCode->getName() . '" ';
                                    foreach ($zipCode->getAttributes() as $attribute => $value) {
                                        $input .= $attribute . '="' . $value . '" ';
                                    }
                                    $input .= ' style="display: none;" value="' . $zipCode->getValue() . '" disabled></ipnut>';
                                    echo $input;
                                    echo $this->formElementErrors($zipCode, ['class' => 'errors']);

                                    ?>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Info aggiuntive"); ?></label>
                                    <?php
                                    $addressInfo = $this->profileForm->get('customer')->get('addressInfo');
                                    $addressInfo->setValue($this->customer->getAddressInfo());
                                    echo $this->formElement($addressInfo);
                                    echo $this->formElementErrors($addressInfo, ['class' => 'error-sign-up']);
                                    ?>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Dati fiscali"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-2-4">
                                    <label><?= $this->translate("Codice fiscale"); ?></label>
                                        <?php
                                        $taxCode = $this->profileForm->get('customer')->get('taxCode');
                                        $taxCode->setValue($this->customer->getTaxCode());
                                        echo $this->formElement($taxCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($taxCode, ['class' => 'error-sign-up']);
                                        ?>
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Preferenze"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Lingua"); ?></label>
                                        <?php
                                        $language = $this->profileForm->get('customer')->get('language');
                                        $language->setValue($this->customer->getLanguage());
                                        echo $this->formElement($language->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($language, ['class' => 'error-sign-up']);
                                        ?>
                                </div>

                                <div class="block-field bw-f w-1-4">
                                    <label><?= $this->translate("Citt&agrave; preferita"); ?></label>
                                        <?php
                                        $fleet = $this->profileForm->get('customer')->get('fleet');
                                        $fleet->setValue($this->customer->getFleet()->getId());
                                        echo $this->formElement($fleet->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($fleet, ['class' => 'error-sign-up']);
                                        ?>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-1-3 last">
                                    <label><?= $this->translate("Condizioni contrattuali"); ?></label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-2-4">

                                    <label for="newsletter">
                                    <?php
                                    $newsletter = $this->profileForm->get('customer')->get('newsletter');
                                    $newsletter->setChecked($this->customer->getNewsletter());
                                    $newsletter->setAttribute('id', 'newsletter');

                                    echo $this->formElement($newsletter->setAttribute('class', 'required'));
                                    echo $this->formElementErrors($newsletter, ['class' => 'error-sign-up']);
                                    echo $newsletter->getLabel();
                                    ?>
                                    </label>
                                </div>
                                <div class="block-field bw-f w-2-4">
                                    <label for="generalCondition1">
                                    <?php
                                    $generalCondition1 = $this->profileForm->get('customer')->get('generalCondition1');
                                    $generalCondition1->setChecked($this->customer->getGeneralCondition1());
                                    $generalCondition1->setAttribute('id', 'generalCondition1');

                                    echo $this->formElement($generalCondition1->setAttribute('class', 'required'));
                                    echo $this->formElementErrors($generalCondition1, ['class' => 'error-sign-up']);
                                    echo $generalCondition1->getLabel();
                                    ?>
                                    </label>
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <!-- block-row-field -->
                            <div class="block-wrapper-button content-align-center">
                                <button class="reset" id="js-reset-editProfile" type="button"><?= $this->translate('Annulla'); ?></button>
                                <button type="submit"><?= $this->translate('Salva modifiche'); ?></button>
                            </div>
                            <!-- block-row-field -->

                            <?= $this->form()->closeTag(); ?>
                        </div>
                        
                        <div class="block-form-section content-align-center margin-bottom" style="margin-top: 20px;">
                            <h2><i class="fa fa-mobile"></i> <?= $this->translate("Il tuo numero di telefono"); ?></h2>
                        </div>

                        <div id="viewEditMobile">

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <!--<div class="block-wrapper-button content-align-center auto-margin w-2-4">-->
                                <div class="block-field auto-margin w-1-4"
                                    <label><?= $this->translate("Cellulare"); ?></label>
                                    <input type="text" name="" class="disabled" value="<?= $this->customer->getMobile(); ?>" >
                                </div>

                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button type="button" id="js-edit-mobile"><?= $this->translate('Modifica Numero'); ?></button>
                            </div>

                        </div><!--edit mobile -->
                        
                        <div id="editMobile" class="block-row-field clearfix" style="display: none;">

                            <?php
                            $this->mobileForm->prepare();
                            echo $this->form()->openTag($this->mobileForm);
                            ?>

                            <div class="block-field content-align-center auto-margin clearfix w-1-1">

                                    <div class="block-field bw-f w-1-4">
                                        <label><?= $this->translate('Prefisso'); ?></label>
                                        <?php
                                        $dialCode = $this->mobileForm->get('dialCode');
                                        $dialCode->setValue($this->customer->getCountry());
                                        echo $this->formElement($dialCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($dialCode, ['class' => 'error-sign-up']);
                                        ?>
                                    </div>
                                    <div class="block-field bw-f w-1-3">
                                        <p> <label><?= $this->translate('Cellulare'); ?></label>
                                            <?php
                                            $mobile = $this->mobileForm->get('mobile');
                                            $mobile->setValue($this->customer->getMobile());
                                            echo $this->formElement($mobile);
                                            echo $this->formElementErrors($mobile, ['class' => 'error-sign-up']); 
                                            ?>
                                        </p>
                                    </div>

                                    <div class="block-field bw-f last">
                                        <label>&nbsp</label>
                                        <div  style="display: block;" id="buttonCode" >
                                            <button type="button" id="buttonSendCode"><?= $this->translate("INVIA CODICE") ?></button>
                                        </div>
                                    </div>

                            </div>

                            <div class="block-row-field content-align-center clearfix w-1-1">
                                <div id="confirmSmsCode" style="display: none;">
                                    <div class="block-field bw-f w-1-3"  id="textCode">
                                        <p> <label><?= $this->translate('Codice di Verifica'); ?></label>
                                            <?php
                                            $smsCode = $this->mobileForm->get('smsCode');
                                            echo $this->formElement($smsCode);
                                            echo $this->formElementErrors($smsCode, ['class' => 'error-sign-up']);
                                            ?>
                                        </p>
                                    </div>
                                    <br>
                                    <p>
                                        <?= $this->translate("Inserisci qui il codice di verifica inviato via sms") ?><br/>
                                    </p>
                                </div>
                            </div>

                            <div class="block-wrapper-button content-align-center">
                                <button class="reset" id="js-reset-editMobile" type="button"><?= $this->translate('Annulla'); ?></button>
                                <button id="js-sumbimit-editMobile" type="submit"><?= $this->translate('Salva modifiche'); ?></button>
                            </div>
                            <?= $this->form()->closeTag(); ?>
                        </div><!-- editMobile -->

                        <div class="block-form-section content-align-center margin-bottom" style="margin-top: 20px;">
                            <h2><i class="fa fa-unlock-alt"></i> <?= $this->translate("I tuoi dati per l'accesso"); ?></h2>
                        </div>

                        <div id="viewEditPwd">

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field auto-margin w-1-3">
                                    <label><?= $this->translate("Password"); ?></label>
                                    <input type="text" class="required disabled" name="" value="********" >
                                </div>
                            </div>
                            <!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button type="button" id="js-edit-pwd"><?= $this->translate('Modifica Password'); ?></button>
                            </div>

                        </div><!--edir pwd -->

                        <div id="editPwd" style="display: none;">

                            <?php
                            $this->passwordForm->prepare();
                            echo $this->form()->openTag($this->passwordForm);
                            ?>

                            <!-- block-row-field -->
                            <div class="block-row-field clearfix">

                                <div class="block-field bw-f w-1-4">
                                    <p> <label><?= $this->translate("Vecchia password"); ?></label>
                                        <?php
                                        $oldPassword = $this->passwordForm->get('oldPassword');
                                        echo $this->formElement($oldPassword->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($oldPassword, ['class' => 'error-sign-up']);
                                        ?>
                                    </p>
                                </div>

                                <div class="block-field bw-f w-3-4 last">

                                    <div class="block-field bw-f w-2-4">
                                        <p> <label><?= $this->translate("Password"); ?></label>
                                            <?php
                                            $password = $this->passwordForm->get('password');
                                            echo $this->formElement($password->setAttribute('class', 'required'));
                                            echo $this->formElementErrors($password, ['class' => 'error-sign-up']);
                                            ?>
                                        </p>
                                    </div>

                                    <div class="block-field bw-f w-2-4">
                                        <p> <label><?= $this->translate("Ripeti password"); ?></label>
                                            <?php
                                            $password2 = $this->passwordForm->get('password2');
                                            echo $this->formElement($password2->setAttribute('class', 'required'));
                                            echo $this->formElementErrors($password2, ['class' => 'error-sign-up']);
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div><!-- block-row-field -->

                            <div class="block-wrapper-button content-align-center">
                                <button class="reset" id="js-reset-editPwd" type="button"><?= $this->translate('Annulla'); ?></button>
                                <button type="submit"><?= $this->translate('Salva modifiche'); ?></button>
                            </div>
                            <?= $this->form()->closeTag(); ?>
                        </div><!-- editPwd -->

                    </div>
                    <!-- block-form -->

                    <!-- block -->
                    <div class="bw-f w-1-3 last  clearfix">

                        <!-- block-form -->
                        <div class="block-form bw-f w-4-4  clearfix">
                            <!-- user area banner -->
                            <div id="userarea-banner" class="bw-f w-4-4 clearfix">
                            </div>
                            <!-- user area banner -->

                            <div class="block-form-section content-align-center margin-bottom">
                                <h2><?= $this->translate("I tuoi minuti Bonus"); ?></h2>
                            </div>

                            <!-- block-row-field-->
                            <div class="block-row-field clearfix">

                                <div class="block-field block-avatar-app content-align-center">

                                    <input class="required disabled" style="text-align: center; max-width: 200px; margin-top: 10px; font-size: 26px;" type="text" value="<?php echo $this->customer->getTotalBonuses() ?>">
                                    <div style="margin-top: 5px;"></div>
                                    <h2><?= $this->translate('Accreditati'); ?></h2>
                                    <div style="margin-bottom: 15px;"></div>
                                    <input class="required disabled" style="text-align: center; max-width: 200px; font-size: 26px; color: red; margin-top: 5px;" type="text" value="<?php echo $this->customer->getUsedBonuses() ?>">
                                    <div style="margin-top: 5px;"></div>
                                    <h2><?= $this->translate('Utilizzati'); ?></h2>
                                    <div style="margin-bottom: 15px;"></div>
                                    <input id="" class="required disabled" style="text-align: center; max-width: 200px;  font-size: 26px; margin-top: 5px;" type="text" value="<?php echo $this->customer->getResidualBonuses() ?>">
                                    <div style="margin-top: 5px;"></div>
                                    <h2><?= $this->translate('Rimanenti'); ?></h2>
                                </div>
                            </div>
                            <!-- block-row-field -->
                            <br />

                                <div class="block-row-field clearfix">
                                    <div class="block-field block-avatar-app content-align-center">
                                        <div class="block-form-section content-align-center margin-bottom">
                                            <h2><?= $this->translate("Punti OSSIGENO"); ?></h2>
                                        </div>
                                        <div id="PointsO2Img" style="border: 0"></div>
                                    </div>
                                </div>

                                <div class="block-row-field clearfix">
                                    <div class="block-field block-avatar-app content-align-center">
                                        <input class="required disabled" style="text-align: center; max-width: 200px; margin-top: 10px; font-size: 26px;" type="text" value="<?php echo $this->customer->getTotalPointsCurrentMonth() ?>">
                                        <div style="margin-top: 5px;"></div>
                                        <h2><?= $this->translate('Accreditati questo mese'); ?></h2>
                                        <div style="margin-bottom: 15px;"></div>
                                        <input class="required disabled" style="text-align: center; max-width: 200px;  font-size: 26px; margin-top: 5px;" type="text" value="<?php echo $this->customer->getResidualPoints() ?>">
                                        <div style="margin-top: 5px;"></div>
                                        <h2><?= $this->translate('Utilizzabili'); ?></h2>
                                        <input id="PointsOxygen" class="required disabled" style="text-align: center; max-width: 200px;  font-size: 26px; margin-top: 5px; display: none" type="text" value="<?php echo $this->customer->getPositivePoints() ?>">
                                    </div>
                                </div>
                                <br />
                                <div class="block-row-field clearfix">
                                    <div class="block-field block-avatar-app content-align-center">
                                        <div class="block-form-section content-align-center margin-bottom">
                                            <h2><?= $this->translate("Contributo ambientale"); ?></h2>
                                        </div>
                                        <div>
                                            <img src="/img/points_co2.png" alt="CO2" height="200" width="200" style="border: 0">
                                        </div>
                                        <br/>
                                        <div>
                                            <h2 id="co2"></h2>
                                        </div>
                                    </div>
                                </div>

                            <?php if (!$this->customer->getFirstPaymentCompleted()): ?>
                                <br />
                                <a href="<?= (!is_null($this->serverInstance) && $this->serverInstance == "sk_SK") ? $this->url('gpwebpay/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]]) : $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customer->getId()]])?>" style="color: #ff0000;">
                                    <?= $this->translate('Non ho ancora pagato la mia iscrizione al servizio e vorrei farlo adesso.'); ?>
                                </a>
                            <?php endif; ?>



                        </div>
                        <!-- block-form -->

                    </div>
                    <!-- block -->

                </div>
                <!-- module-profile -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->
<?php $this->headStyle()->captureStart() ?>
.error-sign-up {
list-style-type: none;
}

.error-sign-up li {
color: red;
}
<?php $this->headStyle()->captureEnd() ?>

<?php
if ($this->showError) {
    $this->inlineScript()->captureStart();

    echo <<<JS
    $(document).ready(function() {

        var typeForm = '$this->typeForm';

        switch(typeForm) {

            case 'edit-profile':
                $('#viewProfile, #editProfile').toggle();
            break;

            case 'edit-pwd':
                $('#viewEditPwd, #editPwd').toggle();
            break;
            
            case 'edit-mobile':
                $('#viewEditMobile, #editMobile').toggle();
            break;
        }
    });
JS;
    $this->inlineScript()->captureEnd();
}
?>

<script>

    $(document).ready(function() {
        $(".datepicker-date" ).datepicker({
            dateFormat: "dd-mm-yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-100:+0",
            maxDate: new Date(new Date().getFullYear(), 11, 31)
        });

        $("#js-sumbimit-editMobile").hide();
        $("#js-edit-form, #js-reset-editProfile").click(function() {
            $('#viewProfile, #editProfile').toggle();
        });
        $("#js-edit-pwd, #js-reset-editPwd").click(function() {
            $('#viewEditPwd, #editPwd').toggle();
        });
        $("#js-edit-mobile, #js-reset-editMobile").click(function() {
            $('#viewEditMobile, #editMobile').toggle();
            result = phoneJs("<?= $this->customer->getMobile() ?>");
            $("#mobile").val(result["number"]);
            $('#dialCode').val(result["dial_code"]);
        });
    });

    var municipalitiesUrl = "<?= $this->url('core/municipalities') ?>",
            birthTownValue = "<?= $birthTown->getValue() ?>",
            townValue =  "<?=  $this->customer->getTown() ?>",
            zipCodeValue =  "<?=  $this->customer->getZipCode() ?>",
            userId = <?= (string) $this->customer->getId() ?>,
            bannerJsonpUrl = "<?= $this->bannerJsonpUrl['url'] ?>",
            pageLink = "<?= $this->serverUrl(true) ?>";

    loadBanner(bannerJsonpUrl, userId, pageLink);

    if (document.location.pathname === "/area-utente" || document.location.pathname === "/area-utente/mobile" ) {
        $.ajax({
            type: "POST",
            url: "/co2",
            data: {id: userId},
            beforeSend: function () {
                $('#co2').html("<i class='fa fa-spinner fa-pulse fa-2x fa-fw'>");
            },
            success: function (data) {
                $('#co2').html("<p> <?= $this->translate("Hai risparmiato") ?> " + data.toString() + " <?= $this->translate("KG di CO") ?><small><sub>2</sub></small></p><p><?= $this->translate("Grazie!") ?></p>");
            },
            error: function () {
                $('#co2').html("<p>" + data.toString() + "</p>");
            }
        });
    }


</script>