<?php
    $invoices = [];
    $availableDates = $this->availableDates;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', array('route' => 'invoices-list')); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Fatture'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume content -->
                <div class="module-sharing-resmume padding-top">

                    <!-- Filter -->
                    <div class="invoices-filter">

                        <!-- Header -->
                        <p class="invoices-filter-title">Periodo</p>

                        <!-- Select box -->
                        <select id="invoices-filter-select" class="invoices-filter-select">

                            <?php
                                foreach ($availableDates as $date) {
                                    // extract year
                                    $year = (integer) ($date / 100);
                                    // extract month
                                    $month = $date - $year * 100;
                                    $month = (($month < 10) ? '0' : '') . $month;
                                    // add selector option
                                    echo '<option value="' . $date . '">' .
                                        $month . '/' . $year .
                                    '</option>';
                                }
                            ?>

                        </select>
                        <!-- select box -->

                    </div>
                    <!-- filter -->

                    <!-- Invoices table -->
                    <div class="block-data-table clearboth clearfix margin-top-custom">

                        <!-- Invoices table headers -->
                        <div class="block-data-table-row clearfix">
                            <div class="block-data-table-th cw-1-6">N&deg; Fattura</div>
                            <div class="block-data-table-th cw-1-6">Giorno</div>
                            <div class="block-data-table-th cw-1-6">Tipo</div>
                            <div class="block-data-table-th cw-1-6">Netto (&euro;)</div>
                            <div class="block-data-table-th cw-1-6">IVA (&euro;)</div>
                            <div class="block-data-table-th cw-1-6">Download</div>
                        </div>
                        <!-- invoices table headers -->

                        <!-- Invoice table body -->
                        <div id="invoice-table-body">
                            <!-- Content generated in js -->
                        </div>
                        <!-- invoice table body -->

                    </div>
                    <!-- invoices table -->

                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<!-- JavaScript -->
<script type="text/javascript">
var invoicesUrl = "<?= $this->url('core/invoices'); ?>";
var lastPeriod = "<?= $availableDates[0]; ?>";
var downloadLink = "<?= $this->url('pdf/invoices'); ?>/";
</script>
<script type="text/javascript" src="<?= $this->basePath(); ?>/js/invoices.js"></script>
