<?php
    $invoices = [];
    $availableDates = $this->availableDates;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Fatture'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume content -->
                <div class="module-sharing-resmume padding-top">
                    
                    <?php
                        // check if there are any invoices
                        if (!empty($availableDates)) {
                    ?>
                    <h6><?= $this->translate("Attenzione: a partire dal 02.03.2018 le fatture sono emesse mensilmente. Ogni fattura raccoglie tutti i viaggi completati il mese precedente alla data del documento.") ?></h6>
                    <!-- Filter -->
                    <div class="invoices-filter">

                        <!-- Header -->
                        <p class="invoices-filter-title">Periodo</p>

                        <!-- Select box -->
                        <select id="invoices-filter-select" class="invoices-filter-select">

                            <?php
                                foreach ($availableDates as $date) {
                                    // extract year
                                    $year = (integer) ($date / 100);
                                    // extract month
                                    $month = $date - $year * 100;
                                    $month = (($month < 10) ? '0' : '') . $month;
                                    // add selector option
                                    echo '<option value="' . $date . '">' .
                                        $month . '/' . $year .
                                    '</option>';
                                }
                            ?>

                        </select>
                        <!-- select box -->

                    </div>
                    <!-- filter -->

                    <!-- Invoices table -->
                    <div class="block-data-table clearboth clearfix margin-top-custom">

                        <!-- Invoices table headers -->
                        <div class="block-data-table-row clearfix">
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("N&deg; Fattura") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("Data") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("Tipo") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("Netto (&euro;)") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("IVA (&euro;)") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("Totale (&euro;)") ?></div>
                            <div class="block-data-table-th cw-1-7"><?= $this->translate("Download") ?></div>
                        </div>
                        <!-- invoices table headers -->

                        <!-- Invoice table body -->
                        <div id="invoice-table-body">
                            <!-- Content generated in js -->
                        </div>
                        <!-- invoice table body -->

                    </div>
                    <!-- invoices table -->

                    <?php
                        // if there are no invoices
                        } else {
                    ?>

                    <h2><?= $this->translate("Nessuna fattura emessa finora") ?></h2>

                    <?php
                        // close no invoices if
                        }
                    ?>

                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<!-- JavaScript -->
<script type="text/javascript">
var invoicesUrl = "<?= $this->url('core/invoices'); ?>";
var lastPeriod = "<?= (count($availableDates) > 0 ? $availableDates[0] : ''); ?>";
var downloadLink = "<?= $this->url('pdf/invoices'); ?>/";
</script>
<script type="text/javascript" src="<?= $this->basePath(); ?>/js/invoices.js"></script>
