<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <div class="module-column-app side-sx">

            <!--<a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>-->

            <!-- block-nav-app -->
            <nav class="block-nav-app">
                <?php echo $this->partial('partials/menu-user-area', array('route' => 'pin')); ?>
            </nav>
            <!-- block-nav-app -->

        </div>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('PIN'); ?></h1>
                <div class="block-user-info-app">
                    <p class="welcome-message"><?= $this->translate('Ciao'); ?>! <a href="#"> <?= $this->layout()->loggedUser->getName() ?> <?= $this->layout()->loggedUser->getSurname() ?></a></p>
                </div>
            </div>

            <div class="module-column-app-content clearfix">

                <!-- module-sharing-resmume -->
                <div class="module-sharing-resmume padding-top">

                    <div class="pin-title">
                        <?= $this->translate('QUESTO E’ IL PIN CHE TI SEVIRA’ PER UTILIZZARE UN’EQUOMOBILE'); ?>
                    </div>

                    <div style="width:100%; overflow:hidden">

	                    <div id="pin" class="pin-box">
	                    	<?php echo $this->layout()->loggedUser->getPrimaryPin(); ?>
	                    </div>

	                    <div class="pin-warning">
	                    	<?= $this->translate('ATTENZIONE: MEMORIZZALO IN LUOGO SICURO E NON DARLO AD ALTRI'); ?>
	                    </div>

                    </div>

                    <div class="pin-info">
                    	<a href="<?= $this->url('comefunziona'); ?>">
                            <?= $this->translate('Guarda come si usa'); ?>
                        </a>
                    </div>

                </div>
                <!-- module-sharing-resmume -->

            </div>
            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->