<?php
    $this->headScript()
        ->appendFile($this->basePath('js/jquery.redirect.js'))
        ->appendFile($this->basePath('js/reprofiling-rates.js'));
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Tariffe'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <!-- module-column-app-content -->
            <div class="module-column-app-content clearfix">

                <!-- module-rates -->
                <div class="module-rates clearfix">

                    <!-- block-form -->
                    <div class="block-form bw-f w-2-4 clearfix fixresponsive">
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-user"></i><?= $this->translate("Il tuo piano tariffario personale"); ?></h2>
                        </div>

                        <!-- block-form -->
                        <div class="block-form clearfix">
                            <table id ="rates" class="bw-f" style="width: 100%">
                                <thead>
                                    <tr>
                                        <th style="border: none;"></th>
                                        <th><?= $this->translate('Le tue tariffe') ?></th>
                                        <th><?= $this->translate('Invece di') ?></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td><?= $this->translate('Tariffa base della corsa') ?></td>
                                        <td>&euro; <?= number_format(0.28 * (100 - $this->customer->getDiscountRate()) / 100, 2, ',', '.') ?></td>
                                        <td>&euro; 0,28</td>
                                    <tr>
                                    <tr>
                                        <td><?= $this->translate('Tariffa per 1 ora') ?></td>
                                        <td>&euro; <?= number_format(12 * (100 - $this->customer->getDiscountRate()) / 100, 2, ',', '.') ?></td>
                                        <td>&euro; 12,00</td>
                                    <tr>
                                    <tr>
                                        <td><?= $this->translate('Tariffa giornaliera') ?></td>
                                        <td>&euro; <?= number_format(50 * (100 - $this->customer->getDiscountRate()) / 100, 2, ',', '.') ?></td>
                                        <td>&euro; 50,00</td>
                                    <tr>
                                    <tr>
                                        <td><?= $this->translate('Tariffa di prenotazione') ?></td>
                                        <td>&euro; 0,00</td>
                                        <td>&euro; 0,00</td>
                                    <tr>
                                </tbody>
                            </table>
                        </div>

                        <ul>
                            <li><?= $this->translate('Il giorno del tuo compleanno ricevi 30 minuti bonus (per questo giorno)') ?></li>
                            <?php if ($this->customer->getGender() === 'female'): ?>
                                <li><?= $this->translate('Di notte, dall’1 alle 5, le donne possono acquistare un Women Night Voucher (30 minuti a 3 &euro;), per tornare a casa in piena sicurezza pagando 0,10 &euro;/min.') ?></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var userDetailsUrl = "<?= $this->url('area-utente/utente') ?>";
</script>
