<footer class="main_foot">
    <div class="boxed">
        <div id="footer_widget">
            <div class="widget_box seguici">
                <div class="fwidget">
                    <h3><?= $this->translate('Seguici su')?></h3>
                    <div class="menu-social-container">
                        <ul id="menu-social" class="menu"><li id="menu-item-105" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-105"><a target="_blank" href="https://www.facebook.com/Sharengozd/"><i class="_mi _before fa fa-facebook-square" aria-hidden="true"></i><span>facebook</span></a></li>
                            <li id="menu-item-104" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-104"><a target="_blank" href="https://twitter.com/sharengozd"><i class="_mi _before fa fa-twitter-square" aria-hidden="true"></i><span>twitter</span></a></li>
                            <li id="menu-item-106" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-106"><a target="_blank" href="https://www.linkedin.com/company/share'ngo"><i class="_mi _before fa fa-linkedin-square" aria-hidden="true"></i><span>linkedin</span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="fwidget">
                    <div class="textwidget">© Share'ngo Force of Nature EV B.V.</div>
                </div>
            </div>
            <div class="widget_box menu_uno">
                <div class="fwidget">
                    <h3>Sharengo</h3>
                    <div class="menu-menu-foot-1-container">
                        <ul id="menu-menu-foot-1" class="menu">
                            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="https://site.sharengo.nl/contact/"><?= $this->translate('Contatti')?></a></li>
                            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="mailto:job@sharengo.nl"><?= $this->translate('Lavora con noi')?></a></li>
                            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="https://site.sharengo.nl/press/"><?= $this->translate('Press')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box menu_due">
                <div class="fwidget">
                    <h3><?= $this->translate('Supporto')?></h3>
                    <div class="menu-menu-foot-2-container">
                        <ul id="menu-menu-foot-2" class="menu">
                            <li id="menu-item-270" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-270"><a href="https://site.sharengo.nl/privacy/"><?= $this->translate('Privacy')?></a></li>
                            <li id="menu-item-126" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-126"><a target="_blank" href="http://www.sharengo.nl/pdf/Reglement%20Sharengo%202017%20NL.pdf"><?= $this->translate('Contratto di servizio e tariffe')?></a></li>
                            <li id="menu-item-127" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-127"><a target="_blank" href="http://site.sharengo.nl/nl/hoe-werkt-het/"><?= $this->translate('FAQ')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box scarica">
                <div class="fwidget">
                    <h3><?= $this->translate('Scarica l\'App Sharengo')?></h3>
                    <div class="menu-app_footer-container">
                        <ul id="menu-app_footer" class="menu">
                            <li id="menu-item-128" class="app_store menu-item menu-item-type-custom menu-item-object-custom menu-item-128"><a href="https://itunes.apple.com/sk/app/sharengo-sk/id1449719356?l=sk&mt=8">Apple</a></li>
                            <li id="menu-item-129" class="play_store menu-item menu-item-type-custom menu-item-object-custom menu-item-129"><a href="https://play.google.com/store/apps/details?id=it.sharengo.sk">Google</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="dati_legali">
            <p>© Share'ngo Force of Nature EV B.V.</p>
            <p>Newtonweg 2</p>
            <p>2952 BH Alblasserdam</p>
        </div>
    </div>
</footer>
