<footer class="main_foot">
    <div class="boxed">
        <div id="footer_widget">
            <div class="widget_box seguici">
                <div class="fwidget">
                    <h3><?= $this->translate('Seguici su')?></h3>
                    <div class="menu-social-container">
                        <ul id="menu-social" class="menu"><li id="menu-item-105" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-105"><a target="_blank" href="https://www.facebook.com/Sharengozd/"><i class="_mi _before fa fa-facebook-square" aria-hidden="true"></i><span>facebook</span></a></li>
                            <li id="menu-item-104" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-104"><a target="_blank" href="https://twitter.com/sharengozd"><i class="_mi _before fa fa-twitter-square" aria-hidden="true"></i><span>twitter</span></a></li>
                            <li id="menu-item-106" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-106"><a target="_blank" href="https://www.linkedin.com/company/share'ngo"><i class="_mi _before fa fa-linkedin-square" aria-hidden="true"></i><span>linkedin</span></a></li>
                            <li id="menu-item-1468" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-1468"><a target="_blank" href="https://www.instagram.com/sharengozd/"><i class="_mi _before fa fa-instagram" aria-hidden="true"></i><span>instagram</span></a></li>
                        </ul>
                    </div>
                </div>
                <div class="fwidget">
                    <div class="textwidget">© Share'ngo SK 2018</div>
                </div>
            </div>
            <div class="widget_box menu_uno">
                <div class="fwidget">
                    <h3>Sharengo</h3>
                    <div class="menu-menu-foot-1-container">
                        <ul id="menu-menu-foot-1" class="menu">
                            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="mailto:info@sharengo.sk"><?= $this->translate('Contatti')?></a></li>
                            <li id="menu-item-103" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-103"><a href="mailto:info@sharengo.sk"><?= $this->translate('Lavora con noi')?></a></li>
                            <li id="menu-item-102" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-102"><a href="http://site.sharengo.sk/press/"><?= $this->translate('Press')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box menu_due">
                <div class="fwidget">
                    <h3><?= $this->translate('Supporto')?></h3>
                    <div class="menu-menu-foot-2-container">
                        <ul id="menu-menu-foot-2" class="menu">
                            <li id="menu-item-270" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-270"><a href="https://site.sharengo.sk/privacy/"><?= $this->translate('Privacy')?></a></li>
                            <li id="menu-item-126" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-126"><a target="_blank" href="https://site.sharengo.sk/legal-notes/"><?= $this->translate('Contratto di servizio e tariffe')?></a></li>
                            <li id="menu-item-127" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-127"><a target="_blank" href="https://site.sharengo.sk/faq/"><?= $this->translate('FAQ')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box scarica">
                <div class="fwidget">
                    <h3><?= $this->translate('Scarica l’App')?></h3>
                    <div class="menu-app_footer-container">
                        <ul id="menu-app_footer" class="menu">
                            <li id="menu-item-128" class="app_store menu-item menu-item-type-custom menu-item-object-custom menu-item-128"><a href="https://itunes.apple.com/it/app/sharengo-cs/id1093104891?mt=8">Apple</a></li>
                            <li id="menu-item-129" class="play_store menu-item menu-item-type-custom menu-item-object-custom menu-item-129"><a href="https://play.google.com/store/apps/details?id=it.sharengo.eteria">Google</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="dati_legali">
            <p>&copy; Sharengo službu prevádzkuje spoločnosť 4 SALE,s r o zákaznícka linka <strong>+421 905 333 109</strong></p>
            <p>Sídlo: Mäsiarska 40, Košice 04001 IČ0.45323224 <br>Prevádzka: Tomášikova 19, Košice 04001 </p>
        </div>
    </div>
</footer>
