<footer class="main_foot">
    <div class="boxed">
        <div id="footer_widget">
            <div class="widget_box seguici">
                <div class="fwidget">
                    <h3><?= $this->translate('Seguici su')?></h3>
                </div>
                <br>
                <div class="fwidget">
                    <div class="textwidget">
                        <p><a href="https://www.facebook.com/sharengoslovakia/">Facebook</a></p>
                        <p><a href="https://www.instagram.com/sharengo_slovensko/">Instagram</a></p>
                    </div>
                </div>
                <div class="fwidget">
                    <div class="textwidget">© Sharengo Slovensko | CARSHARING s.r.o. | 2019</div>
                </div>
            </div>
            <div class="widget_box menu_uno">
                <div class="fwidget">
                    <h3>Sharengo</h3>
                    <div class="menu-menu-foot-1-container">
                        <ul id="menu-menu-foot-1" class="menu">
                            <li id="menu-item-101" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-101"><a href="https://site.sharengo.sk/kontakty/"><?= $this->translate('Contatti')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box menu_due">
                <div class="fwidget">
                    <h3><?= $this->translate('Supporto')?></h3>
                    <div class="menu-menu-foot-2-container">
                        <ul id="menu-menu-foot-2" class="menu">
                            <li id="menu-item-270" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-270"><a href="<?= $this->basePath('pdf/sk/privacy.pdf')?>"><?= $this->translate('Privacy')?></a></li>
                            <li id="menu-item-126" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-126"><a target="_blank" href="<?= $this->basePath('pdf/sk/contract.pdf') ?>"><?= $this->translate('Contratto di servizio e tariffe')?></a></li>
                            <li id="menu-item-127" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-127"><a target="_blank" href="https://site.sharengo.sk/faq/"><?= $this->translate('FAQ')?></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="widget_box scarica">
                <div class="fwidget">
                    <h3><?= $this->translate('Scarica l’App')?></h3>
                    <div class="menu-app_footer-container">
                        <ul id="menu-app_footer" class="menu">
                            <li id="menu-item-128" class="app_store menu-item menu-item-type-custom menu-item-object-custom menu-item-128"><a href="https://itunes.apple.com/sk/app/sharengo-sk/id1449719356?l=sk&mt=8">Apple</a></li>
                            <li id="menu-item-129" class="play_store menu-item menu-item-type-custom menu-item-object-custom menu-item-129"><a href="https://play.google.com/store/apps/details?id=it.sharengo.sk">Google</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="dati_legali">
            <p>© Sharengo službu prevádzkuje spoločnosť:</p>
            <p>Bratislava: ED Assist, s.r.o., zákaznícka linka <a href="tel:+421 908 911 905">+421 908 911 905</a>, IČO: 45 855 269</p>
            <p>Košice:     CARSHARING s.r.o., zákaznícka linka <a href="tel:+421 911 050 099">+421 911 050 099</a> , IČO: 52 482 430</p>
        </div>
    </div>
</footer>
