<?php

// Find out if a user is logged in
$isLoggedIn = $this->IsLoggedIn();

?>

<!-- module-modal -->
<div id="car-popup" class="module-modal" style="height:100%; position:fixed; display:none">
    <!-- modal-overlay -->
    <div class="modal-overlay">
        <!-- module-pop-up -->
        <div class="module-pop-up" style="margin:180px auto;">
            
            <a id="btn-close" class="btn-close"><i class="fa fa-close"></i></a>
            
            <!-- module-pop-up-content -->
            <div class="module-pop-up-content">
            
                <!-- block-car-data -->
                <div class="block-car-data bg-ct4 clearfix">
                    
                    <div class="block-heading text-align-center">
                        <span class="block-info">Auto scelta</span>
                        <h1 id="licence-plate" class="block-title"></h1>
                    </div>
                    
                    <!-- block-content -->
                    <div class="block-content clearfix">
                        
                        <!-- block-column -->
                        <div id="left-column" class="block-column bw-f w-2-4">
                            <div class="block-image"><img src="images/car.jpg" alt=""></div>
                            
                            <!-- block-label-status -->
                            <div class="block-label-status">
                                <span class="block-info">Stato interni</span>
                                <div class="block-bar">
                                    <!-- value are w25, w50, w75, w100 -->
                                    <div id="int_cleanliness" class="block-bar-value"></div>
                                </div>                                            
                            </div>
                            <!-- block-label-status -->
                            
                            <!-- block-label-status -->
                            <div class="block-label-status">
                                <span class="block-info">Stato esterni</span>
                                <div class="block-bar">
                                    <div id="ext_cleanliness" class="block-bar-value"></div>
                                </div>                                            
                            </div>
                            <!-- block-label-status -->
                            
                        </div>
                        <!-- block-column -->
                        
                        <div id="right-column" class="block-column last bw-f w-2-4">
                         
                            <!-- block-wrapper-car-data-info -->
                            <div class="block-wrapper-car-data-info bg-ct4">
                                <!-- block-car-data-info -->
                                <div class="block-car-data-info">
                                    <span class="block-data-name"><i class="fa fa-map-marker"></i> Dove si trova</span>
                                    <span id="location" class="block-data-value"></span>
                                </div>
                                <!-- block-car-data-info -->
                                <!-- block-car-data-info -->
                                <div class="block-car-data-info">
                                    <span id="km-title" class="block-data-name">
                                        <i id="circle-icon" class="fa fa-sun-o"></i>
                                    Autonomia</span>
                                    <span id="km" class="block-data-value"></span>                                                
                                </div>
                                <!-- block-car-data-info -->
                                
                                <div <?php if($isLoggedIn){echo 'id="btn-reserve"';} ?>
                                 class="block-wrapper-btn">                                            
                                                                    
                                    <a <?php if(!$isLoggedIn){echo 'href="'.$this->url('login').'"';} ?>
                                     class="btn-link ct3">Registrati e prenota <i class="fa fa-angle-right"></i></a>
                                </div>

                                <div id="step2-buttons" class="block-wrapper-btn" style="display:none"> 
                                    <button id="btn-back" class="reset pull-left"><i class="fa fa-angle-left"></i> Annulla</button>
                                    <button id="btn-confirm" class="pull-right ct2">Conferma <i class="fa fa-angle-right"></i></button>
                                </div>
                                
                            </div>
                            <!-- block-wrapper-car-data-info -->
                            
                        </div>
                    </div>
                    <!-- block-content -->
                </div>
                <!-- block-car-data -->
                
            </div>
            <!-- module-pop-up-content -->
            
        </div>
        <!-- module-pop-up -->
    </div>
    <!-- modal-overlay -->
</div>
<!-- module-modal -->

<script>
// handle the second popup

// hold the km value in this var
var oldKm;

var text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec magna rhoncus nunc varius euismod. Nullam interdum a augue sed accumsan. Fusce in quam leo. Pellentesque in tristique est.';

// get the necessary elements
var leftColumn = document.getElementById('left-column');
var rightColumn = document.getElementById('right-column');
var btnReserve = document.getElementById('btn-reserve');
var step2Buttons = document.getElementById('step2-buttons');
var circleIcon = document.getElementById('circle-icon');
var kmTitle = document.getElementById('km-title');
var kmText = document.getElementById('km');
var btnBack = document.getElementById('btn-back');
var btnConfirm = document.getElementById('btn-confirm');

// add the event listeners
btnReserve.addEventListener('click', function(event) {
    reserve();
})
btnBack.addEventListener('click', function(event) {
    reset();
})
btnConfirm.addEventListener('click', function(event) {
    // TODO
})

// create the functions
function reserve()
{
    leftColumn.style.display="none";
    rightColumn.style.width="100%";
    btnReserve.style.display="none";
    step2Buttons.style.display="inline";
    circleIcon.className="fa fa-info-circle";
    kmTitle.innerHTML = "Ricorda che:";
    oldKm = km.innerHTML;
    km.innerHTML = text;
}

function reset()
{
    leftColumn.style.display="block";
    rightColumn.style.width="";
    btnReserve.style.display="inline";
    step2Buttons.style.display="none";
    circleIcon.className="fa fa-sun-o";
    kmTitle.innerHTML = "Autonomia";
    km.innerHTML = oldKm;
}

</script>

<script>
// close the popup when the cross button is pressed

// get the necessary elements
var div = document.getElementById('car-popup');

// add the event listener
$('#btn-close').click(function(e) {
    div.style.display="none";
    reset();
})

 </script>
