<?php

// Find out if a user is logged in
$isLoggedIn = $this->IsLoggedIn();

$userAuth = '';
$userId = '';

if ($isLoggedIn)
{
    $user = $this->LoginProvider();
    $userEmail = urlencode($user->getEmail());
    $userPassword = $user->getPassword();
    $userAuth = $userEmail . ':' . $userPassword . '@';
    $userId = $user->getId();
}

?>

<!-- module-modal -->
<div id="car-popup" class="module-modal" style="height:100%; position:fixed; display:none">
    <!-- modal-overlay -->
    <div class="modal-overlay">
        <!-- module-pop-up -->
        <div class="module-pop-up" style="margin:180px auto;">
            
            <a id="btn-close" class="btn-close"><i class="fa fa-close"></i></a>
            
            <!-- module-pop-up-content -->
            <div class="module-pop-up-content">
            
                <!-- block-car-data -->
                <div class="block-car-data bg-ct4 clearfix">
                    
                    <div class="block-heading text-align-center">
                        <span class="block-info"><?= $this->translate('Auto scelta'); ?></span>
                        <h1 id="licence-plate" class="block-title"></h1>
                    </div>
                    
                    <!-- block-content -->
                    <div class="block-content clearfix">
                        
                        <!-- block-column -->
                        <div id="left-column" class="block-column bw-f w-2-4">
                            <div class="block-image"><img src="images/car.jpg" alt=""></div>
                            
                            <!-- block-label-status -->
                            <div class="block-label-status">
                                <span class="block-info"><?= $this->translate('Stato interni'); ?></span>
                                <div class="block-bar">
                                    <!-- value are w25, w50, w75, w100 -->
                                    <div id="int_cleanliness" class="block-bar-value"></div>
                                </div>                                            
                            </div>
                            <!-- block-label-status -->
                            
                            <!-- block-label-status -->
                            <div class="block-label-status">
                                <span class="block-info"><?= $this->translate('Stato esterni'); ?></span>
                                <div class="block-bar">
                                    <div id="ext_cleanliness" class="block-bar-value"></div>
                                </div>                                            
                            </div>
                            <!-- block-label-status -->
                            
                        </div>
                        <!-- block-column -->
                        
                        <div id="right-column" class="block-column last bw-f w-2-4">
                         
                            <!-- block-wrapper-car-data-info -->
                            <div class="block-wrapper-car-data-info bg-ct4">
                                <!-- block-car-data-info -->
                                <div id="block-right-top" class="block-car-data-info">
                                    <span class="block-data-name"><i class="fa fa-map-marker"></i> <?= $this->translate('Dove si trova'); ?></span>
                                    <span id="location" class="block-data-value"></span>
                                </div>
                                <!-- block-car-data-info -->
                                <!-- block-car-data-info -->
                                <div class="block-car-data-info">
                                    <span id="block-right-bottom-title" class="block-data-name">
                                        <i id="circle-icon" class="fa fa-sun-o"></i>
                                    <?= $this->translate('Autonomia'); ?></span>
                                    <span id="block-right-bottom-text" class="block-data-value"></span>                                                
                                </div>
                                <!-- block-car-data-info -->
                                
                                <div id="btn-reserve" class="block-wrapper-btn">                                            
                                    <a id="reserve-text" <?php if (!$isLoggedIn) echo 'href="' . $this->url('login') . '"'; ?>
                                     class="btn-link ct3"><i class="fa fa-circle-o-notch fa-spin"></i></a>
                                </div>

                                <div id="step2-buttons" class="block-wrapper-btn" style="display:none"> 
                                    <button id="btn-back" class="reset pull-left"><i class="fa fa-angle-left"></i> <?= $this->translate('Annulla'); ?></button>
                                    <button id="btn-confirm" class="pull-right ct2"><?= $this->translate('Conferma'); ?> <i class="fa fa-angle-right"></i></button>
                                </div>

                                <div>
                                    <button id="btn-done" class="ct2" style="display:none; margin:0 auto;"><?= $this->translate('Chiudi'); ?> <i class="fa fa-check"></i></button>
                                </div>
                                
                            </div>
                            <!-- block-wrapper-car-data-info -->
                            
                        </div>
                    </div>
                    <!-- block-content -->
                </div>
                <!-- block-car-data -->
                
            </div>
            <!-- module-pop-up-content -->
            
        </div>
        <!-- module-pop-up -->
    </div>
    <!-- modal-overlay -->
</div>
<!-- module-modal -->

<script>
var isLoggedIn = <?php if ($isLoggedIn) echo 'true'; else echo 'false'; ?>;
var auth = '<?php echo $userAuth; ?>';
var userId = '<?php echo $userId; ?>';
</script>
<script type="text/javascript" src="js/car-popup.js"></script>

