<br>
<hr>
<br>
<div class="block-form-section  margin-bottom">
    <h2>Carte di credito non accetate:</h2>
</div>
<!-- credit card refuse section -->
<div class="block-form bw-f w-4-4  clearfix">
    <div class="bw-f w-1-4 clearfix">
        <div>
            Genius - Unicredit
        </div>
        <div>
            <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/Genius_Card.png') ?>" alt="Genius_Card">
        </div>
    </div>
    <div class="bw-f w-1-4 clearfix">
        <div>
            Bancomat generici
        </div>
        <div>
            <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/bancomat.png') ?>" alt="bancomat">
        </div>
    </div>
</div>