<br>
<div class="block-form bw-f w-3-3 clearfix">
    <div>
        <h3 id="test"><i class="fa fa-credit-card"></i> Non utilizzare bancomat o le seguenti carte di credito:</h3>
    </div>
    <br>
    <div class="block-form bw-f w-4-4  clearfix">
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/visa_reward_debit_card.png') ?>" alt="visa_reward_debit_card">
            </div>
            <div>
                Visa - Reward Debit
            </div>
        </div>
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/maestro_debit_card.png') ?>" alt="maestro_debit_card">
            </div>
            <div>
               Maestro - Debit
            </div>
        </div>
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/Genius_Card.png') ?>" alt="Genius_Card">
            </div>
            <div>
                Genius - Unicredit
            </div>
        </div>
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/platinum_debit_card.png') ?>" alt="platinum_debit_card">
            </div>
            <div>
                Platinum - Debit
            </div>
        </div>
    </div>
    <br>
    <div class="block-form bw-f w-4-4  clearfix">
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/visa_corporate_card.png') ?>" alt="visa_corporate_card">
            </div>
            <div>
                Visa Corporate
            </div>
        </div>
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/visa_fleet_card.png') ?>" alt="visa_fleet_card">
            </div>
            <div>
                Visa - Fleet
            </div>
        </div>
        <div class="bw-f w-1-4 clearfix">
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/mastercard_debit_standard_prepagata.jpg') ?>" alt="mastercard_debit_standard_prepagata">
            </div>
            <div>
                Mastercard - Prepagata
            </div>
        </div>
    </div>
</div>


<!--CSS-->
<style>
    #test{
        color: red;
        font-size: 25px;
        font-weight: bold;
    }  
</style>