<br>
<div class="block-form bw-f w-3-3 clearfix">
    <div>
        <h3 id="test"><i class="fa fa-credit-card"></i> Non utilizzare bancomat o le seguenti carte di credito:</h3>
    </div>
    <br>
    <div class="block-form bw-f w-4-4  clearfix">
        <div class="bw-f w-1-4 clearfix">
            <div>
                Genius - Unicredit
            </div>
            <div>
                <img style="width:160px;" src="<?= $this->basePath('images/credit-card-refuse/Genius_Card.png') ?>" alt="Genius_Card">
            </div>
        </div>
    </div>
</div>

<style>
    #test{
        color: red;
        font-size: 25px;
        font-weight: bold;
    }  
</style>