<div class="module-column-app side-sx">
    <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>
    <nav class="block-nav-app">
        <ul>
            <?php
            $menu = '';
            foreach ($this->container as $page) {
                $menu .= '<li>';
                $menu .= sprintf('<a href="%s" class="%s">', $page->getHref(), $page->isActive() ? 'active' : '');
                $menu .= sprintf('<i class="%s"></i>', $page->get('icon'));
                $menu .= sprintf('<span class="title">%s</span>', $this->translate($page->getLabel()));
                $menu .= '</a>';
                $menu .= '</li>';
            }
            echo $menu;
            ?>
        </ul>
    </nav>
</div>
