<div class="module-column-app side-sx">
    <a class="btn-toogle-column-app js-toogle-column-app"><i class="fa fa-angle-left"></i></a>
    <nav class="block-nav-app">
        <ul>
            <!--the definition of the left menu is in the config/module.config.php at the key "navigation"-->
            <?php
            $menu = '';
            $mobile = substr($this->serverUrl(true), -6) == 'mobile' ? '/mobile' : '';
            foreach ($this->container as $page) {
                $menu .= '<li>';
                $menu .= sprintf('<a href="%s" class="%s">', $page->getHref().$mobile, $page->isActive() ? 'active' : '');
                $menu .= sprintf('<i class="%s"></i>', $page->get('icon'));
                $menu .= sprintf('<span class="title">%s</span>', $this->translate($page->getLabel()));
                $menu .= '</a>';
                $menu .= '</li>';
            }
            echo $menu;
            ?>
        </ul>
    </nav>
</div>
