<ul>
    <!--
    <li><a href=""><i class="fa fa-crosshairs"></i> <?= $this->translate('Noleggia auto'); ?></a></li>
    <li><a href="" <?= $this->route == 'profile' ? 'class="active"' : '' ?>><i class="fa fa-user"></i> <?= $this->translate('Profilo'); ?></a></li>
    <li><a href=""><i class="icon icon-car-small-fff"></i> <?= $this->translate('Noleggi'); ?></a></li>
    <li><a href=""><i class="fa fa-trophy"></i> <?= $this->translate('Bonus'); ?></a></li>
    <li><a href=""><i class="fa fa-file-o"></i> <?= $this->translate('Fatture'); ?></a></li>
    <li><a href=""><i class="fa fa-credit-card"></i> <?= $this->translate('Dati di pagamento'); ?></a></li>
    <li><a href=""><i class="fa fa-tachometer"></i> <?= $this->translate('Patente'); ?></a></li>
    <li><a href=""><i class="fa fa-plus"></i> <?= $this->translate('Servizi aggiuntivi'); ?></a></li>
    <li><a href=""><i class="fa fa-map-marker"></i> <?= $this->translate('Posiziona auto'); ?></a></li>
    -->
</ul>