<script>
    var translations = {
        "send_code": "<?= $this->translate("INVIA CODICE") ?>",
        "promo_code": "<?= $this->translate("Codice promo") ?>",

        "general_condition_title": "<?= $this->translate("Termini e Condizioni Generali di Contratto, Regolamento Tariffario e Privacy") ?>",
        "general_condition_link": "<?= $this->translate("Termini e Condizioni Generali di Contratto") ?>",
        "general_condition1": "<?= $this->translate("Ho letto, compreso e accettato i Termini e Condizioni Generali di Contratto e il Regolamento Tariffario del servizio di car sharing SHARE'N GO&reg;, fornito da C.S. Group S.p.A. e dalle sue controllate: C.S. Firenze S.r.l., C.S. Milano S.r.l. e C.S. Roma S.r.l.") ?>",
        "general_condition2": "<?= $this->translate("Dichiaro ai sensi e per gli effetti di cui agli artt. 1341 e 1342 c.c., avendo letto i presenti Termini e Condizioni Generali di Contratto di accettare espressamente e approvare specificatamente le condizioni di cui agli articoli: 3 (oggetto e parti del contratto), 4 (modifica unilaterale del Contratto), 5 (iscrizione e prenotazione online del Car Sharing SHARE’NGO®), 6 (tariffe e fatturazione), 7 (divieto di sublocazione e di cessione), 8 (esonero di responsabilità), 9 (permesso di guida), 10 (utilizzo dei veicoli. Clausola risolutiva espressa), 11 (sinistro o avaria del veicolo), 12 (furti e vandalismi), 13 (sanzioni in materia di circolazione stradale), 14 (assicurazioni), 16 (decorrenza, durata, rinnovo, sospensione, recesso, risoluzione del contratto), 17 (reclami), 18 (penali), 20 (foro competente).") ?>",

        "regulation_condition": "<?= $this->translate("Regolamento Tariffario") ?>",
        "privacy_condition_link": "<?= $this->translate("Informativa Privacy") ?>",
        "privacy_policy_title": "<?= $this->translate("Informativa sulla privacy") ?>",
        "privacy_policy_text": "<?= $this->translate("Al fine di migliorare il servizio ed essere aggiornato sulle offerte di SHARE&apos;NGO&reg; e dei partner di SHARE’NGO&reg; riservate in via preferenziale e/o esclusiva ai clienti SHARE’NGO®, do il mio consenso a ricevere comunicazioni di SHARE’NGO® via email, SMS o posta, inclusi gli inviti a partecipare a indagini di mercato e sondaggi.") ?>",

        "cancel_button": "<?= $this->translate("Annulla") ?>",
        "next_button": "<?= $this->translate("Avanti") ?>",

        "sms_send": "<?= $this->translate("Invio sms...") ?>",
        "sms_wait": "<?= $this->translate("Sms già inviato, attendere 60 secondi") ?>",
        "sms_sended": "<?= $this->translate("Sms inviato") ?>",
        "sms_error_send": "<?= $this->translate("Errore nell'invio sms") ?>",
        "sms_error_wrong_number": "<?= $this->translate("Numero non corretto, attendere 60 secondi per riprovare") ?>",
        "sms_error_alredy_present": "<?= $this->translate("Numero gi&agrave presente, attendere 60 secondi per riprovare") ?>",
        "sms_button": "<?= $this->translate("INVIA CODICE") ?>",
        "sms_insert": "<?= $this->translate("Inserire numero di telefono") ?>",


        "verify_promocode_invalid": "<?= $this->translate("Il codice inserito non &egrave; valido") ?>",
        "verify_promocode_button": "<?= $this->translate("Applica") ?>",

        "cookies_directive_here": "<?= $this->translate("qui") ?>",

    };

    function translate(key) {
        return translations[key];
    }
</script>
