<?php
    $name = "Test Name";
    $docN = "97566";
    $invoiceDate = "01.05.2015";
    $cardN = "014258";
    $mail = "test@test.it";
    $address = "via test - 7343728";
    $cf = "TESTCFI904S11L";
    $piva = "";
    $amount = "12,93";
    $ccard = "xxxx xxxx xxxx xxxx";
?>

<!-- Top right logo and text -->
<div class="header">
    <img class="logo" src=<?= $this->basePath('images/logox2.png'); ?> alt="">
    <h4>Share`n Go s.r.l.</h4>
    <p>Sede operativa bla bla bla</p>
    <h3 class="table-header">Riepilogo dei viaggi</h3>
</div>

<!-- Big light green box -->
<div class="green-box">

    <!-- Top right table -->
    <table class="table tg">
        <tr>
            <td class="tg-031e">Cliente:</td>
            <td class="tg-031e"><?= $name ?></td>
        </tr>
        <tr>
            <td class="tg-031e">Doc N°:</td>
            <td class="tg-031e"><?= $docN ?></td>
        </tr>
        <tr>
            <td class="tg-031e">Data Fattura:</td>
            <td class="tg-031e"><?= $invoiceDate ?></td>
        </tr>
        <tr>
            <td class="tg-031e">Card:</td>
            <td class="tg-031e"><?= $cardN ?></td>
        </tr>
        <tr>
            <td class="tg-031e">e-mail:</td>
            <td class="tg-031e"><?= $mail ?></td>
        </tr>
    </table>

    <!-- Message -->
    <div class="message">
        <p class="name"><?= $name ?></p>
        <p><?= $address ?></p>
        <p><?= $cf ?></p>
        <p><?= "PIVA: " . $piva ?></p>
    </div>

</div>

<!-- Trip table -->
<div>
    <table class="table tg2">
        <tr>
            <th class="tg2-031e">Data</th>
            <th class="tg2-031e">Ora</th>
            <th class="tg2-031e">Durata</th>
            <th class="tg2-031e">Targa</th>
            <th class="tg2-031e">Partenza</th>
            <th class="tg2-031e">Destinazione</th>
            <th class="tg2-031e">Distanza</th>
        </tr>
        <tr>
            <td class="tg2-031e">30.04.2015</td>
            <td class="tg2-031e">21:00</td>
            <td class="tg2-031e">15 min</td>
            <td class="tg2-031e">EX582BG</td>
            <td class="tg2-031e">Via Salasco 2</td>
            <td class="tg2-031e">Via Santa Croce 4</td>
            <td class="tg2-031e"></td>
        </tr>
        <tr>
            <td class="tg2-031e">30.04.2015</td>
            <td class="tg2-031e">21:15</td>
            <td class="tg2-031e"></td>
            <td class="tg2-031e"></td>
            <td class="tg2-031e"></td>
            <td class="tg2-031e"></td>
            <td class="tg2-031e"></td>
        </tr>
    </table>
</div>

<!-- Lower table header -->
<div class="bottom-header">
    <h3 class="table-header">Importo</h3>
</div>

<!-- Lower big green box -->
<div class="green-box lower-box">
    <table class="table tg">
        <tr>
            <td class="tg-031e">Noleggio</th>
            <td class="tg-031e">3,32</th>
        </tr>
        <tr>
            <td class="tg-031e">Imponibile</td>
            <td class="tg-031e">3,32</td>
        </tr>
        <tr>
            <td class="tg-031e">IVA 22%</td>
            <td class="tg-031e">0,73</td>
        </tr>
        <tr>
            <td class="tg-031e">Totale</td>
            <td class="tg-031e">4,05</td>
        </tr>
        <tr>
            <td class="tg-031e">Abbuono bonus</td>
            <td class="tg-031e">4,05</td>
        </tr>
        <tr>
            <td class="tg-031e">Addebito</td>
            <td class="tg-031e"></td>
        </tr>
    </table>
</div>

<!-- Footer -->
<div class="footer">
    <p>Share`n Go s.r.l.</p>
    <br></br>
    <p>pag 2/2</p>
</div>



<!-- General styles -->
<style>
.logo {
    width: 486px;
    height: 99px;
}
.header {
    position: absolute;
    top: 10px;
    right: 10px;
}
.table-header {
    width: 300px;
    height: 30px;
    background-color: #43a34c;
    padding-top: 4px;
    padding-left: 4px;
}
.line {
    width: 100%;
    height: 3px;
    position: relative;
    top: 225px;
    background-color: #43a34c;
}
.green-box {
    width: 100%;
    height: 400px;
    position: relative;
    top: 225px;
    background-color: #a3e3ac;
    border-style: solid;
    border-width: 3px;
    border-right-width: 0px;
    border-color: #43a34c;
}
.message {
    position: relative;
    top: 200px;
    left: 50px;
    font-size: 20px;
}
.name {
    font-weight: 700;
}
.footer {
    width: 486px;
    float: right;
    position: relative;
    top: 400px;
    font-size: 20px;
}
.bottom-header {
    float: right;
    width: 486px;
    position: relative;
    top: 300px;
}
.lower-box {
    top: 350px;
}
</style>

<!-- Table styles -->
<style type="text/css">
.table {
    border-collapse: collapse;
    border-spacing: 0;
    position: relative;
}

.table td, th {
    font-family:Arial, sans-serif;
    font-size:14px;
    padding:10px 5px;
    border-style:solid;
    overflow:hidden;
    word-break:normal;
}
.tg {
    float: right;
    width: 486px;
    top: -2px;
}
.tg td, th {
    border-width:0px;
    border-top-width:2px;
    border-bottom-width:2px;
    border-color: #43a34c;
}
.tg2 {
    top: 222px;
    width: 100%;
}
.tg2 td {
    border-width:0px;
    border-color:#43a34c;
    color:#333;
}
.tg2 th {
    font-weight:normal;
    border-width:0px;
    border-color:#43a34c;
    color:#333;
    background-color:#43a34c;
}
</style>
