<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;

$mobile = $this->mobile;

?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Ricarica wallet'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Ricarica wallet'); ?></h2>
                        </div>
                        <!-- title -->

                        <!-- Description -->
                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title">
                                <?= $this->translate('Ricarica il tuo wallet con il Pacchetto crediti pi&ugrave; adatto a te ed approfitta delle nostre tariffe scontate.') ?>
                                <br>
                                <?= $this->translate('Prima di scegliere il tuo preferito assicurati di aver completato la tua registrazione con l\'acquisto del Pacchetto Benvenuto.'); ?>
                            </span>    
                        </div>
                        <!-- Description -->

                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Crediti'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Prezzo'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Valido dal'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Valido fino'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"><?= $this->translate('Disponibile fino'); ?></div>
                                <div class="block-data-table-th cw-1-7 text-center"></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    if($package->getType()==="Pacchetto" || $package->getType()==="PacchettoPunti" || $package->getType()==="Ricarica" ){
                                        if($this->customer->getGender()=="male" && $package->getCode()=="WOMEN" ){
                                            continue;
                                        }
                                        if ($package->getCode()=="BENVENUTO" && !$this->showWelcomePackage){
                                            continue;
                                        }

                                        $cost = sprintf("%.2f &euro;", $package->getCost() / 100);
                                        if($package->getCost()==0) {
                                            $cost= $this->translate('GRATUITO');
                                        }

                                        $validFrom = $package->validFromOrToday()->format("d-m-Y");
                                        $validTo = sprintf($this->translate("per %d gg"), $package->getDuration());
                                        $buyableUntil = $package->getBuyableUntil()->format("d-m-Y");

                                        $buyLink =sprintf('<a href="%s" class="buyPackage"><i class="fa fa-plus" title="%s"></i></a>',
                                            $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]),
                                            $this->translate('Acquista'));

                                        if ($package->getCode()=="WOMEN" && $this->verifyWomenVoucher>=1) { //verify number of one month trip
                                            $buyLink =sprintf('<a onclick="verify()"><i class="fa fa-plus" title="%s"></i></a>',
                                                $this->translate('Acquista'));
                                        }

                                        $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                        $i++;
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7 text-center"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $package->getMinutes() ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $cost ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $validFrom ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $validTo ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $buyableUntil ?></div>
                                <div class="block-data-table-td cw-1-7 text-center"><?= $buyLink ?></div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-7-7" style="text-align:justify"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->
                            <?php
                                    }   // end if
                                }   // end foreach
                            ?>

                        </div>
                        <!-- table -->
                        
                          </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="block-form bw-f margin-separator"></div>

                    <!-- Promo code section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-4-4">
                                    <div>
                                        <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                                $promoCode = $form->get('promocode')->get('promocode');
                                                echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                                echo $this->formElementErrors($promoCode, ['class' => 'errors']);
                                                echo $this->form()->openTag($form);
                                                ?>
                                    </div>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type="submit" name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->
                </div>
            </div>
        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->
    <!-- overlay women voucher -->
    <div id="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden"><?= $this->translate('Chiudi') ?></span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> <?= $this->translate('ATTENZIONE') ?></h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: center; font-weight: 500;"><?= $this->translate('Il voucher &eacute; disponibile per un solo acquisto giornaliero.') ?></p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->
</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }
    .errors li {
        color: red;
    }
    .women-voucher {
        font-size: 1.2em;
        width: 180px;
        color: #43a34c;
        word-wrap:break-word;
        font-weight: 700;
    }
    @media (max-width: 680px) {
        .women-voucher {
            font-size: 1.2em;
            width: auto;
        }
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
    $this->headLink()->appendStylesheet($this->basePath('css/overlay.css'));
?>
<script type="text/javascript">
    
    function verify() {
        overlay = $('#sng-overlay');
          overlay.css("visibility", "visible");


        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        });
    }

</script>