<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
$gender = $this->customer->getGender();
$verifyWomenVoucher = $this->verifyWomenVoucher; //verify number of one month trip
$mobile = $this->mobile;

/* 8 marzo  CSD-2139 */
$nowFree = date_create();
$start = date_create('2018-03-08 06:00:00');
$end = date_create('2018-03-09 04:55:00');
?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('promo e pacchetti'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista Pacchetti'); ?></h2>
                        </div>
                        <!-- title -->

                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title">
                                <?= $this->translate('Acquista il Pacchetto Minuti pi&ugrave; adatto a te e approfitta delle nostre tariffe scontate.') ?>
                            </span>
                            <br>
                            <span class="block-sub-title">
                                <?= $this->translate('Prima di scegliere il tuo preferito assicurati di aver completato la tua registrazione con l\'acquisto del Pacchetto Benvenuto.'); ?>
                            </span>    
                        </div>
                        <br><br>
                        <!-- packages -->
                        <div class="block-data-table clearboth clearfix">
                        <?php
                            foreach ($bonusPackages as $package) {
                                if($package->getType()==="Pacchetto" || $package->getType()==="PacchettoPunti"){
                                    $hour = date("Gi");
                                    $hour = intval($hour);
                                    if($gender=="male" && $package->getCode()=="WOMEN" ){
                                        continue;
                                    }
                                    if ($package->getCode()=="BENVENUTO" && !$this->showWelcomePackage){
                                        continue;
                                    }
                        ?>
                            <div class="bw-f w-1-4 clearfix">
                                <div class="bw-f w-1-2 clearfix">
                                    <img style="width:110px;" src="<?= $this->basePath('images/pacco_regalo.png') ?>" alt="">
                                </div>
                                <div class="bw-f w-1-2 clearfix">
                                    <div class="content-align-center">
                                        <p class=<?= $package->getCode()=="WOMEN" ? 'women-voucher' : '"fa-2x highlight font-weight bold"'; ?> <?= $package->getCode()=="CODE13" ? 'style="color:red"' :''?>><?= strtoupper($this->translate($package->getName())) ?></p>
                                        <span style="font-size: 2.2rem"><?= $package->getMinutes() ?></span>
                                        <span style="font-size: 1.5rem;"><?= $this->translate('min') ?></span>
                                        <?php if($package->getType()==="Pacchetto"){ ?>
                                            <p class="block-sub-title"><?= ($package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end)) ? "GRATUITO" : $this->translate('a ').sprintf("%.0f &euro;", $package->getCost() / 100) ?></p>

                                            <p class="block-sub-title">
                                            <?php
                                            if($package->getMinutes()>0 && !($package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end))) {
                                                $cost = ($package->getCost()/100) / $package->getMinutes();
                                                $cost_round = sprintf("%.3f", $cost);
                                                if(substr($cost_round, -1)==='0'){ // if last char is a '0', then remove
                                                    $cost_round = substr($cost_round,0,strlen($cost_round)-1);
                                                }
                                                if($package->getName()=="ESTATE") {
                                                    $cost_round = "0,22";
                                                }
                                                echo sprintf("%s &euro;/", $cost_round).$this->translate('min');

                                            }
                                            ?>
                                            </p>
                                            <p class="block-sub-title"><?= $this->translate('Validità') ?>
                                                <?php
                                                    // Duration is expressed in 30-days multiplies (ex. 30, 60, 90 etc...)
                                                    $months = floor($package->getDuration() / 30);
                                                    echo ' '.$months.' '.($months > 1 ? $this->translate('mesi') : $this->translate('mese'));
                                                ?>
                                            </p>
                                        <?php }else{?>
                                            <p class="block-sub-title"><?= $this->translate('a') ?> <?= sprintf("%.0f", $package->getCost()) ?></p>
                                            <p class="block-sub-title">
                                            <?php
                                                $cost_round = "0,0";
                                                echo sprintf("%.1f &euro;/", $cost_round).$this->translate('min');
                                            ?>
                                            </p>
                                            <p class="block-sub-title"><?= $this->translate('Validità') ?>
                                                <?php
                                                    // Duration is expressed in days for packet points
                                                    $day = floor($package->getDuration());
                                                    echo ' '.$day.' '.($day > 1 ? $this->translate('giorni') : $this->translate('giorno'));
                                                ?>
                                            </p>
                                        <?php }?>  
                                    </div>
                                </div>
                            </div>
                        <?php
                                }   // enf if
                            }   // end foreach
                        ?>
                        </div>
                        <!-- packages -->

                        <!-- description -->
                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Minuti'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Prezzo'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido dal'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Disponibile fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Acquista/Converti'); ?></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    if($package->getType()==="Pacchetto" || $package->getType()==="PacchettoPunti"){
                                        if($gender=="male" && $package->getCode()=="WOMEN" ){
                                            continue;
                                        }
                                        if ($package->getCode()=="BENVENUTO" && !$this->showWelcomePackage){
                                            continue;
                                        }
                                        $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                        $i++;
                                        $validTo = sprintf($this->translate("per %d gg"), $package->getDuration());
                                        $validFrom = $package->validFromOrToday()->format("d-m-Y");
                                        if($package->getName()=="ESTATE"){
                                            $validTo = "31 agosto 2018";
                                        }
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getMinutes() . (" min.") ?></div>
                                <?php if($package->getType()==="Pacchetto"){ ?>
                                    <div class="block-data-table-td cw-1-7"><?= ($package->getCode()=="WOMEN" && ($nowFree >= $start && $nowFree <= $end)) ? "GRATUITO" : sprintf("%.2f &euro;", $package->getCost() / 100) ?></div>
                                <?php }else{ ?>
                                    <div class="block-data-table-td cw-1-7"><?= sprintf("%.0f &euro;", 0) ?></div>
                                <?php } ?>
                                <div class="block-data-table-td cw-1-7"><?= $validFrom ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $validTo ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getBuyableUntil()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7">
                                    <?php if ($package->getCode()=="WOMEN" && $verifyWomenVoucher>=1) { ?>
                                    <a onclick="verify()">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                    <?php } else { ?>
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->
                            <?php
                                    }   // end if
                                }   // end foreach
                            ?>

                        </div>
                        <!-- table -->
                        
                          </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="block-form bw-f margin-separator"></div>

                    <!-- Promo code section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-4-4">
                                    <div>
                                        <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                                $promoCode = $form->get('promocode')->get('promocode');
                                                echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                                echo $this->formElementErrors($promoCode, ['class' => 'errors']);

                                                echo $this->form()->openTag($form);
                                                ?>
                                    </div>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type="submit" name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->

                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->
    <!-- overlay women voucher -->
    <div id="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden">Chiudi</span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> ATTENZIONE</h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: center; font-weight: 500;">Il voucher &eacute; disponibile per un solo acquisto giornaliero.</p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->
</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }
    .errors li {
        color: red;
    }
    .women-voucher {
        font-size: 1.2em;
        width: 180px;
        color: #43a34c;
        word-wrap:break-word;
        font-weight: 700;
    }
    @media (max-width: 680px) {
        .women-voucher {
            font-size: 1.2em;
            width: auto;
        }
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
    $this->headLink()->appendStylesheet($this->basePath('css/overlay.css'));
?>
<script type="text/javascript">
    
    function verify() {
        overlay = $('#sng-overlay');
          overlay.css("visibility", "visible");


        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        });
    }

</script>