<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
$gender = $this->customer->getGender();
$verify = 1; //$this->verify; verify number of one month trip
?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('promo e pacchetti'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <!-- Promo code section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <?php echo $this->partial('partials/flash-messages.phtml', []); ?>

                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-gift"></i> <?= $this->translate('Codice Promo'); ?></h2>
                        </div>
                        <?= $this->form()->openTag($form); ?>
                            <div class="block-row-field clearfix">
                                <div class="block-field bw-f w-4-4">
                                    <p> <label><?= $this->translate('Inserisci il codice promo'); ?></label>
                                        <?php
                                        $promoCode = $form->get('promocode')->get('promocode');
                                        echo $this->formElement($promoCode->setAttribute('class', 'required'));
                                        echo $this->formElementErrors($promoCode, ['class' => 'errors']);
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <div class="block-wrapper-button content-align-center">
                                <input type="submit" name="" value="<?= $this->translate('Valida'); ?>">
                            </div>
                        <?php echo $this->form()->closeTag(); ?>
                    </div>
                    <!-- promo code section -->

                    <!-- Margin -->
                    <div class="block-form bw-f margin-separator"></div>

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista Pacchetti'); ?></h2>
                        </div>
                        <!-- title -->

                        <!-- Description -->
                        <div class="content-align-center block-title highlight">
                            <?= $this->translate('TIPO CHE SEI, PACCHETTO CHE TROVI') ?>
                        </div>
                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title">
                                <?= $this->translate('Scegli il pacchetto minuti che preferisci e il costo dei tuoi noleggi Share&#39ngo scende fino ad arrivare a 0,22 &euro;/min, la tariffa pi&ugrave; bassa tra tutti gli operatori di servizi di car sharing a flusso libero.<br>Con l\'abbonamento mensile puoi avere una Share&#39ngo tutta per te') ?>
                                <br>
                                <span style="font-size: 16px">
                                    (<a href="package-my-sharengo"><?= $this->translate('clicca qui') ?></a> <?= $this->translate('per ricevere tutte le informazioni necessarie') ?>).
                                </span>
                            </span>
                            <br>
                            <span class="block-sub-title">
                                <b style="color:red"><?= $this->translate('Attenzione: '); ?></b><?= $this->translate('prima di acquistare un pacchetto assicurati di aver pagato la quota di iscrizione'); ?>
                            </span>    
                        </div>
                        <br><br>
                        <!-- packages -->
                        <div class="block-data-table clearboth clearfix">
                        <?php
                            foreach ($bonusPackages as $package) {
                                if($package->getType()==="Pacchetto"){
                                    if( ($gender=="male" || $verify==3) && $package->getCode()=="WOMEN"){
                                        continue;
                                    }
                        ?>
                            <div class="bw-f w-1-4 clearfix">
                                <div class="bw-f w-1-2 clearfix">
                                    <img style="width:110px;" src="<?= $this->basePath('images/pacco_regalo.png') ?>" alt="">
                                </div>
                                <div class="bw-f w-1-2 clearfix">
                                    <div class="content-align-center">
                                        <p class=<?= $package->getCode()=="WOMEN" ? 'women-voucher' : '"fa-2x highlight font-weight bold"'; ?>><?= strtoupper($this->translate($package->getName())) ?></p>
                                            <span style="font-size: 2.2rem"><?= $package->getMinutes() ?></span>
                                            <span style="font-size: 1.5rem;"><?= $this->translate('min') ?></span>
                                            <p class="block-sub-title"><?= $this->translate('a') ?> <?= sprintf("%.0f &euro;", $package->getCost() / 100) ?></p>

                                        <p class="block-sub-title">
                                        <?php
                                        if($package->getMinutes()>0) {
                                            $cost = ($package->getCost()/100) / $package->getMinutes();
                                            $cost_round = sprintf("%.3f", $cost);
                                            if(substr($cost_round, -1)==='0'){ // if last char is a '0', then remove
                                                $cost_round = substr($cost_round,0,strlen($cost_round)-1);
                                            }
                                            echo sprintf("%s &euro;/", $cost_round).$this->translate('min');
                                        }
                                        ?>
                                        </p>
                                        <p class="block-sub-title"><?= $this->translate('Validità') ?>
                                            <?php
                                                if( $package->getCode()=="WOMEN"){
                                                    echo 'una notte';
                                                } else {
                                                    // Duration is expressed in 30-days multiplies (ex. 30, 60, 90 etc...)
                                                    $months = floor($package->getDuration() / 30);
                                                    echo ' '.$months.' '.($months > 1 ? $this->translate('mesi') : $this->translate('mese'));
                                                }
                                            ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php
                                }   // enf if
                            }   // end foreach
                        ?>
                        </div>
                        <!-- packages -->

                        <!-- description -->
                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Minuti'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Prezzo'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido dal'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Disponibile fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Acquista'); ?></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    if($package->getType()==="Pacchetto"){
                                        if( ($gender=="male" || $verify==3) && $package->getCode()=="WOMEN"){
                                            continue;
                                        }

                                        $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                        $i++;
                                        $validTo = sprintf($this->translate("per %d gg"), $package->getDuration());
                                        $validFrom = $package->validFromOrToday()->format("d-m-Y");
                                        if ($package->getCode()=="WOMEN") {
                                            $now = date("Y-m-d");
                                            $validFrom = date_create($now.' 01:00:00');
                                            //$validTo = date_create($now.' 06:00:00');
                                            $validTo = "per la notte";
                                            $hour = date("G");

                                                if ( intval($hour) >= 5 ) {
                                                  //add 1 day to now in case of purchase after the 5am
                                                    $validFrom = date_add($validFrom, date_interval_create_from_date_string('1 days'));
                                                    $validTo = date_add($validTo, date_interval_create_from_date_string('1 days'));
                                                }
                                            
                                            $validFrom = $validFrom->format("d-m-Y");
                                            //$validTo = $validTo->format("d-m-Y H:i");
                                            $validTo = "per la notte";
                                        }
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getMinutes() . (" min.") ?></div>
                                <div class="block-data-table-td cw-1-7"><?= sprintf("%.2f &euro;", $package->getCost() / 100) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $validFrom ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $validTo ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getBuyableUntil()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7">
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->
                            <?php
                                    }   // end if
                                }   // end foreach
                            ?>

                        </div>
                        <!-- table -->

                    </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="bw-f w-1-3 last clearfix"></div>
                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }
    .errors li {
        color: red;
    }
    .women-voucher {
        font-size: 1.2em;
        width: 180px;
        color: #43a34c;
        word-wrap:break-word;
        font-weight: 700;
    }
    @media (max-width: 680px) {
        .women-voucher {
            font-size: 1.2em;
            width: auto;
        }
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
?>
