<?php
$bonusPackages = $this->bonusPackages;
?>

<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>
        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('gift card'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <!-- Promo code section -->
                    <!-- Margin -->
                    <div class="block-form bw-f margin-separator"></div>

                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><i class="fa fa-shopping-cart"></i> <?= $this->translate('Acquista una Gift Card'); ?></h2>
                        </div>
                        <!-- title -->

                        <!-- Description -->
                        <div class="content-align-center block-title highlight">
                            <?= $this->translate('REGALA LA MOBILIT&Agrave; SOSTENIBILE CON GIFT CARD') ?>
                        </div>
                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title" >
                                <?= $this->translate('Ti stai divertendo un mondo con Share&#39;ngo? Condividi il piacere della mobilit&agrave; elettrica e condivisa, regalando una Gift Card ad un amico, un parente o un collega.') ?><br>
                                <?= $this->translate('La Gift Card comprende l&#39;iscrizione a Share&#39;ngo con il pacchetto minuti bonus che scegli tu.') ?><br>
                                <div style='font-size:20px; color:#ff0000; margin-top: 6px; margin-bottom: 6px'>
                                    <?= $this->translate('Riceverai la Gift Card via email il giorno dopo l&#39;acquisto.') ?><br>
                                </div>
                                <div style='font-size:20px'>
                                    <?= $this->translate('(chi riceve la Gift Card potr&agrave; attivare il suo account con soli 50 cent)' )?>
                                </div>
                            </span>
                        </div>
                        <br><br>
                        <!-- packages -->
                        <div class="block-data-table clearboth clearfix">
                        <?php
                            foreach ($bonusPackages as $package) {
                                 if($package->getType()==="PacchettoRegalo"){
                        ?>
                            <div class="bw-f w-1-3 clearfix" style="margin-right: 0px;">
                                <div class="bw-f w-1-2 clearfix" style="margin-right: 5px;">
                                    <img style="width:122px;" src="<?= $this->basePath('images/gift-packages.png') ?>" alt="">
                                </div>
                                <div class="bw-f w-1-2 clearfix">
                                    <div class="content-align-center">
                                        <p class="fa-2x highlight font-weight bold"><?= strtoupper($this->translate($package->getName())) ?></p>
                                        <p class="block-sub-title" style='font-size:16px'><?= $this->translate('Iscrizione +')?><br><?=  substr($package->getCode(), 4,5)?> <?= $this->translate('min') ?> <?= $this->translate('a') ?> <?= sprintf("%.0f &euro;", $package->getCost() / 100) ?></p>
                                        <p class="block-sub-title">
                                        <?php
                                        if($package->getMinutes()>0) { echo sprintf("%.2f &euro;", ($package->getCost() / 100) / $package->getMinutes()).$this->translate('min'); }
                                        ?>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        <?php
                                 }  // end if
                            }   // end foreach
                        ?>
                        </div>
                        <!-- packages -->

                        <!-- description -->
                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix">
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Minuti'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Prezzo'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido dal'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Valido fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Disponibile fino'); ?></div>
                                <div class="block-data-table-th cw-1-7"><?= $this->translate('Acquista'); ?></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    if($package->getType()==="PacchettoRegalo"){
                                        $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                        $i++;
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>">
                                <div class="block-data-table-td cw-1-7"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= substr($package->getCode(), 4,5) . (" min.") ?></div>
                                <div class="block-data-table-td cw-1-7"><?= sprintf("%.2f &euro;", $package->getCost() / 100) ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->validFromOrToday()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7"><?= sprintf($this->translate("per %d gg"), $package->getDuration()); ?></div>
                                <div class="block-data-table-td cw-1-7"><?= $package->getBuyableUntil()->format("d-m-Y") ?></div>
                                <div class="block-data-table-td cw-1-7">
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none;">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->

                            <?php
                                    }   // end if
                                }   // end foreach
                            ?>

                        </div>
                        <!-- table -->

                    </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                    <div class="bw-f w-1-3 last clearfix"></div>
                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }

    .errors li {
        color: red;
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
?>
