<?php
$form = $this->promoCodeForm->prepare();
$bonusPackages = $this->bonusPackages;
$gender = $this->customer->getGender();
$verifyWomenVoucher = $this->verifyWomenVoucher; //verify number of one month trip
$mobile = $this->mobile;

?>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->
        <?php echo $this->navigation('navigation')->menu()->setPartial('partials/left-menu-user-area'); ?>

        <!-- module-column-app sx -->
        
        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title"><?= $this->translate('Canoni e Tariffe'); ?></h1>
                <?php echo $this->partial('partials/welcome-user-area'); ?>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-manage-driver-license padding-top">
                    <?php
                        if (count($bonusPackages) > 0) {
                    ?>

                    <!-- Bonus packages section -->
                    <div class="block-form bw-f w-3-3  clearfix">

                        <!-- Title MYSHARENGO -->
                        <div class="block-form-section content-align-center margin-bottom">
                            <h2><?= $this->translate('Prenota ora il tuo Abbonamento'); ?></h2>
                        </div>
                        <!-- title MYSHARENGO-->
                        <div class="block-field block-avatar-app content-align-center">
                            <span class="block-sub-title">
                                <?= $this->translate('Con la nuova mobilità di MYSHARENGO puoi disporre di una Sharengo tutta per te  per il tempo che ti serve,') ?>
                            </span>
                            <br>
                            <span class="block-sub-title">
                                <?= $this->translate('scegli  tra le opzioni di tempo e di tariffe quella più adatta a te.'); ?>
                            </span>    
                        </div>
                        <br><br>
                        <!-- packages -->
                        <div class="block-data-table clearboth clearfix">
                        <?php
                            foreach ($bonusPackages as $package) {
                                if($package->getType()==="Pacchetto" || $package->getType()==="PacchettoPunti"){
                                    $hour = date("Gi");
                                    $hour = intval($hour);
                                    if($gender=="male" && $package->getCode()=="WOMEN" ){
                                        continue;
                                    }
                                    if ($package->getCode()=="BENVENUTO" && !$this->showWelcomePackage){
                                        continue;
                                    }
                        ?>
                            <div class="bw-f w-1-4 clearfix">
                                <div class="bw-f w-1-2 clearfix">
                                    <img style="width:110px;" src="<?= $this->basePath('images/pacco_regalo.png') ?>" alt="">
                                </div>
                                <div class="bw-f w-1-2 clearfix">
                                    <div class="content-align-center">
                                        <p class=<?= $package->getCode()=="WOMEN" ? 'women-voucher' : '"fa-2x highlight font-weight bold"'; ?>
                                            <?= $package->getCode()=="CODE13" ? 'style="color:red"' :''?>><?= strtoupper($this->translate($package->getName())) ?></p>
                                        
                                        <!-- title -->
                                        <span style="font-size: 2.2rem">
                                            
                                            <?php
                                                    // Duration is expressed in 30-days multiplies (ex. 30, 60, 90 etc...)
                                                    $months = floor($package->getDuration() / 30);
                                                    if ($months>0) {
                                                        echo ' '.$months.' '.($months > 1 ? $this->translate('mesi') : $this->translate('mese'));
                                                    } else {
                                                        echo ' '.$package->getDuration().' '.($package->getDuration() > 1 ? $this->translate('giorni') : $this->translate('giorno'));
                                                    }

                                                ?>
                                            
                                        </span>
                                        
                                            <p class="block-sub-title" style="font-size: 1.5rem"><?= sprintf("%s %.0f &euro;", $this->translate('a'),$package->getCost() / 100) ?></p>

                                            <p class="block-sub-title" style="font-size: 1.2rem; margin-top: 0.5rem">
                                            <?php
                                            if($package->getDuration()>0) {
                                                $cost = ($package->getCost()/100) / 30; //$package->getDuration();
                                                $cost_round = sprintf("%.1f", $cost);
                                                if(substr($cost_round, -1)==='0'){ // if last char is a '0', then remove
                                                    $cost_round = substr($cost_round,0,strlen($cost_round)-2);
                                                }

                                                echo sprintf("%s &euro;/", $cost_round).$this->translate('giorno');

                                            }
                                            ?>
                                            </p>
                                            
                                          
                                    </div>
                                </div>
                            </div>
                        <?php
                                }   // enf if
                            }   // end foreach
                        ?>
                        </div>
                        <!-- packages -->

                        <!-- description -->
                        <!-- Table -->
                        <div class="block-data-table clearboth clearfix margin-top-custom" style="box-sizing: border-box;">
                            <!-- Table header -->
                            <div class="block-data-table-row clearfix" style="text-align: center;">
                                <div class="block-data-table-th cw-1-5"><?= $this->translate('Nome'); ?></div>
                                <div class="block-data-table-th cw-1-5"><?= $this->translate('Mesi'); ?></div>
                                <div class="block-data-table-th cw-1-5"><?= $this->translate('Prezzo (IVA Inclusa)'); ?></div>
                                <div class="block-data-table-th cw-1-5"><?= $this->translate('Prezzo al giorno (IVA Inclusa)'); ?></div>
                                <div class="block-data-table-th cw-1-5"><?= $this->translate('Prenota'); ?></div>
                            </div>
                            <!-- table header -->
                            <?php
                                $i = 1;
                                foreach ($bonusPackages as $package) {
                                    if($package->getType()==="Pacchetto" || $package->getType()==="PacchettoPunti"){
                                        if($gender=="male" && $package->getCode()=="WOMEN" ){
                                            continue;
                                        }
                                        if ($package->getCode()=="BENVENUTO" && !$this->showWelcomePackage){
                                            continue;
                                        }
                                        $oddOrEven = ($i % 2) ? 'even' : 'odd';
                                        $i++;
                                        $validTo = sprintf($this->translate("per %d gg"), $package->getDuration());
                                        $validFrom = $package->validFromOrToday()->format("d-m-Y");
                            ?>
                            <!-- Table body -->
                            <div class="block-data-table-row clearfix <?= $oddOrEven ?>" style="text-align: center;">
                                <div class="block-data-table-td cw-1-5"><?= $this->translate($package->getName()) ?></div>
                                <div class="block-data-table-td cw-1-5">
                                    <?php
                                        
                                        // Duration is expressed in 30-days multiplies (ex. 30, 60, 90 etc...)
                                        $months = floor($package->getDuration() / 30);
                                        if ($months>0) {
                                            echo ' '.$months.' '.($months > 1 ? $this->translate('mesi') : $this->translate('mese'));
                                        } else {
                                            echo ' '.$package->getDuration().' '.($package->getDuration() > 1 ? $this->translate('giorni') : $this->translate('giorno'));
                                        }
                                    ?>
                                </div>
                                <div class="block-data-table-td cw-1-5"><?= sprintf("%.0f &euro;", $package->getCost() / 100) ?></div>
                                <div class="block-data-table-td cw-1-5">
                                            <?php
                                            if($package->getDuration()>0) {
                                                $cost = ($package->getCost()/100) / 30; //$package->getDuration();
                                                $cost_round = sprintf("%.1f", $cost);
                                                if(substr($cost_round, -1)==='0'){ // if last char is a '0', then remove
                                                    $cost_round = substr($cost_round,0,strlen($cost_round)-2);
                                                }

                                                echo sprintf("%s &euro;/", $cost_round).$this->translate('giorno');

                                            }
                                            ?>
                                </div>
                                <div class="block-data-table-td cw-1-5">
                                    <a href="<?= $this->url('area-utente/bonus-package', ['id' => $package->getId()], ['force_canonical' => true]) ?>" class="buyPackage">
                                        <i class="fa fa-cart-plus"></i>
                                    </a>
                                </div>
                            </div>
                            <div class="block-data-table-row data-info clearfix" style="display: table-row; border: none; text-align: justify">
                                <div class="block-data-table-td cw-6-6"><?= $package->getNotes() ?></div>
                            </div>
                            <!-- table body -->
                            <?php
                                    }   // end if
                                }   // end foreach
                            ?>

                            <div class="block-form bw-f margin-separator"></div>

                            <!-- Promo code section -->
                            <div class="block-form bw-f w-3-3  clearfix">

                                <?php echo $this->partial('partials/flash-messages.phtml', []); ?>
                            
                            </div>
                            
                        </div>
                        <!-- table -->
                        
                          </div>
                    <!-- bonus packages section -->

                    <?php
                        }
                    ?>

                </div>
            </div>

        </div>
        <!-- module-column-app dx -->
    </div>
    <!-- module-wrapper-app -->
    <!-- overlay women voucher -->
    <div id="sng-overlay" class="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden">Chiudi</span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> ATTENZIONE</h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: center; font-weight: 500;">Il voucher &eacute; disponibile per un solo acquisto giornaliero.</p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->
</div>
<!-- main -->

<?php
$this->headStyle()->captureStart() ?>
    .errors {
        list-style-type: none;
    }
    .errors li {
        color: red;
    }
    .women-voucher {
        font-size: 1.2em;
        width: 180px;
        color: #43a34c;
        word-wrap:break-word;
        font-weight: 700;
    }
    @media (max-width: 680px) {
        .women-voucher {
            font-size: 1.2em;
            width: auto;
        }
    }
<?php $this->headStyle()->captureEnd() ?>

<!-- JavaScript -->
<?php
    $this->inlineScript()->appendFile($this->basePath('js/magnific-popup.min.js'));
    $this->inlineScript()->appendFile($this->basePath('js/bonus-packages.js'));
    $this->headLink()->appendStylesheet($this->basePath('css/magnific-popup.css'), 'screen');
    $this->headLink()->appendStylesheet($this->basePath('css/overlay.css'));
?>
<script type="text/javascript">
    
    function verify() {
        overlay = $('#sng-overlay');
          overlay.css("visibility", "visible");


        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        });
    }

</script>