<?php
    $invoiceContent = $this->invoiceContent;
    // Customer data
    $name = $invoiceContent['name']. ' ' . $invoiceContent['surname'];
    $mail = $invoiceContent['email'];
    $cardN = $invoiceContent['card'];
    $address = $invoiceContent['address'];
    $cf = $invoiceContent['cf'];
    $piva = $invoiceContent['piva'];
    $ccard = 'xxxx xxxx xxxx xxxx';
    // Invoice data
    $docN = $invoiceContent['invoice_number'];
    $invoiceDate = substr($invoiceContent['emitted_ts']['date'], 0, 19);
    $fullAmount = (float)$invoiceContent['amount'] / 100;
    $partialAmount = number_format($fullAmount * 50 / 61, 2, '.', '');
    $iva = number_format($partialAmount * 22 / 100, 2, '.', '');
    if ($partialAmount + $iva != $fullAmount) {
        $partialAmount = $fullAmount - $iva;
    }
    $amount = number_format($fullAmount, 2, '.', '');
?>

<!-- Main container -->
<div id="container">

<?php
    for ($i = 1; $i <= 2; $i++) {
?>

    <!-- Page container -->
    <div class="page-container">

        <!-- Header -->
        <div class="header font">
            <h4>Share`n Go s.r.l.</h4>
            <p class="header-text">
                CS Milano SRL<br>
                Sede legale<br>
                Via dei Pelaghi, 162 – 57121 Livorno (LI)<br>
                P.IVA: 01808470494<br>
                Sede operativa<br>
                Via Casati Felice 1/A – 20124 Milano (MI)<br>
                Tel: 0586.1975772<br>
                Email: servizioclienti@sharengo.eu
            </p>
        </div>
        <!-- header -->

        <!-- Logo -->
        <img class="logo" src="<?php echo $this->serverUrl()?>/images/sharengo_logo_pdf.png" alt="">

        <!-- Table aggregate -->
        <div>
            <!-- Invoice table header -->
            <h3 class="table-header invoice-header font">Dati Fattura</h3>

            <!-- Top line -->
            <div class="line"></div>

            <!-- Invoice table -->
            <table class="table table1 font">
                <tr>
                    <td class="table1-031e">Cliente:</td>
                    <td class="table1-031e"><?= $name ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">Doc N°:</td>
                    <td class="table1-031e"><?= $docN ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">Data Fattura:</td>
                    <td class="table1-031e"><?= $invoiceDate ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">Card:</td>
                    <td class="table1-031e"><?= $cardN ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">e-mail:</td>
                    <td class="table1-031e"><?= $mail ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">Indirizzo:</td>
                    <td class="table1-031e"><?= $address ?></td>
                </tr>
                <tr>
                    <td class="table1-031e">Codice fiscale:</td>
                    <td class="table1-031e"><?= $cf ?></td>
                </tr>
                <?php
                    if ($piva != null && $piva != '') {
                ?>
                <tr>
                    <td class="table1-031e">Partita IVA:</td>
                    <td class="table1-031e"><?= $piva ?></td>
                </tr>
                <?php
                    }
                ?>
            </table>
            <!-- invoice table -->

        </div>
        <!-- table aggregate -->

        <!-- Content -->
        <div id="content" class="content">

<?php
    if ($i == 1) {
?>

            <!-- Message -->
            <div class="message font">
                <p><br>Gentile <span class="name"><?= $name ?></span></p>
                <p>La ringraziamo per aver usufruito dei nostri servizi.<br>
                    Nelle pagine successive troverà un elenco dettagliato dei viaggi di cui Lei ha usufruito.</p>
                <p>L'importo totale della fattura da saldare è complessivamente di<br>EUR <?= $amount ?></p>
                <p>Twistcar provvederà ad addebitare la Sua carta di credito<br>n° <?= $ccard ?> per il suddetto importo.</p>
                <p>Per eventuali chiarimenti può contattarci al n. 02 49688617 il mercoledi dalle 9 alle 13.</p>
                <p>Cordiali saluti</p>
            </div>
            <!-- message -->

<?php
    } else {
?>

        <!-- Transactions table -->
        <div>
            <table class="table table2 font">
                <tr>
                    <th class="table2-031e">Descrizione</th>
                </tr>
                <tr>
                    <td class="table2-031e">Fattura per il primo pagamento utente.</td>
                </tr>
            </table>
        </div>
        <!-- transactions table -->


        <!-- Summary table header -->
        <h3 class=" table-header summary-header font">Importo</h3>

        <!-- Bottom line -->
        <div class="line"></div>

        <!-- Summary table -->
        <table class="table table1 font">
            <tr>
                <td class="table1-031e">Imponibile</td>
                <td class="table1-031e"><?= $partialAmount ?></td>
            </tr>
            <tr>
                <td class="table1-031e">IVA 22%</td>
                <td class="table1-031e"><?= $iva ?></td>
            </tr>
            <tr>
                <td class="table1-031e">Totale</td>
                <td class="table1-031e"><?= $amount ?></td>
            </tr>
        </table>
        <!-- summary table -->

        <!-- Bottom message -->
        <p class="message font">
            Potrà trovare tutte le sue fatture nell'Area Riservata insieme alle altre informazioni del suo profilo.
        </p>
<?php
    }
?>

        </div>
        <!-- content -->

        <!-- Page end -->
        <div class="page-break"></div>

    </div>
    <!-- page container -->

<?php
    }
?>

</div>
<!-- main container -->
