<?php echo $this->doctype(); ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Share\'NGo - the new mobility'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('description', '')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300')
            ->appendStylesheet($this->basePath('css/styles.css'), 'screen')
            ->appendStylesheet($this->basePath('css/addons.css'), 'screen')
            /*->appendStylesheet([
                'rel' => 'stylesheet/less',
                'href' => $this->basePath('less/styles.less'),
                'type' => 'text/css'],
            'screen')*/
            ->appendStylesheet($this->basePath('css/print.css'), 'print')
            ->appendStylesheet($this->basePath('css/ie8.css'), 'screen', 'lte IE 8')
            ->appendStylesheet('http://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css')
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependScript('window.jQuery || document.write(\'<script src="js/vendor/jquery-1.8.2.min.js"><\/script>\')')
            ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js')
            ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js')
            ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/nwmatcher/1.2.5/nwmatcher.min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile($this->basePath('js/jquery.backgroundSize.js'), 'text/javascript', ['conditional' => 'lte IE 8'])
            ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.0/less.min.js')
        ; ?>

    </head>
    <body>
        <!--[IE 9]>
            <p class="chromeframe"><?= $this->translate('Stai usando un browser <strong>non supportato</strong>. Per favore <a href="http://browsehappy.com/">aggiorna il tuo browser</a> o <a href="http://www.google.com/chromeframe/?redirect=true">attiva Google Chrome Frame</a> per far diventare pi&ugrave; potente il tuo browser.'); ?></p>
        <![endif]-->

        <!-- outer -->
        <div id="outer">
            <!-- header -->
            <header id="header" class="emotional-header clearfix">

                <!-- show-nav-for-iphone -->
                <button type="button" class="show-nav-for-iphone" data-toggle="collapse" data-target="#nav">
                    <i class="fa fa-align-justify"></i>
                </button><!-- show-nav-for-iphone -->

                <!-- site-link -->
                <a href="<?= $this->url('home'); ?>" id="site-link">
                    <h2><?= $this->translate('Share\'NGo - the new mobility'); ?></h2>
                </a><!-- site-link -->

                <!-- module-wrapper-menu -->
                <div class="module-wrapper-menu clearfix">

                    <!-- block-menu-languages -->
                    <div class="block-languages block-menu">
                        <ul>
                            <?php /*<li>
                                <a class="js-show-element">
                                    <?= $this->translate('Italiano'); ?>
                                    <i class="fa fa-caret-down"></i>
                                </a>
                                <ul class="js-collapse-box block-available-languages hidden">
                                    <li><a href=""><?= $this->translate('Inglese'); ?></a></li>
                                    <li><a href=""><?= $this->translate('Francese'); ?></a></li>
                                    <li><a href=""><?= $this->translate('Tedesco'); ?></a></li>
                                </ul>
                            </li> */?>
                            <li>
                                <a class="js-show-element">
                                    <?= $this->translate('MILANO'); ?>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- block-menu-languages -->

                    <!-- nav-collapse -->
                    <div id="nav" class="nav-collapse collapse">

                        <!-- nav -->
                        <nav id="menu" class="block-menu block-navigation-menu">
                            <h1 class="hidden"><?= $this->translate('Navigazione principale'); ?></h1>
                            <ul>
                                <li><a href="<?= $this->url('home') ?>" class="<?= $this->currentRoute() == 'home' ? 'active' : ''?>"><?= $this->translate('Car sharing'); ?></a></li>
                                <li><a href="<?= $this->url('cosae') ?>" class="<?= $this->currentRoute() == 'cosae' ? 'active' : ''?>"><?= $this->translate('Cosa &egrave; Sharengo?'); ?></a></li>
                                <li><a href="<?= $this->url('quantocosta') ?>" class="<?= $this->currentRoute() == 'quantocosta' ? 'active' : ''?>"><?= $this->translate('Quanto costa'); ?></a></li>
                                <li><a href="<?= $this->url('comefunziona') ?>" class="<?= $this->currentRoute() == 'comefunziona' ? 'active' : ''?>"><?= $this->translate('Come funziona'); ?></a></li>
                                <li><a href="<?= $this->url('faq') ?>" class="<?= $this->currentRoute() == 'faq' ? 'active' : ''?>"><?= $this->translate('Faq'); ?></a></li>
                                <li><a href="<?= $this->url('contatti') ?>" class="<?= $this->currentRoute() == 'contatti' ? 'active' : ''?>"><?= $this->translate('Contatti'); ?></a></li>
                            </ul>
                        </nav>
                        <!-- nav -->

                    </div>
                    <!-- nav-collapse -->

                    <!-- block-user-action -->
                    <div class="block-user-action block-menu">
                        <ul>
                            <?php /*<li><a href="<?= $this->url('login') ?>"><i class="fa fa-user"></i><?= $this->translate('Login'); ?></a></li>*/?>
                            <li><a href="<?= $this->url('signup') ?>"><i class="fa fa-user-plus"></i><?= $this->translate('Registrati'); ?></a></li>
                        </ul>
                    </div>
                    <!-- block-menu-languages -->

                </div>
                <!-- module-wrapper-menu -->

            </header>
            <!-- header -->

            <?php echo $this->content; ?>
        </div>
        <!-- outer -->

        <!-- footer -->
        <footer id="footer">
            <!-- content -->
            <div class="content clearfix">

                <!-- block-footer -->
                <div class="block-footer bw-f w-1-3">

                    <p>
                        <?= $this->translate('<span class="font-weight bold">Share \'N Go</span> <br>è un servizio di C.S. Milano s.r.l.'); ?><br>
                        <?= $this->translate('<span class="font-weight semibold">Sede Legale:</span><br>Via Casati Felice 1/A, 20124 - Milano (MI)<br>Codice Fiscale e Partita IVA n. 01808470494<br>Numero REA MI - 2063182<br>Telefono: <a href="tel:05020091"> 050 20091</a>');
                        ?><br>
                        <?= $this->translate('<span class="font-weight semibold">Sede operativa:</span><br>    Piazzale D’Ascanio C., 1 - 56121 Pisa (PI)');
                        ?>
                    </p>

                </div>
                <!-- block-footer -->

                <!-- block-footer -->
                <div class="block-footer bw-f w-1-3">

                    <ul class="simple-list">
                        <li><a href="<?= $this->url('cookies') ?>"><?= $this->translate('Cookies'); ?></a></li>
                        <li><a href="<?= $this->url('notelegali') ?>"><?= $this->translate('Note legali'); ?></a></li>
                        <li><a href="<?= $this->url('privacy') ?>"><?= $this->translate('Politiche di privacy'); ?></a></li>
                        <li><a href="<?= $this->url('notelegali') ?>"><?= $this->translate('Avvertenze Legali'); ?></a></li>
                        <li><a href="<?= $this->url('contatti') ?>"><?= $this->translate('Contatti'); ?></a></li>
                        <li><a href="<?= $this->url('faq') ?>"><?= $this->translate('Faq'); ?></a></li>
                    </ul>

                </div>
                <!-- block-footer -->

                <!-- block-footer -->
                <div class="block-footer last bw-f w-1-3">

                    <ul class="simple-list">
                        <li><a href="<?= $this->url('callcenter') ?>"><?= $this->translate('Call center'); ?></a></li>
                        <li><a href="<?= $this->url('callcenter') ?>"><?= $this->translate('Servizi clienti'); ?></a></li>
                    </ul>

                </div>
                <!-- block-footer -->

                <div class="badge-green-number">
                    <h2 class="block-title"><i class="fa fa-phone-square"></i> <?= $this->translate('Numero verde'); ?></h2>
                    <a href="tel:800900930">800 900 930</a>
                </div>

            </div>
            <!-- content -->
        </footer>
        <!-- footer -->

        <?php
            $this->inlineScript()
                ->appendFile($this->basePath('js/respond.min.js'))
                ->appendFile($this->basePath('js/bootstrap.min.js'))
                ->appendFile('http://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.min.js')
                ->appendFile($this->basePath('js/slick-script.js'))
                ->appendFile($this->basePath('js/main.js'));
            echo $this->inlineScript()
        ?>
    </body>
</html>
