<?php echo $this->doctype(); ?>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sharengo - Fattura')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('description', '')
                                    ->appendName('author', 'MvLabs.it')?>

         <!-- CSS
          ================================================== -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->serverUrl() . '/styles/css/report.css');

        ?>

	</head>
	<body>

	<?php echo $this->content; ?>

	<script src="https://code.jquery.com/jquery.js"></script>
    <?php
        echo $this->headScript();
        echo $this->inlineScript();
        echo $this->headStyle() ;
    ?>
	</body>

</html>
