<?php echo $this->doctype(); ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Share\'NGo - the new mobility'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('description', '')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/x-icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,700,600,300')
            ->appendStylesheet($this->basePath('css/styles2.css?ver=0.1'), 'screen')
            ->appendStylesheet($this->basePath('css/addons.css?ver=0.1'), 'screen')
            ->appendStylesheet($this->basePath('css/core.css?ver=4.6.2'), 'screen') // da sostituire con il link al rokivo css
            ->appendStylesheet($this->basePath('css/application.css?ver=4.6.2'), 'screen') // da sostituire rokivo
            ->appendStylesheet($this->basePath('css/print.css'), 'print')
            ->appendStylesheet($this->basePath('css/ie8.css'), 'screen', 'lte IE 8')
            ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css')
        ?>

        <!-- Scripts -->
        <?php $this->headScript()
            ->prependScript('window.jQuery || document.write(\'<script src="js/vendor/jquery-1.8.2.min.js"><\/script>\')')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js')
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/nwmatcher/1.2.5/nwmatcher.min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile($this->basePath('js/jquery.backgroundSize.js'), 'text/javascript', ['conditional' => 'lte IE 8'])
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js')

            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.0/less.min.js')
            ->appendFile($this->basePath('js/jquery.cookiesdirective.js'));

        $this->headScript()->setAllowArbitraryAttributes(true);

            // Google Analytics section
            if ($this->config('googleAnalytics', 'key')) {
                echo '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-63160906-2"></script>';
                echo "<script>
                          window.dataLayer = window.dataLayer || [];
                          function gtag(){dataLayer.push(arguments);}
                          gtag('js', new Date());
                        
                          gtag('config', '".$this->config('googleAnalytics', 'key')."');
                          gtag('config', 'AW-953520877');
                        </script>";
            }
            //Facebook Pixel Code
            echo '<script>
                    !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                    n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
                    n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;
                    t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
                    document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');
                    
                    fbq(\'init\', \'423565347840059\');
                    fbq(\'track\', "PageView");</script>
                    <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=423565347840059&ev=PageView&noscript=1"/></noscript>';
            //End Facebook Pixel Code
            echo $this->headScript();
            echo $this->headStyle();
            echo $this->placeholder('google-track-adwords');
            echo $this->placeholder('google-analytics');
            echo $this->partial('partials/translations.phtml');
        ?>
    </head>
<body <?= $this->isUserArea($this->currentRoute()) ? 'class="app"' : ''; ?>>
<?php
    echo $this->placeholder('facebook-pixel');


    if ($this->serverInstanceId!=="") {
        echo $this->partial("partials/header/main_head_".$this->serverInstanceId.".phtml");
    } else {
        echo $this->partial("partials/header/main_head.phtml");
    }
?>
<!-- outer -->
        <div id="outer">
            <?= $this->availableFleets(); ?>
            <?php echo $this->content; ?>
        </div>
<!-- outer -->
<?php
    $privacyLink = "http://site.sharengo.it/privacy/"; // exception to the rule: take the page from the wordpress

    if ($this->serverInstanceId!=="") {
        echo $this->partial("partials/footer/main_foot_".$this->serverInstanceId.".phtml");
        if($this->serverInstanceId=="nl_NL") {
            $privacyLink = $this->basePath("pdf/nl/privacy.pdf"); // exception to the rule: take the page from the wordpress
        } else if($this->serverInstanceId=="sl_SI") {
           $privacyLink = $this->basePath("pdf/si/privacy.pdf");
        } else if($this->serverInstanceId=="sk_SK") {
           $privacyLink = $this->basePath("pdf/sk/privacy.pdf");
        }
    } else {
        echo $this->partial("partials/footer/main_foot.phtml");
    }
?>
		<?php
        if($this->isUserArea($this->currentRoute())) {
            echo " <style> .block-navigation-menu ul { text-align:center !important; } .block-navigation-menu {	visibility: hidden;}</style>";
        }

            $cookieMessage = $this->translate('I cookie ci aiutano a fornire i nostri servizi. Utilizzando tali servizi, accetti l\'utilizzo dei cookie da parte nostra. Per maggiori dettagli si prega di cliccare');

            $this->inlineScript()
                ->appendFile($this->basePath('js/plugins-min.js?ver=4.6.1'))
                ->appendFile($this->basePath('js/main-min.js?ver=4.6.1'))
                ->appendFile($this->basePath('js/respond.min.js'))
                ->appendFile($this->basePath('js/bootstrap.min.js'))
                ->appendFile('//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.min.js')
                ->appendFile($this->basePath('js/slick-script.js'))
                ->appendFile($this->basePath('js/main.js'))
                ->appendFile($this->basePath('js/js.cookie.js'))
                ->appendScript('
                     // Using $(document).ready never hurts
                    $(document).ready(function(){

                        // Cookie setting script wrapper
                        var cookieScripts = function () {
                            // Loading external javascript file
                            $.cookiesDirective.loadScript({
                                uri:"external.js",
                                appendTo: "eantics"
                            });
                        }

                        $.cookiesDirective({
                            privacyPolicyUri: "'.$privacyLink.'",
                            explicitConsent: false,
                            position : "bottom",
                            duration: 999999,
                            message: "'.$cookieMessage.'",
                            scriptWrapper: cookieScripts,
                            backgroundColor: "#000000",
                            linkColor: "#ffffff"
                        });
                    });
                ');
            echo $this->inlineScript()
        ?>
    </body>
</html>
