<?php echo $this->doctype(); ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Share\'NGo - the new mobility'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()
            ->appendName('description', '')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/x-icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,700,600,300')
            ->appendStylesheet($this->basePath('css/styles2.css'), 'screen')
            ->appendStylesheet($this->basePath('css/addons.css'), 'screen')
            //->appendStylesheet($this->basePath('css/core.css?ver=4.6.1'), 'screen') // da sostituire con il link al rokivo css
            //->appendStylesheet($this->basePath('css/application.css?ver=4.6.1'), 'screen') // da sostituire rokivo
            ->appendStylesheet($this->basePath('css/print.css'), 'print')
            ->appendStylesheet($this->basePath('css/ie8.css'), 'screen', 'lte IE 8')
            ->appendStylesheet('//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.css')
        ?>

        <!-- Scripts -->
        <?php $this->headScript()
            ->prependScript('window.jQuery || document.write(\'<script src="js/vendor/jquery-1.8.2.min.js"><\/script>\')')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.2.1/jquery-migrate.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.0/jquery.min.js')
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/nwmatcher/1.2.5/nwmatcher.min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/selectivizr/1.0.2/selectivizr-min.js', 'text/javascript', ['conditional' => 'lt IE 9'])
            ->appendFile($this->basePath('js/jquery.backgroundSize.js'), 'text/javascript', ['conditional' => 'lte IE 8'])
            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js')

            ->appendFile('//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.0/less.min.js')
            ->appendFile($this->basePath('js/jquery.cookiesdirective.js'));

            if ($this->config('googleAnalytics', 'key')) {
                $this->headScript()->appendScript(
                    "(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                    ga('create', '".$this->config('googleAnalytics', 'key')."', 'auto');
                    ga('send', 'pageview');"
                );
            }

            echo $this->headScript();
            echo $this->headStyle();
            echo $this->placeholder('google-track-adwords');
            echo $this->placeholder('facebook-pixel');
        ?>
        <style>
            .block-languages {
                visibility:hidden;
            }
            body>#outer {
                height: 100%;
                min-height: 100%;
                padding-top: 0;
            }
            .module-car-map.small-height #map_wrapper {
                height: 100%;
            }
            #map_canvas {
                width: 100%;
                height: 100%;
            }
            .module-car-map.small-height {
                height: 100%;
            }

            .no-js #loader { display: none;  }
            .js #loader { display: block; position: absolute; left: 100px; top: 0; }
            .loading_img {
                    position: fixed;
                    left: 0px;
                    top: 0px;
                    width: 100%;
                    height: 100%;
                    z-index: 9999;
                    background: url(images/loading.gif) center no-repeat #fff;
            }
        </style>
    </head>
    <body>
        <div class="loading_img"></div>
        <!-- outer -->
        <div id="outer">
           <?= $this->availableFleets(); ?>
            <?php echo $this->content; ?>
        </div>
		<?php
            $this->inlineScript()
		//->appendFile($this->basePath('js/plugins-min.js?ver=4.6.1'))
		//->appendFile($this->basePath('js/main-min.js?ver=4.6.1'))
                ->appendFile($this->basePath('js/respond.min.js'))
                ->appendFile($this->basePath('js/bootstrap.min.js'))
                ->appendFile('//cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.3.15/slick.min.js')
                ->appendFile('//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js')
                ->appendFile($this->basePath('js/slick-script.js'))
                ->appendFile($this->basePath('js/main.js'))
                //->appendFile($this->basePath('js/js.cookie.js'))
                /*->appendScript('
                     // Using $(document).ready never hurts
                    $(document).ready(function(){

                        // Cookie setting script wrapper
                        var cookieScripts = function () {
                            // Loading external javascript file
                            $.cookiesDirective.loadScript({
                                uri:"external.js",
                                appendTo: "eantics"
                            });
                        }

                        $.cookiesDirective({
                            privacyPolicyUri: "'.$this->basePath('pdf/Informativa_Privacy.pdf').'",
                            explicitConsent: false,
                            position : "bottom",
                            duration: 999999,
                            message: "I cookie ci aiutano a fornire i nostri servizi. Utilizzando tali servizi, accetti l\'utilizzo dei cookie da parte nostra. Per maggiori dettagli leggi la nostra",
                            scriptWrapper: cookieScripts,
                            backgroundColor: "#000000",
                            linkColor: "#ffffff"
                        });
                    });
                ');
            echo $this->inlineScript()*/
        ?>
    </body>
</html>
