<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'))
    ->appendFile($this->basePath('js/signup.js?v=3.9'));

$this->headLink()
    ->appendStylesheet($this->basePath('css/overlay.css'))
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'));
?>

<!-- Facebook Pixel Code -->
<script>
    !function (f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function () {
            n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments)
        }
        ;
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s)
    }(window, document, 'script',
        'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '423565347840059');
    fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
               src="https://www.facebook.com/tr?id=423565347840059&ev=PageView&noscript=1"/></noscript>
<!-- End Facebook Pixel Code -->
<!-- main -->
<div id="main">
    <!-- module-section-bookmark -->
    <div class="module-section-bookmark content-align-center">
        <h1 class="module-main-title"><?= $this->translate('Crea un account Share\'ngo'); ?></h1>
    </div>
    <!-- module-section-bookmark -->
    <script>fbq('track', 'Lead');</script>

    <!-- module-wizard -->
    <div class="module-wizard clearfix" style="width: 430px; margin: 0 auto; padding-bottom: 15px;">
        <ul>
            <li class="active"><i class="fa fa-user"></i></li>
            <li><i class="fa fa-tachometer"></i></li>
            <li><i class="fa fa-credit-card"></i></li>
            <li><i class="fa fa-flag-checkered"></i></li>
        </ul>
    </div>
    <!-- module-wizard -->

    <!-- content -->
    <div class="content">

        <?php
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
        ?>

        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Email'); ?></label>
                        <?php
                        $email = $this->form->get('user')->get('email');
                        echo $this->formElement($email);
                        echo $this->formElementErrors($email, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Password'); ?></label>
                        <?php
                        $password = $this->form->get('user')->get('password');
                        echo $this->formElement($password);
                        echo $this->formElementErrors($password, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p> <label><?= $this->translate('Citt&agrave; preferita'); ?></label>
                        <?php
                        $fleet = $this->form->get('user')->get('fleet');
                        echo $this->formElement($fleet);
                        echo $this->formElementErrors($fleet, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

            </div>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field w-4-4" style="text-align: justify">

                    <?php $privacyCondition = $this->form->get('user')->get('privacyCondition'); ?>
                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($privacyCondition) ?>
                        <span class='control-indicator'
                              id="generalCondition1Text"><?= $privacyCondition->getLabel(); ?></span>
                    </label>
                    <?php echo $this->formElementErrors($privacyCondition, ['class' => 'errors']); ?>

                </div>
            </div>
            <!-- block-row-field -->


            <div class="block-wrapper-button content-align-center">
<!--                <input type="reset" class="reset" name="" id="cancelBtn" value="Annulla">-->
                <input type="submit" name="" id="nextBtn" value="REGISTRATI">
                <p style="font-size: 15px; font-weight: 300; color: #07BA50; padding-top: 15px;">Facendo clic su REGISTRATI accetti<br>
                    le <a style="font-size: 15px; font-weight: 400; color: #07BA50; text-decoration: underline;" href="<?= $this->basePath('pdf/car_sharing_def.pdf'); ?>">condizioni contrattuali</a> di Share'ngo</p>
            </div>


            </form>

        </div>
        <!-- block-form -->

    </div>
    <!-- content -->
    <!-- overlay -->
    <div id="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden">Chiudi</span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more"
                             style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;">ATTENZIONE</h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: justify; font-weight: 500;">Domenica 11 Febbraio dalle
                                    ore 7:30 alle ore 13:30 una manutenzione programmata del sistema di verifica delle
                                    patenti potrebbe causare qualche rallentamento nella procedure di controllo. Le
                                    patenti verranno comunque convalidate entro luned&igrave; mattina.</p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->
</div>
<!-- main -->

<?
$this->inlineScript()->appendScript(
    '$(document).ready(function() {
$( ".datepicker-date" ).datepicker({
dateFormat: "dd-mm-yy",
changeMonth: true,
changeYear: true,
yearRange: "-100:+0",
maxDate: new Date(new Date().getFullYear(), 11, 31)
});
});'
);
?>

<script type="text/javascript">
    var municipalitiesUrl = "<?//= $this->url('core/municipalities') ?>",
        birthTownValue = "<?//= $birthTown->getValue() ?>";

    $(document).ready(function () {
        overlay = $('#sng-overlay');

        var now = new Date(<? echo date("Y, n - 1, d, H, i, s"); ?> );
        var dateStart = new Date(2018, 1, 11, 7, 0, 0, 0);
        var dateEnd = new Date(2018, 1, 11, 14, 0, 0, 0);

        //        var dateStart = new Date(2016, 11, 2, 0, 0, 0, 0);
        //        var dateEnd = new Date(2016, 11, 4, 18, 0, 0, 0);

        if (now >= dateStart && now <= dateEnd) {
            overlay.css("visibility", "visible");
        }

        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(600, function () {
                overlay.remove();
            });
        });

        // Criteo section
        var email = $("#email").val();
        var list = [];
        $("#fleet option").each(function () {
            if (parseInt($(this).val()) !== 0) {
                list.push(parseInt($(this).val()));
            }
            ;
        });

        criteoViewListing(email, list);

        $("#fleet").change(function () {
            var email = $("#email").val();
            var fleetId = parseInt($(this).find(":selected").val());

            criteoViewBasketItem(email, fleetId);
        });

    });

    /*signup favourite city draft*/

    //$(document).ready(function () {
        console.log('ciao');
        var apiGeolocationSuccess = function(position) {
            //alert("API geolocation success!\n\nlat = " + position.coords.latitude + "\nlng = " + position.coords.longitude);

            var MilanoLat = 45.4542119, MilanoLon = 9.1113509617797;
            var FirenzeLat = 43.8461388, FirenzeLon = 11.3743562543917;
            var ModenaLat = 44.6458885, ModenaLon = 10.9255707;
            var RomaLat = 41.8935085, RomaLon = 12.4825526;
            var arr = [];
            arr[1] = Math.abs(MilanoLat-position.coords.latitude)+Math.abs(MilanoLon-position.coords.longitude);
            arr[2] = Math.abs(FirenzeLat-position.coords.latitude)+Math.abs(FirenzeLon-position.coords.longitude);
            arr[3] = Math.abs(RomaLat-position.coords.latitude)+Math.abs(RomaLon-position.coords.longitude);
            arr[4] = Math.abs(ModenaLat-position.coords.latitude)+Math.abs(ModenaLon-position.coords.longitude);

            var min = Math.min(arr[1], arr[2], arr[3], arr[4]);
            var i = arr.indexOf(min);

            $('select#fleet>option:eq('+i+')').attr('selected', true);
        };

        var tryAPIGeolocation = function() {
            jQuery.post( "https://www.googleapis.com/geolocation/v1/geolocate?key=AIzaSyC8FZ21zdDF6HLNc0hYJthJvqqcoM4aCiI", function(success) {
                apiGeolocationSuccess({coords: {latitude: success.location.lat, longitude: success.location.lng}});
            })
                .fail(function(err) {
                    //alert("API Geolocation error! \n\n"+err);
                    console.log(err);
                });
        };

        tryAPIGeolocation();
    //});

</script>
