<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'))
    ->appendFile($this->basePath('js/signup.js?v=4.4'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css?v=0.1'));
$this->inlineScript()
    ->appendFile($this->basePath('js/driver-license-popup.js'));
$this->placeholder('facebook-pixel')->set('<script>fbq(\'track\', \'CompleteRegistration\');</script>');
$this->placeholder('google-analytics')->set('<script>gtag(\'event\', \'conversion\', {\'send_to\': \'AW-953520877/wYOdCOz65lwQ7aXWxgM\'});</script>');
?>
<style>
    .sub{
        font-size: 18px;
    }
    @media only screen and (max-width: 767px){
        .sub {
            font-size: 13px;

        }
    }
</style>
<div class="module-section-bookmark yellow content-align-center">
    <!-- MYSHARENGO 
    <h1 class="module-main-title"><?= $this->translate('Pacchetto Benvenuto'); ?></h1>
    <div class="module-main-title-2" style="display: inline-block; padding-top: 15px">
        <p>
            <b><?= $this->translate('21 minuti a soli 5&euro;') ?></b><br>
            <?= $this->translate('e guidi subito la tua Sharengo!') ?>
        </p>
    </div>
    -->
    <h1 class="module-main-title"><?= $this->translate('Iscriverti ti costa solo 1€'); ?></h1>
    <div class="module-main-title-2" style="display: inline-block; padding-top: 15px">
        <p>
            <b><?= $this->translate('e guidi subito la tua Sharengo!') ?></b>
        </p>
    </div>
</div>

<div class="module-main-subtitle content-align-center">
    <p><?= $this->translate('Benvenuto') ?> <?= $this->email ?><br>
        <?= $this->translate('Pochi istanti per completare il tuo profilo') ?></p>
</div>

<!-- main -->
<div id="main">

    <!-- module-wizard -->
    <div class="module-wizard clearfix">
        <ul>
            <li class="active">1</i></li>
            <li class="active">2</li>
            <li>3</li>
            <li class="last"><i class="icon-auto"></i></li>
        </ul>
    </div>
    <!-- module-wizard -->

    <!-- content -->
    <div class="content">

        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <?php
            $this->form->prepare();
            echo $this->form()->openTag($this->form);
            ?>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field bw-f w-1-3">
                    <label><?= $this->translate('Nome Patente'); ?></label>
                        <?php
                        $driverLicenseName = $this->form->get('user1')->get('driverLicenseName');
                        echo $this->formElement($driverLicenseName);
                        echo $this->formElementErrors($driverLicenseName, ['class' => 'errors']);
                        ?>
                </div>

                <div class="block-field bw-f w-1-3">
                    <label><?= $this->translate('Cognome Patente'); ?></label>
                    <?php
                    $driverLicenseSurname = $this->form->get('user1')->get('driverLicenseSurname');
                    echo $this->formElement($driverLicenseSurname);
                    echo $this->formElementErrors($driverLicenseSurname, ['class' => 'errors']);
                    ?>
                </div>
                <div class="block-field bw-f w-1-3">
                </div>

            </div>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <div class="block-field bw-f w-2-4" id="coherenceTaxCodeName">
                    <label><?= $this->translate('Nome codice fiscale'); ?></label>
                    <?php
                    $name = $this->form->get('user1')->get('name');
                    echo $this->formElement($name);
                    echo $this->formElementErrors($name, ['class' => 'errors']);
                    ?>
                </div>
                <div class="block-field bw-f w-2-4" id="coherenceTaxCodeSurname">
                    <label><?= $this->translate('Cognome codice fiscale'); ?></label>
                    <?php
                    $surname = $this->form->get('user1')->get('surname');
                    echo $this->formElement($surname);
                    echo $this->formElementErrors($surname, ['class' => 'errors']);
                    ?>
                </div>
            </div>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <div class="block-field bw-f w-1-4">
                    <label><?= $this->translate("Stato di residenza"); ?></label>
                    <?php
                    $country = $this->form->get('user1')->get('country');

                    echo $this->formElement($country->setAttribute('class', 'required'));
                    echo $this->formElementErrors($country, ['class' => 'error-sign-up']);
                    ?>
                </div>
                <div class="block-field bw-f w-3-4 last">
                    <div class="block-field bw-f w-2-4">
                        <label><?= $this->translate("Provincia di residenza"); ?></label>
                        <?php
                        $province = $this->form->get('user1')->get('province');
                        echo $this->formElement($province->setAttribute('class', 'required'));
                        echo $this->formElementErrors($province, ['class' => 'error']);
                        ?>
                    </div>
                    <div class="block-field bw-f w-2-4 last">
                        <label><?= $this->translate("Citt&agrave;"); ?></label>
                        <?php
                        $town = $this->form->get('user1')->get('town');
                        $select = '<select name="' . $town->getName() . '" ';
                        foreach ($town->getAttributes() as $attribute => $value) {
                            $select .= $attribute . '="' . $value . '" ';
                        }
                        $select .= '><option></option></select>';
                        echo $select;
                        $input = '<input name="' . $town->getName() . '" ';
                        foreach ($town->getAttributes() as $attribute => $value) {
                            $input .= $attribute . '="' . $value . '" ';
                        }
                        $input .= ' style="display: none;" value="' . $town->getValue() . '" disabled></ipnut>';
                        echo $input;
                        echo $this->formElementErrors($town, ['class' => 'errors']);
                        ?>
                        </p>
                    </div>
                </div>
            </div>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <div class="block-field bw-f w-2-4">
                    <label><?= $this->translate('Indirizzo di residenza'); ?></label>
                    <?php
                    $address = $this->form->get('user1')->get('address');
                    echo $this->formElement($address);
                    echo $this->formElementErrors($address, ['class' => 'errors']);
                    ?>
                </div>
                <div class="block-field bw-f w-1-4">
                    <label><?= $this->translate('N. civico'); ?></label>
                    <?php
                    $address = $this->form->get('user1')->get('civico');
                    echo $this->formElement($address);
                    echo $this->formElementErrors($address, ['class' => 'errors']);
                    ?>
                </div>

                <div class="block-field bw-f w-1-4">
                    <label><?= $this->translate("Cap"); ?></label>
                    <?php

                    $zipCode = $this->form->get('user1')->get('zipCode');
                    $select = '<select name="' . $zipCode->getName() . '" ';
                    foreach ($zipCode->getAttributes() as $attribute => $value) {
                        $select .= $attribute . '="' . $value . '" ';
                    }
                    $select .= '><option></option></select>';
                    echo $select;
                    $input = '<input name="' . $zipCode->getName() . '" ';
                    foreach ($zipCode->getAttributes() as $attribute => $value) {
                        $input .= $attribute . '="' . $value . '" ';
                    }
                    $input .= ' style="display: none;" value="' . $zipCode->getValue() . '" disabled></ipnut>';
                    echo $input;
                    echo $this->formElementErrors($zipCode, ['class' => 'errors']);

                    ?>
                </div>
            </div>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <div class="block-field bw-f w-1-4">
                    <label><?= $this->translate('Prefisso'); ?></label>
                    <?php
                    $dialCode = $this->mobileForm->get('dialCode');
                    echo $this->formElement($dialCode->setAttribute('class', 'required'));
                    echo $this->formElementErrors($dialCode, ['class' => 'error-sign-up']);
                    ?>
                </div>
                <div class="block-field bw-f w-2-4 ">
                    <label><?= $this->translate('Cellulare'); ?></label>
                        <?php
                        $mobile = $this->form->get('user1')->get('mobile');
                        echo $this->formElement($mobile);
                        echo $this->formElementErrors($mobile, ['class' => 'errors']);
                        ?>
                </div>
                <div class="block-field bw-f w-1-4">
                    <label>&nbsp</label>
                    <div style="display: block;" id="buttonCode">
                        <input type="text" id="email" hidden="true" value="<?= $this->customerEmail ?>" >
                        <button type="button" id="buttonSendCode"><?= $this->translate("INVIA CODICE") ?></button>
                    </div>
                </div>
            </div>

            <div class="block-row-field clearfix">
                <div id="confirmSmsCode" style="display: none;">
                    <div class="block-field bw-f w-1-4" id="textCode">
                        <p>
                            <label><?= $this->translate('Codice di Verifica'); ?></label>
                            <?php
                            $smsCode = $this->form->get('user1')->get('smsCode');
                            echo $this->formElement($smsCode);
                            echo $this->formElementErrors($smsCode, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>
                    <div>
                        <p>
                            <label class="small-form">
                                <?= $this->translate("INSERISCI QUI IL CODICE DI VERIFICA INVIATO VIA SMS, SE NON RICEVI IL MESSAGGIO, CONTATTA IL SERVIZIO CLIENTI") ?>
                            </label>
                        </p>
                    </div>
                </div>
            </div>
            <!-- FINE -->
            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field bw-f w-2-4">
                    <label><?= $this->translate('Codice fiscale'); ?></label>
                    <?php
                    $taxCode = $this->form->get('user1')->get('taxCode');
                    echo $this->formElement($taxCode);
                    echo $this->formElementErrors($taxCode, ['class' => 'errors']);
                    ?>
                </div>

            </div>
            <div class="block-row-field clearfix">
                <div class="block-field bw-f w-1-3">
                    <label><?= $this->translate('Numero patente'); ?></label>
                        <a href=""><i class="fa fa-info-circle"></i></a>
                        <?php
                        $driverLicense = $this->form->get('user1')->get('driverLicense');
                        echo $this->formElement($driverLicense);
                        echo $this->formElementErrors($driverLicense, ['class' => 'errors']);
                        ?>
                    <label class="small-form"><?= $this->translate('&Egrave; obbligatoria una patente valida per quadricicli pesanti categoria L7e'); ?></label>
                </div>

                <div class="block-field bw-f w-1-3">
                    <label><?= $this->translate('Scadenza patente'); ?></label>
                        <?php
                        $driverLicenseExpire = $this->form->get('user1')->get('driverLicenseExpire');
                        echo $this->formElement($driverLicenseExpire);
                        echo $this->formElementErrors($driverLicenseExpire, ['class' => 'errors']);
                        ?>
                </div>

                <div class="block-field bw-f w-1-3">
                    <label style="margin-right: 5px;"><?= $this->translate('Rilasciata (nazione)'); ?></label>
                    <?php
                    $driverLicenseCountry= $this->form->get('user1')->get('driverLicenseCountry');
                    echo $this->formElement($driverLicenseCountry->setAttribute('class', 'required'));
                    echo $this->formElementErrors($driverLicenseCountry, ['class' => 'errors']);

                    $driverLicenseUploadStyle = "display: none";
                    if($driverLicenseCountry->getValue()!='it' && $driverLicenseCountry->getValue()!=''){
                        $driverLicenseUploadStyle = "visibility: visible";
                    }
                    ?>
                </div>
            </div>
            <div id="driverLicenseUpload" style="<?= $driverLicenseUploadStyle ?>">
                <div class="block-field auto-margin">
                    <div style="font-weight: bold; text-align: center"><?= $this->translate("DICHIARAZIONE SOSTITUTIVA DELL'ATTO DI NOTORIETA'"); ?><br><?= $this->translate("CERTIFICAZIONE DISPONIBILITA' PATENTE DI GUIDA"); ?></div>
                    <div style="font-weight: bold; text-align: center"><?= $this->translate("(Artt. 21 comma 1 - 38 comma 2 e 3 del D.P.R. N. 445 del 28.12.2000)") ?></div>
                    <div class="message font" style="text-align: justify;">
                        <?= $this->translate("Il sottoscritto") . ' ' .
                        '<span id="fName"></span> <span id="fSurname"></span>' . ' '
                        ?>,
                        <?= $this->translate("consapevole delle sanzioni penali cui pu&ograve andare incontro in caso di dichiarazioni mendaci, sanzioni penali previste dal Codice penale e dalle leggi speciali in materia ed espressamente richiamate dall'art. 76 del D.P.R. N. 445 DEL 28/12/2000, sotto la sua responsabilit&agrave"); ?>
                        <br>

                        <div style="font-weight: bold; text-align: center"><?= $this->translate("DICHIARA"); ?></div>
                        <br>
                        <?= $this->translate("di essere titolare di patente di guida in corso di validit&agrave "); ?> <?= "<span id='fDriverLicense'></span>"?>.
                        <?= $this->translate("E altresì dichiara che suddetto documento di guida è valido, in relazione alle norme internazionali di circolazione (legate alla residenza del cittadino straniero su territorio italiano e alla durata della stessa), ai fini della guida sul territorio italiano.");?>
                    </div>
                    <br>
                    <div>
                        <?php $signature = $this->form->get('signature');
                        echo $this->formElement($signature);
                        ?>
                        <label style="margin-right: 5px;"><?= $this->translate("Letto, confermato e sottoscritto"); ?></label>
                        <?php
                        echo $this->formElementErrors($signature, ['class' => 'errors']);
                        ?>
                    </div>
                    <br>
                    <div>
                        Livorno, lì <?= date("d/m/Y")?>
                    </div>
                    <br>
                    <div style="font-size: 70%;text-align: justify">
                        <?= $this->translate("Ai sensi dell'art. .16 del D.P.R. 445/2000 e nel rispetto del Decreto Legislativo sulla Privacy 196/2003 i dati personali riportati sulla presente dichiarazione sono relativi ad  informazioni strettamente necessarie al conseguimento di finalit&agrave previste dalle vigenti normative e sono trattati e custoditi esclusivamente dall'ufficio responsabile del procedimento."); ?>
                    </div>
                    <div style="font-size: 80%; font-weight: bold; text-decoration: underline">
                        <?= $this->translate("Esente da Autentica"); ?>
                    </div>
                    <br>
                </div>
                <label><?= $this->translate("Occorre allegare copia fotostatica, anche non autenticata, della patente di guida e della carta di identità, entrambe fronte e retro"); ?></label><br><br>
                <div class="block-row-field clearfix">
                    <div class="block-field bw-f w-2-4">
                        <p> <label style="margin-right: 5px;"><?= $this->translate('fronte patente di guida'); ?></label>
                            <?php $driverLicenseForeignUpload = $this->form->get('drivers-license-front'); ?>
                            <?php echo $this->formFile($driverLicenseForeignUpload);
                            echo $this->formElementErrors($driverLicenseForeignUpload, ['class' => 'errors']); ?>
                        </p>
                    </div>
                    <div class="block-field bw-f w-2-4">
                        <p> <label style="margin-right: 5px;"><?= $this->translate('retro patente di guida'); ?></label>
                            <?php $driverLicenseForeignUpload = $this->form->get('drivers-license-back'); ?>
                            <?php echo $this->formFile($driverLicenseForeignUpload);
                            echo $this->formElementErrors($driverLicenseForeignUpload, ['class' => 'errors']); ?>
                        </p>
                    </div>
                </div>
                <div class="block-row-field clearfix">
                    <div class="block-field bw-f w-2-4">
                        <p> <label style="margin-right: 5px;"><?= $this->translate('fronte carta di identità'); ?></label>
                            <?php $driverLicenseForeignUpload = $this->form->get('identity-front'); ?>
                            <?php echo $this->formFile($driverLicenseForeignUpload);
                            echo $this->formElementErrors($driverLicenseForeignUpload, ['class' => 'errors']); ?>
                        </p>
                    </div>
                    <div class="block-field bw-f w-2-4">
                        <p> <label style="margin-right: 5px;"><?= $this->translate('retro carta di identità'); ?></label>
                            <?php $driverLicenseForeignUpload = $this->form->get('identity-back'); ?>
                            <?php echo $this->formFile($driverLicenseForeignUpload);
                            echo $this->formElementErrors($driverLicenseForeignUpload, ['class' => 'errors']); ?>
                        </p>
                    </div>
                </div>
            </div>
            </div>

            <!-- block-row-field -->
            <div class="block-form w-4-4 auto-margin clearfix">
                <p class="codicePromo"><?= $this->translate("INSERISCI QUI SE HAI UN CODICE PROMO") ?></p>

                <!-- block-row-field -->
                <div class="block-row-field  content-align-center  clearfix">
                    <div class='block-field  auto-margin w-2-4 '>
                        <div class="block-field bw-f  w-2-3">
                            <p>
                                <?php
                                $promocode = $this->form->get('promocode')->get('promocode');
                                echo $this->formElement($promocode);
                                ?>
                            </p>
                        </div>
                        <div class="block-field bw-f last  w-1-3">
                            <button  type="button" id="buttonVerifyPromo"><?= $this->translate("Applica") ?></button>
                        </div>
                        <div id="promodiv" class=""></div>
                        <div id="errorepromo">
                            <?php echo $this->formElementErrors($promocode, ['class' => 'errors']); ?>

                        </div>
                    </div>

                </div>
                <p style="font-size: 14px ; text-align: center; padding: 0px 0 10px 0">
                    <?= $this->translate("Attivazione include il controllo della Patente<br>con il Ministero dei Trasporti.") ?></p>
                <div class="block-wrapper-button content-align-center">

                    <input type="submit" name="nextBtn" id="nextBtn" value="<?= $this->translate('Continua'); ?>">
                </div>

                </form>

            </div>
            <!-- block-form -->

        </div>
        <!-- content -->

    </div>
    <!-- main -->
    <!-- overlay foreign driver license -->
    <div id="sng-overlay" class="driver-foreign" style="visibility: hidden; background: rgba(0, 0, 0, 0.3);">
        <div class="table">
            <div class="cell">
                <div class="box" id="popup" style="background:#45ad4e !important; max-width: 800px; border-radius: 50px; padding-top: 10px; font-family: 'Open Sans', sans-serif;">
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-image: none; text-align: left !important;">
                            <br>
                            <div id="italian">
                                <p align="right"><a onclick="closeChangeCard()" style="color:#fff"><b>[X] <?= $this->translate("Chiudi");?></b></a></p>
                                <p style="color:#fff;text-align: left; font-weight: 500;">
                                    <b class="sub"><?= $this->translate("Prima di procedere verifica:");?></b><br><br>
                                    <b><?= $this->translate("Hai una patente europea senza scadenza?");?></b><br>
                                    <?= $this->translate("Se la tua patente europea non ha una scadenza compila l'autocertificazione che ti invieremo via email. E nel caso tu sia residente in Italia da più di 2 anni devi convertirla in quella italiana.");?>
                                    <br><br>
                                    <b><?= $this->translate("Hai una patente estera non europea?"); ?></b><br>
                                    <?= $this->translate("Per registrarti devi disporre di una patente internazionale o di una traduzione giurata del documento e compilare il modulo di autocertificazione che ti invieremo via mail. Se sei residente in Italia da più di un anno è necessario convertirla in quella italiana."); ?>
                                </p>
                            </div>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->

    <!-- overlay upload limit size -->
    <div id="sng-overlay" class="overlay-upload" style="visibility: hidden; background: rgba(0, 0, 0, 0.3);">
        <div class="table">
            <div class="cell">
                <div class="box" id="popup" style="background:#45ad4e !important; max-width: 800px; border-radius: 50px; padding-top: 10px; font-family: 'Open Sans', sans-serif;">
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-image: none; text-align: left !important;">
                            <br>
                                <p align="right"><a onclick="closeUploadAlert()" style="color:#fff"><b>[X] <?= $this->translate("Chiudi");?></b></a></p>
                                <p style="color:#fff;text-align: left; font-weight: 500;">
                                    <?= $this->translate("I file inseriti superano la dimensione massima caricabile.")." (max. ".ini_get('post_max_size'). "B)"; ?>
                                </p>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->

    <!-- overlay already signup -->
    <div id="sng-overlay" class="overlay-signup" style="visibility: hidden; background: rgba(0, 0, 0, 0.3);">
        <div class="table">
            <div class="cell">
                <div class="box" id="popup" style="background:#45ad4e !important; max-width: 800px; border-radius: 50px; padding-top: 10px; font-family: 'Open Sans', sans-serif;">
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-image: none; text-align: left !important;">
                            <br>
                            <p align="right"><a onclick="closeSignup()" style="color:#fff"><b>[X] <?= $this->translate("Chiudi");?></b></a></p>
                            <h2 style="color:#fff;text-align: center; font-weight: 800;font-family: 'Open Sans', sans-serif"><?= $this->translate("Sei già iscritto!");?></h2>
                            <hr style="height:2px;border:none;color:#fff;background-color:#fff;">
                            <p style="color:#fff;text-align: center; font-weight: 800; font-family: 'Open Sans', sans-serif">
                                <br>
                                <?= $this->translate("Per completare l'inserimento dei tuoi dati clicca sopra su ACCEDI e fai LOGIN"); ?>
                            </p>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->

    <!-- module-modal -->
    <div class="module-modal" style="height: 3000px; display: none;">
        <!-- modal-overlay -->
        <div class="modal-overlay">
            <!-- module-pop-up -->
            <div class="module-pop-up" style="margin:350px auto;">

                <a class="btn-close"><i class="fa fa-close"></i></a>

                <!-- module-pop-up-content -->
                <div class="module-pop-up-content">

                    <!-- block-pop-up-generic-content -->
                    <div class="block-pop-up-generic-content">
                        <img src="<?= $this->basePath('images/patente-fac-simile.jpg'); ?>" alt="">
                        <p>
                            <?= $this->translate('5. Numero Patente'); ?>
                        </p>
                    </div>
                    <!-- block-pop-up-generic-content -->

                </div>
                <!-- module-pop-up-content -->

            </div>
            <!-- module-pop-up -->
        </div>
        <!-- modal-overlay -->
    </div>
    <!-- module-modal -->

    <?php
    $this->headLink()->appendStylesheet($this->basePath('css/overlay.css'));
    $this->inlineScript()->appendScript(
        '$(document).ready(function() {
            $( "#driverLicenseReleaseDate" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
                maxDate: new Date(new Date().getFullYear(), 11, 31)
            });
        });
        $(document).ready(function() {
            $( "#driverLicenseExpire" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "+0:+100",
                minDate: new Date(new Date().getFullYear(), 0, 1)
            });
        });'
    );
    ?>
    <script>
        <?php
        function parse_size($size) {
            $unit = preg_replace('/[^bkmgtpezy]/i', '', $size); // Remove the non-unit characters from the size.
            $size = preg_replace('/[^0-9\.]/', '', $size); // Remove the non-numeric characters from the size.
            if ($unit) {
                // Find the position of the unit in the ordered string which is the power of magnitude to multiply a kilobyte by.
                return round($size * pow(1024, stripos('bkmgtpezy', $unit[0])));
            }
            else {
                return round($size);
            }
        } ?>
        //File Upload Validation
        var maxUpload = <?= parse_size(ini_get('post_max_size')) ?> ;

        var driversLicenseFront = document.getElementById("drivers-license-front");
        var driversLicenseBack = document.getElementById("drivers-license-back");

        var driverLicenseCountry = document.getElementById("driverLicenseCountry");
        var driverLicenseUpload = document.getElementById("driverLicenseUpload");

        var identityFront = document.getElementById("identity-front");
        var identityBack = document.getElementById("identity-back");

        var driversLicenseFrontSize = 0;
        var driversLicenseBackSize = 0;
        var identityFrontSize = 0;
        var identityBackSize = 0;

        driversLicenseFront.onchange = function() {
            driversLicenseFrontSize = driversLicenseFront.files[0].size;
            checkUploadSize(this);
        };

        driversLicenseBack.onchange = function() {
            driversLicenseBackSize = driversLicenseBack.files[0].size;
            checkUploadSize(this);
        };

        identityFront.onchange = function() {
            identityFrontSize = identityFront.files[0].size;
            checkUploadSize(this);
        };

        identityBack.onchange = function() {
            identityBackSize = identityBack.files[0].size;
            checkUploadSize(this);
        };

        totalSize = function() {
            return (driversLicenseFrontSize + driversLicenseBackSize + identityFrontSize + identityBackSize);
        };

        checkUploadSize = function (inputFile) {
            if(totalSize() > maxUpload){
                openUploadAlert();
                inputFile.value = "";
            }
        };

        function closeUploadAlert(){
            overlay = $('.overlay-upload');
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        }

        function openUploadAlert(){
            overlay = $('.overlay-upload');
            overlay.css("visibility", "visible");
        }

        driverLicenseCountry.onchange = function() {
            console.log("driverLicenseCountry " + this.value);

            if(this.value!=='it') {
                setTimeout(
                    function(){ openChangeCard(); },
                    100);   // this delay is avoid mouseup event that fire  closeChangeCard function and close overlay

                $('#driverLicenseUpload').show();
            } else {
                $('#driverLicenseUpload').hide();
            }
        }

        <?php // in case driver license' name and surname are different from tax code
        if($this->formElementErrors($this->form->get('user1')->get('name')) != ""){?>
            $('#coherenceTaxCodeName').show();
        <?php } else { ?>
            $('#coherenceTaxCodeName').hide();
        <?php } ?>

        <?php // in case driver license' name and surname are different from tax code
        if($this->formElementErrors($this->form->get('user1')->get('surname')) != ""){?>
        $('#coherenceTaxCodeSurname').show();
        <?php } else { ?>
        $('#coherenceTaxCodeSurname').hide();
        <?php } ?>

        <?php // in case taxCode is already present
        if($this->formElementErrors($this->form->get('user1')->get('taxCode')) == "<ul><li>".$this->translate("Esiste già un utente con lo stesso codice fiscale")."</li></ul>"){?>
            overlay = $('.overlay-signup');
            overlay.css("visibility", "visible");
        <?php } ?>

        $('#driverLicenseName').blur(function(){
            $('#fName').text($('#driverLicenseName').val());
        });

        $('#driverLicenseSurname').blur(function(){
            $('#fSurname').text($('#driverLicenseSurname').val());
        });

        $('#driverLicense').blur(function(){
            $('#fDriverLicense').text('n. ' + $('#driverLicense').val());
        });

        $(function() {
            $('#registration-form-2').on('submit', function(e) {
                $("#nextBtn").attr("disabled", true);
                addLoader();
            });
        });

        var addLoader = function() {
            $("#outer").prepend("<div class=\"load-overlay\"><div>" + "<p><i class=\"fa fa-refresh fa-spin\">" + "</i></p></div></div>");
        };
        var removeLoader = function() {
            $("#outer > div.load-overlay").remove();
        };

        function openChangeCard() {
            overlay = $('.driver-foreign');
            overlay.css("visibility", "visible");
        }
        function closeChangeCard() {
            overlay = $('.driver-foreign');
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        }

        function closeSignup() {
            overlay = $('.overlay-signup');
            overlay.fadeOut(400, function () {
                overlay.css("visibility", "hidden");
                overlay.css("display","initial");
            });
        }

        $(document).mouseup(function (e) {
            var popup = $("#popup");
            if (popup.has( e.target ).length == 0 && popup.css('visibility') === 'visible') {
                closeChangeCard();
            }
        });
    </script>
    <script type="text/javascript">
        var municipalitiesUrl = "<?= $this->url('core/municipalities') ?>"
        var townValue ="";
    </script>
    <script async src="//onetag-sys.com/sync/a,63/2"></script>
    <?php
    if($this->customerFleetId == 1){
        echo '
        <!-- Adform Tracking Code BEGIN -->
        <script type="text/javascript">
            window._adftrack = Array.isArray(window._adftrack) ? window._adftrack : (window._adftrack ? [window._adftrack] : []);
            window._adftrack.push({
                pm: 1171594,
                divider: encodeURIComponent(\'|\'),
                pagename: encodeURIComponent(\'RD-PIXEL_SharenGo_MILANO_TYP\'),
                order : { 
                     orderid: \'<insert order id value here>\'
                }
            });
            (function () { var s = document.createElement(\'script\'); s.type = \'text/javascript\'; s.async = true; s.src = \'https://track.adform.net/serving/scripts/trackpoint/async/\'; var x = document.getElementsByTagName(\'script\')[0]; x.parentNode.insertBefore(s, x); })();
    
        </script>
        <noscript>
            <p style="margin:0;padding:0;border:0;">
                <img src="https://track.adform.net/Serving/TrackPoint/?pm=1171594&ADFPageName=RD-PIXEL_SharenGo_MILANO_TYP&ADFdivider=|" width="1" height="1" alt="" />
            </p>
        </noscript>
        <!-- Adform Tracking Code END -->
        <script src="https://secure.adnxs.com/px?id=993709&t=1" type="text/javascript"></script>';
    }else if($this->customerFleetId == 3){
        echo '<script src="https://secure.adnxs.com/px?id=993711&t=1" type="text/javascript"></script>';
    }
    ?>
