<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css'));
$this->inlineScript()
    ->appendFile($this->basePath('js/driver-license-popup.js'));
?>
<div class="module-section-bookmark yellow content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Ora sei dei nostri!'); ?></h1>
    <div class="module-main-title-2" style="display: inline-block; padding-top: 15px">
        <p>
            <b>Scarica l'App e...</b><br>
            <img style="width: 100%;max-width: 500px;height: auto; padding-top: 10px;" src="<?= $this->basePath('images/gosharengo.png') ?>">
        </p>
    </div>
</div>

<?php if ($this->outcome == 'OK'): ?>
    <div class="module-main-subtitle content-align-center">
        <p><?= $this->translate('Pagamento avvenuto!' )?></p>
    </div>
<?php else: ?>
    <div class="module-main-subtitle content-align-center">
            <p><?= $this->translate('Si è verificato un problema' )?></p>
            <span><?= $this->translate('Il pagamento non è andato a buon fine.') ?><br>
                <?= $this->translate('Il messaggio di errore che abbiamo ricevuto è: "').$this->message.'"' ?><br>
                <?= $this->translate('Contattare l\'assistenza per maggiori informazioni')?><br>
                <?= $this->translate('Sarà possibile riprovare il pagamento in Area Riservata')?></span>
    </div>
<?php endif; ?>

<!-- main -->
<div id="main">

    <!-- module-wizard -->
    <div class="module-wizard clearfix">
        <ul>
            <li class="active">1</li>
            <li class="active">2</li>
            <li class="active">3</li>
            <li class="active"><i class="icon-auto active"></i></li>
        </ul>
    </div>
    <!-- module-wizard -->

    <!-- content -->
    <div class="content">
            <!-- block-form -->
            <div class="block-form w-3-4 auto-margin clearfix">

                <?php
                $this->form->prepare();
                echo $this->form()->openTag($this->form);
                ?>

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Professione'); ?></label>
                            <?php
                            $jobType = $this->form->get('optional')->get('jobType');
                            echo $this->formElement($jobType);
                            echo $this->formElementErrors($jobType, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Come hai conosciuto Sharengo?'); ?></label>
                            <?php
                            $howToKnow = $this->form->get('optional')->get('howToKnow');
                            echo $this->formElement($howToKnow);
                            echo $this->formElementErrors($howToKnow, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>
                </div>
                <!-- block-row-field -->


                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Partita IVA (solo per ditte individuali e professionisti)'); ?></label>
                            <?php
                            $vat = $this->form->get('optional')->get('vat');
                            echo $this->formElement($vat);
                            echo $this->formElementErrors($vat, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>
                </div>

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field w-4-4" style="text-align: justify">

                        <?php $newsletter = $this->form->get('optional')->get('newsletter'); ?>
                        <label class='control checkbox small-form'>
                            <?php echo $this->formElement($newsletter) ?>
                            <span class='control-indicator'
                                  id="generalCondition1Text"><?= $newsletter->getLabel(); ?></span>
                        </label>
                        <?php echo $this->formElementErrors($newsletter, ['class' => 'errors']); ?>

                    </div>
                </div>
                <!-- block-row-field -->
                <br>
                <div class="block-wrapper-button content-align-center">

                    <input type="submit" name="" value="<?= $this->translate('Conferma');?>">
                    <!--<input type="button" style="    background: #43a34c;
    width: auto;
    text-align: center;
    color: #000;
    font-weight: normal;
    line-height: 1em;
    height: 40px;
    display: inline-block;
    padding: 12px 20px 10px 20px;
    border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    font-size: 18px;
    text-decoration: none;
    border: 1px solid #255b2a;
    -moz-transition: all .2s ease-in-out;
    -webkit-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    transition: all .2s ease-in-out;
    backface-visibility: hidden;
    webkit-backface-visibility: hidden;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-transform: uppercase;
" value="Scopri gli altri vantaggi per te" onclick="location.href='http://site.sharengo.it/vantaggi-per-te/';"></input>-->
                </div>

                </form>

            </div>
            <!-- block-form -->

        </div>
        <!-- content -->

    </div>
    <!-- main -->

    <?
    $this->inlineScript()->appendScript(
        '$(document).ready(function() {
            $( "#driverLicenseReleaseDate" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
                maxDate: new Date(new Date().getFullYear(), 11, 31)
            });
        });
        $(document).ready(function() {
            $( "#driverLicenseExpire" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "+0:+100",
                minDate: new Date(new Date().getFullYear(), 0, 1)
            });
        });'
    );
    ?>

    <script>
        if($('#driverLicenseForeign').is(":checked"))
            $('#self_declaretion').show();
        else
            $('#self_declaretion').hide();

        $('#driverLicenseForeign').change(function(){
            if($('#driverLicenseForeign').is(":checked"))
                $('#self_declaretion').show();
            else
                $('#self_declaretion').hide();
        });
    </script>
