<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-it.js'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css'));
$this->inlineScript()
    ->appendFile($this->basePath('js/driver-license-popup.js'));
?>
<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Completa il tuo profilo'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

    <!-- module-wizard -->
    <div class="module-wizard clearfix">
        <ul>
            <li class="active"><i class="fa fa-user"></i></li>
            <li class="active"><i class="fa fa-tachometer"></i></li>
            <li class="active"><i class="fa fa-credit-card"></i></li>
            <li class="active"><i class="fa fa-flag-checkered"></i></li>
        </ul>
    </div>
    <!-- module-wizard -->

    <!-- content -->
    <div class="content">


        <?php if ($this->outcome == 'OK'): ?>
            <!-- block-form -->
            <div class="block-form w-3-4 auto-margin clearfix">

                <div class="content-align-center margin-bottom">
                    <h2><?= $this->translate('Pagamento completato')?></h2>
                    <p><?= $this->translate('Ti confermiamo la ricezione del pagamento')?></p>
                </div>

            </div>
            <!-- block-form -->


            <div class="block-form w-3-4 auto-margin clearfix">
                <h3>Completa il tuo profilo per l'accredito dei tuoi minuti bonus!</h3>
                <br>
            </div>

            <!-- block-form -->
            <div class="block-form w-3-4 auto-margin clearfix">

                <?php
                $this->form->prepare();
                echo $this->form()->openTag($this->form);
                ?>

                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Professione'); ?></label>
                            <?php
                            $jobType = $this->form->get('optional')->get('jobType');
                            echo $this->formElement($jobType);
                            echo $this->formElementErrors($jobType, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Come hai conosciuto Sharengo?'); ?></label>
                            <?php
                            $howToKnow = $this->form->get('optional')->get('howToKnow');
                            echo $this->formElement($howToKnow);
                            echo $this->formElementErrors($howToKnow, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>
                </div>
                <!-- block-row-field -->


                <!-- block-row-field -->
                <div class="block-row-field clearfix">

                    <div class="block-field bw-f w-2-4">
                        <p> <label><?= $this->translate('Partita IVA (solo per ditte individuali e professionisti)'); ?></label>
                            <?php
                            $vat = $this->form->get('optional')->get('vat');
                            echo $this->formElement($vat);
                            echo $this->formElementErrors($vat, ['class' => 'errors']);
                            ?>
                        </p>
                    </div>

                </div>
                <div class="block-wrapper-button content-align-center">
                    <br>
                    <hr>
                    <br>

                    <!--<input type="submit" name="" value="<?/*= $this->translate('Attiva il tuo account'); */?>">-->
                    <input type="button" style="    background: #43a34c;
    width: auto;
    text-align: center;
    color: #000;
    font-weight: normal;
    line-height: 1em;
    height: 40px;
    display: inline-block;
    padding: 12px 20px 10px 20px;
    border-radius: 4px;
    -moz-border-radius: 4px;
    -webkit-border-radius: 4px;
    font-size: 18px;
    text-decoration: none;
    border: 1px solid #255b2a;
    -moz-transition: all .2s ease-in-out;
    -webkit-transition: all .2s ease-in-out;
    -o-transition: all .2s ease-in-out;
    transition: all .2s ease-in-out;
    backface-visibility: hidden;
    webkit-backface-visibility: hidden;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-transform: uppercase;
" value="Scopri gli altri vantaggi per te" onclick="location.href='http://site.sharengo.it/vantaggi-per-te/';"></input>
                </div>

                </form>

            </div>
            <!-- block-form -->
        <?php else: ?>
            <!-- block-form -->
            <div class="block-form w-3-4 auto-margin clearfix">

                <div class="content-align-center margin-bottom">
                    <h2><?= $this->translate('Si è verificato un problema' )?></h2>
                    <p><?= $this->translate('Il pagamento non è andato a buon fine.') ?>
                    <p><?= $this->translate('Il messaggio di errore che abbiamo ricevuto è: "').$this->message.'"' ?>
                    <p><?= $this->translate('Contattare l\'assistenza per maggiori informazioni')?></p>
                </div>

            </div>
            <!-- block-form -->
        <?php endif; ?>

        </div>
        <!-- content -->

    </div>
    <!-- main -->

    <!-- module-modal -->
    <div class="module-modal" style="height:2400px; display: none;">
        <!-- modal-overlay -->
        <div class="modal-overlay">
            <!-- module-pop-up -->
            <div class="module-pop-up" style="margin:180px auto;">

                <a class="btn-close"><i class="fa fa-close"></i></a>

                <!-- module-pop-up-content -->
                <div class="module-pop-up-content">

                    <!-- block-pop-up-generic-content -->
                    <div class="block-pop-up-generic-content">
                        <img src="<?= $this->basePath('images/patente-fac-simile.jpg'); ?>" alt="">
                        <p>
                            <?= $this->translate('5. Numero Patente<br>4. Data di rilascio<br>4c. Autorit&agrave; di rilascio<br>'); ?>
                        </p>
                    </div>
                    <!-- block-pop-up-generic-content -->

                </div>
                <!-- module-pop-up-content -->

            </div>
            <!-- module-pop-up -->
        </div>
        <!-- modal-overlay -->
    </div>
    <!-- module-modal -->

    <?
    $this->inlineScript()->appendScript(
        '$(document).ready(function() {
            $( "#driverLicenseReleaseDate" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
                maxDate: new Date(new Date().getFullYear(), 11, 31)
            });
        });
        $(document).ready(function() {
            $( "#driverLicenseExpire" ).datepicker({
                dateFormat: "dd-mm-yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "+0:+100",
                minDate: new Date(new Date().getFullYear(), 0, 1)
            });
        });'
    );
    ?>

    <script>
        if($('#driverLicenseForeign').is(":checked"))
            $('#self_declaretion').show();
        else
            $('#self_declaretion').hide();

        $('#driverLicenseForeign').change(function(){
            if($('#driverLicenseForeign').is(":checked"))
                $('#self_declaretion').show();
            else
                $('#self_declaretion').hide();
        });
    </script>
