<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'));

$this->headLink()
    ->appendStylesheet($this->basePath('css/overlay.css'))
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css?v=0.1'));

$privacyLink = $this->basePath('pdf/si/privacy.pdf');
$contractLink = $this->basePath('pdf/si/contract.pdf');

?>

<!-- main -->
<div id="main">
    <!-- module-section-bookmark -->
    <div class="module-section-bookmark yellow content-align-center">
        <h1 class="module-main-title"><?= $this->translate("Condivisione di auto elettriche rispettose dell'ambiente e convenienti per te"); ?></h1>
            <div style="display: inline-block;">
            <ul style="text-align: left; margin-top: 10px">
                <li><?= $this->translate("Auto disponibili vicino a te giorno e notte") ?></li>
                <li><?= $this->translate("I pacchetti partono da 0,10 € al minuto") ?></li>
            </ul>
        </div>
    </div>

    <div class="module-main-subtitle content-align-center">
        <p><?= $this->translate("Registrazione gratuita!") ?></p>
    </div>

    <!-- module-section-bookmark -->
    <script>//fbq('track', 'Lead');</script>

    <!-- module-wizard -->
    <!--<div class="module-wizard clearfix">
        <ul>
            <li class="active">1</li>
            <li>2</li>
            <li>3</li>
            <li class="last"><i class="icon-auto"></i></li>
        </ul>
    </div>-->
    <!-- module-wizard -->
    <br>

    <!-- content -->
    <div class="content">

        <?php
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
        ?>

        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Email'); ?></label>
                        <?php
                        $email = $this->form->get('user')->get('email');
                        echo $this->formElement($email);
                        echo $this->formElementErrors($email, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Password'); ?></label>
                        <?php
                        $password = $this->form->get('user')->get('password');
                        echo $this->formElement($password);
                        echo $this->formElementErrors($password, ['class' => 'errors']);
                        ?>
                    </p>
                    <label class="small-form"><?= $this->translate("min. 8 caratteri, una maiuscola e un numero") ?> </label>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p> <label><?= $this->translate("Luogo preferito"); ?></label>
                        <?php
                        $fleet = $this->form->get('user')->get('fleet');
                        echo $this->formElement($fleet);
                        echo $this->formElementErrors($fleet, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

            </div>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <?php $privacyCondition = $this->form->get('user')->get('privacyCondition'); ?>
                <div class="block-field w-4-4" style="text-align: <?= ($this->formElementErrors($privacyCondition)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">


                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($privacyCondition) ?>
                        <span class='control-indicator'
                              id="generalCondition1Text"><?= $privacyCondition->getLabel(); ?></span>
                    </label>
                    <?php echo $this->formElementErrors($privacyCondition, ['class' => 'errors']); ?>

                </div>
            </div>
            <!-- block-row-field -->
            <div class="block-wrapper-button content-align-center">
                <input type="submit" name="nextBtn" id="nextBtn" value="<?= $this->translate("CREA IL TUO ACCOUNT") ?>">
                <p style="font-size: 12px; font-weight: 300; color: #07BA50; padding-top: 15px;"><?= $this->translate("Cliccando sul tasto Iscriviti accetti") ?> <a style="font-weight: 400; color: #07BA50; text-decoration: underline;" target="_blank" href="<?= $privacyLink ?>"><?= $this->translate("l'Informativa sulla Privacy") ?></a> <?= $this->translate("e"); ?> <br>
                    <a style="font-weight: 400; color: #07BA50; text-decoration: underline;" target="_blank" href="<?= $contractLink; ?>"><?= $this->translate("le Condizioni Contrattuali di Sharengo") ?></a>. </p>
            </div>
            <br>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <?php $generalCondition2 = $this->form->get('user')->get('generalCondition2'); ?>

                <div class="block-field w-4-4" style="text-align: justify; <?= ($this->formElementErrors($generalCondition2)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">

                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($generalCondition2) ?>
                        <span class='control-indicator' id="generalCondition1Text">
                            <?= $this->translate("Il Cliente dopo aver letto i Contratti Generali condizioni ai sensi della Sezione 43c della legge n. 40/1964 Coll. Il codice civile dichiara che accetta e approva letteralmente le Condizioni generali e condizioni e assume consapevole della loro accettazione per concludere il contratto."); ?>
                        </span>
                    </label>
                    <?php echo $this->formElementErrors($generalCondition2, ['class' => 'errors']); ?>

                </div>
            </div>
            <!-- block-row-field -->

            </form>

        </div>
        <!-- block-form -->

    </div>
    <!-- content -->
    <!-- overlay -->
    <div id="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden"><?= $this->translate("Chiudi") ?></span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more"
                             style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;"><?= $this->translate("ATTENZIONE") ?></h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: justify; font-weight: 500;"><?= $this->translate("Domenica 11 Febbraio dalle ore 7:30 alle ore 13:30 una manutenzione programmata del sistema di verifica delle patenti potrebbe causare qualche rallentamento nella procedure di controllo. Le patenti verranno comunque convalidate entro luned&igrave; mattina.") ?></p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->
</div>
<!-- main -->

<?
$this->inlineScript()->appendScript(
    '$(document).ready(function() {
$( ".datepicker-date" ).datepicker({
dateFormat: "dd-mm-yy",
regional: "si",
changeMonth: true,
changeYear: true,
yearRange: "-100:+0",
maxDate: new Date(new Date().getFullYear(), 11, 31)
});
});'
);
?>

<script type="text/javascript">
    $(document).ready(function () {
        tryAPIGeolocation();

        overlay = $('#sng-overlay');

        var now = new Date(<? echo date("Y, n - 1, d, H, i, s"); ?> );
        var dateStart = new Date(2018, 1, 11, 7, 0, 0, 0);
        var dateEnd = new Date(2018, 1, 11, 14, 0, 0, 0);

        //        var dateStart = new Date(2016, 11, 2, 0, 0, 0, 0);
        //        var dateEnd = new Date(2016, 11, 4, 18, 0, 0, 0);

        if (now >= dateStart && now <= dateEnd) {
            overlay.css("visibility", "visible");
        }

        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(600, function () {
                overlay.remove();
            });
        });
    });

    /*signup favourite city draft*/

    function nearBy(fleetLat, fleetLon, userLat, userLon){
        return Math.abs(fleetLat-userLat)+Math.abs(fleetLon-userLon);
    }

    var apiGeolocationSuccess = function(position) {
        var arr = [];
        <?
            $arr = "";
            foreach($this->fleets as $f){
                echo "arr[".$f->getId()."] = nearBy(".$f->getLatitude().",".$f->getLongitude().",position.coords.latitude,position.coords.longitude);\n";
                $arr .= "arr[".$f->getId()."]";$arr .= ",";
            }
        ?>
        var i = arr.indexOf(Math.min(<?= $arr; ?>));
        $('select#fleet>option:eq('+i+')').attr('selected', true);
    };

    var tryAPIGeolocation = function() {
        jQuery.post( "https://www.googleapis.com/geolocation/v1/geolocate?key=<?= $this->googleMapsConfig['key'] ?>", function(success) {
            apiGeolocationSuccess({coords: {latitude: success.location.lat, longitude: success.location.lng}});
        })
            .fail(function(err) {
                console.log(err);
            });
    };

    $(function() {
        $('#registration-form').on('submit', function(e) {
            $("#nextBtn").attr("disabled", true);
            addLoader();
        });
    });

    var addLoader = function() {
        $("#outer").prepend("<div class=\"load-overlay\"><div>" + "<p><i class=\"fa fa-refresh fa-spin\">" + "<\/i><\/p><\/div><\/div>");
    };
    var removeLoader = function() {
        $("#outer > div.load-overlay").remove();
    };

</script>
