<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

 <!-- module-wizard -->
 <div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

     <div class="block-form-section content-align-center margin-bottom">
         <h2><i class="fa fa-thumbs-up"></i> <?= $this->message ?></h2>
     </div>

     <?php if ($this->enable_payment) { ?>
     <!--div class="margin-bottom">
        <h1><?= $this->translate('Completa l\'attivazione del servizio')?></h1>
        <p><?= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento di 10&euro; via PayPal.')?></p>
     </div>


     <!--div class="module-wrapper-button margin-bottom content-align-center">
         <a href="<?= $this->url('pay', array('email' => $this->email)) ?>" class="btn-link x-large ct2"><?= $this->translate('Esegui il pagamento di 10€'); ?> <i class="fa fa-plus-circle"></i></a>
     </div-->

    <div class="block-form-section content-align-center">
        <h2><?= $this->translate('GRAZIE'); ?></h2>
        <div style="color: black; line-height: 1.5; margin-bottom: 30px;"><?= $this->translate('Qualche giorno prima dell’attivazione del
servizio a Milano, prevista per lunedi 15 giugno,
ti verrà richiesto di completare la tua iscrizione
con il pagamento dei 10€ che comprende i primi 500 minuti
di utilizzazione dell’Equomobile.'); ?></div>
        <div style="color: black; line-height: 1.5; font-size: 1em;"><?= $this->translate('Il mancato pagamento dell’iscrizione entro il 14 giugno a mezzanotte
comporterà la perdita del diritto che hai maturato
ai 500 minuti gratuiti previsti con la promozione di lancio di SHARE’NGO'); ?></div>
    </div>

     <?php } ?>

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
               <!-- main -->