<!-- Facebook Conversion Code for registration Florence -->
<?php
$this->placeholder('facebook-pixel')->set('
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');

fbq(\'init\', \'423565347840059\');
fbq(\'track\', "PageView");
fbq(\'track\', \'CompleteRegistration\');</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=423565347840059&ev=PageView&noscript=1"
/></noscript>
');
?>
<script src="//onetag-sys.com/sync/a,63/2"></script>
<img src="https://secure.adnxs.com/px?id=878451&t=2" width="1" height="1" />
<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
    <h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

<!-- module-wizard -->
<div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

<!-- block-form -->
<div class="block-form w-3-4 auto-margin clearfix">

    <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i> <?= $this->message ?></h2>
    </div>

    <?php if ($this->enable_payment) { ?>
    <div class="margin-bottom">
        <h1><?= $this->translate('Completa l\'attivazione del servizio')?></h1>
        <br>
        <?php if ($this->needsDriversLicenseUpload){ ?>
            <p><?= $this->translate('Per verificare la validità della tua patente estera, è necessario caricare una copia della patente di guida e della carta di identità, entrambe fronte e retro. Puoi procedere subito '); ?>
            <a href="<?= $this->url('foreign-drivers-license', ['hash' => $this->hash]) ?>" target="_blank"><?= $this->translate('qui') ?></a>
            <?= $this->translate(', oppure farlo in secondo momento dalla tua area riservata. Finchè la validità della tua patente non sarà verificata, non potrai utilizzare il servizio di SHARE’NGO.')?>
            <p>
        <?php } else {?>
            <p><?= $this->translate('Controlla nelle tue mail se la verifica della tua patente ha dato esito positivo,<br>se così non fosse accedi all\'area riservata e verifica i tuoi dati prima di effettuare il pagamento.')?></p>
        <?php }?>
            <br>
        <?php if ($this->benefitsFromDiscountedSubscriptionAmount) { ?>
            <p><?= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento di ' . $this->subscriptionDiscountedAmount . '&euro; via Cartasi.')?></p>
        <?php } else { ?>
            <p><?= $this->translate('Per completare l\'attivazione del servizio, esegui il pagamento via Cartasi.')?></p>
        <?php } ?>
    </div>
            <br>
    <div class="module-wrapper-button margin-bottom content-align-center">
        <a href="<?= $this->url('cartasi/primo-pagamento', [], ['query' => ['customer' => $this->customerId]]) ?>" class="btn-link x-large ct2"><?= $this->translate('Esegui il pagamento'); ?> <i class="fa fa-plus-circle"></i></a>
    </div>

    <?php } ?>


</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
<!-- main -->
<script type="text/javascript">
    // Criteo section
    var email = "<?= $this->customerEmail;?>";
    var fleet = parseInt(<?= $this->customerFleetId;?>);
    var basket = [ { id: fleet, price: 1, quantity: 1 } ];
    criteoTrackTransaction(email, basket);
</script>

<?php
if($this->customerFleetId){
    echo '
<!-- Adform Tracking Code BEGIN -->
<script type="text/javascript">
    window._adftrack = Array.isArray(window._adftrack) ? window._adftrack : (window._adftrack ? [window._adftrack] : []);
    window._adftrack.push({
        pm: 1171594,
        divider: encodeURIComponent(\'|\'),
        pagename: encodeURIComponent(\'RD-PIXEL_SharenGo_MILANO_TYP\'),
        order : { 
             orderid: \'<insert order id value here>\'
        }
    });
    (function () { var s = document.createElement(\'script\'); s.type = \'text/javascript\'; s.async = true; s.src = \'https://track.adform.net/serving/scripts/trackpoint/async/\'; var x = document.getElementsByTagName(\'script\')[0]; x.parentNode.insertBefore(s, x); })();

</script>
<noscript>
    <p style="margin:0;padding:0;border:0;">
        <img src="https://track.adform.net/Serving/TrackPoint/?pm=1171594&ADFPageName=RD-PIXEL_SharenGo_MILANO_TYP&ADFdivider=|" width="1" height="1" alt="" />
    </p>
</noscript>
<!-- Adform Tracking Code END -->';
}
?>