<?php
    /*$this->headScript()
        ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
        ->appendFile($this->basePath('js/ui.datepicker-it.js'));
    $this->headLink()
        ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'));*/
?>

<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

 <!-- module-wizard -->
 <div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

     <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-car"></i> <?= $this->translate('Inserisci i dati della tua patente di guida'); ?></h2>
    </div>

    <?php
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
    ?>

        <!-- block-row-field -->
         <div class="block-row-field clearfix">

            <div class="block-field bw-f w-2-4">
                <p> <label><?= $this->translate('Numero patente'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                    <?php
                        $driverLicense = $this->form->get('driver')->get('driverLicense');
                        echo $this->formElement($driverLicense);
                        echo $this->formElementErrors($driverLicense);
                    ?>
                </p>
            </div>

        <div class="block-field bw-f w-2-4">
            <p>
                <label><?= $this->translate('Rilascio da autorit&agrave;'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
                <?php
                    $driverLicenseAuthority = $this->form->get('driver')->get('driverLicenseAuthority');
                    echo $this->formElement($driverLicenseAuthority);
                    echo $this->formElementErrors($driverLicenseAuthority);
                ?>
            </p>
        </div>

    </div>
    <!-- block-row-field -->

    <!-- block-row-field -->
    <div class="block-row-field clearfix">

     <div class="block-field bw-f w-2-4">
        <p> <label><?= $this->translate('Rilasciata il'); ?></label> <a href=""><i class="fa fa-info-circle"></i></a>
            <?php
                $driverLicenseReleaseDate = $this->form->get('driver')->get('driverLicenseReleaseDate');
                echo $this->formElement($driverLicenseReleaseDate);
                echo $this->formElementErrors($driverLicenseReleaseDate);
            ?>
        </p>
    </div>

    <div class="block-field bw-f w-2-4">
        <p> <label><?= $this->translate('Nome sulla patente'); ?></label>
            <?php
                $driverLicenseName = $this->form->get('driver')->get('driverLicenseName');
                echo $this->formElement($driverLicenseName);
                echo $this->formElementErrors($driverLicenseName);
            ?>
        </p>
    </div>

</div>
<!-- block-row-field -->

<!-- block-row-field -->
<div class="block-row-field clearfix">

 <div class="block-field bw-f w-2-4">
    <p> <label><?= $this->translate('Rilasciata (nazione)'); ?></label>
        <?php
            $driverLicenseCountry = $this->form->get('driver')->get('driverLicenseCountry');
            echo $this->formElement($driverLicenseCountry);
            echo $this->formElementErrors($driverLicenseCountry);
        ?>
    </p>
</div>

<div class="block-field bw-f w-2-4">
    <p> <label><?= $this->translate('Data di scadenza'); ?></label>
        <?php
            $driverLicenseExpire = $this->form->get('driver')->get('driverLicenseExpire');
            echo $this->formElement($driverLicenseExpire);
            echo $this->formElementErrors($driverLicenseExpire);
        ?>
    </p>
</div>

</div>
<!-- block-row-field -->

<div class="block-form-section content-align-center margin-bottom">
    <h2><i class="fa fa-folder-open"></i> <?= $this->translate('Categoria patente'); ?></h2>
</div>

<!-- block-row-field -->
<div class="block-row-field clearfix">

 <div class="block-field content-align-center bw-f w-4-4">
    <p>
        <?php
            $driverLicenseCategories = $this->form->get('driver')->get('driverLicenseCategories');
            foreach ($driverLicenseCategories->getValueOptions() as $key => $value): ?>
                <label class='control checkbox checkbox--patente'>
                    <input type='checkbox' name="<?php echo $driverLicenseCategories->getName() ?>" value="<?php echo $value; ?>"><span class='control-indicator'><?php echo $key; ?></span>
                </label>
            <?php endforeach; ?>
        <?php echo $this->formElementErrors($driverLicenseCategories, array('class' => 'error-sign-up')); ?>
        </div>
    </p>
</div>

</div>
<!-- block-row-field -->


<div class="block-wrapper-button content-align-center">
    <input type="submit" class="reset" name="" value="Indietro">
    <input type="submit" name="" value="Avanti">
</div>

</form>

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
               <!-- main -->

               <?php
    /*$this->inlineScript()->captureStart();
    echo <<<JS
        $(document).ready(function() {
            $( ".datepicker-date" ).datepicker({
                dateFormat: "dd/mm/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0"
            });
        });
JS;
    $this->inlineScript()->captureEnd();*/
?>
