<!-- module-section-bookmark -->
<div class="module-section-bookmark content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

 <!-- module-wizard -->
 <div class="module-wizard clearfix">
    <ul>
        <li class="active"><i class="fa fa-user"></i></li>
        <li class="active"><i class="fa fa-tachometer"></i></li>
        <li class="active"><i class="fa fa-flag-checkered"></i></li>
    </ul>
</div>
<!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

     <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i> <?= $this->translate('Registrazione completata con successo!'); ?></h2>
    </div>

    <!-- block-alert -->
    <div class="block-alert margin-bottom right">
     <h2 class="block-title"><i class="fa fa-check-circle"></i> <?= $this->translate('Attivazione account'); ?></h2>
     <p>
         <?= $this->translate('Controlla nella tua casella di posta e clicca sul link suggerito dalla mail inviata per ATTIVARE l\'account.'); ?>
     </p>
 </div>
 <!-- block-alert -->

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
               <!-- main -->