<div id="main">
    <!-- module-section-bookmark -->
    <div class="module-section-bookmark yellow content-align-center">
        <h1 class="module-main-title"><?= $this->translate("Iscrizione"); ?></h1>
    </div>
    <div class="content">
        <div class="block-form w-2-4 auto-margin clearfix">
            <div class="block-form-section content-align-center margin-bottom">
                <h2>
                    <i class="fa fa-warning"></i> <?= $this->translate("Servizio sospeso"); ?>
                </h2>
            </div>
        </div>
        <div class="block-form w-2-4 auto-margin clearfix">
            <div class="block-field bw-f w-4-4" style="text-align: justify">
                <label>
                    <?= $this->translate("Attenzione. Il servizio di iscrizione a Share'n Go è temporanemente sospeso. Ci scusiamo per il disagio."); ?>
                </label>
            </div>
        </div>
    </div>

</div>
<!-- main -->
