<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'));

$this->headLink()
    ->appendStylesheet($this->basePath('css/overlay.css'))
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css?v=0.1'));
?>

<!-- main -->
<div id="main">
    <!-- module-section-bookmark -->
    <div class="module-section-bookmark yellow content-align-center">
        <h1 class="module-main-title"><?= $this->translate("Il car sharing elettrico che non inquina"); ?></h1>
        <div style="display: inline-block;">
            <ul style="text-align: left; margin-top: 10px">
                <li><?= $this->translate("Solo auto elettriche, disponibili giorno e notte, vicino a te.") ?></li>
                <li><?= $this->translate("Parcheggi gratis nei posteggi pubblici e in quelli riservati ai residenti.") ?></li>
            </ul>
        </div>
    </div>

    <div class="module-main-subtitle content-align-center">
        <p><?= $this->translate("ISCRIVERTI NON TI COSTA NULLA!") ?></p>
    </div>
    <br>

    <!-- content -->
    <div class="content">

        <?php
        $this->form->prepare();
        echo $this->form()->openTag($this->form);
        ?>

        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <!-- block-row-field -->
            <div class="block-row-field clearfix">

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Email'); ?></label>
                        <?php
                        $email = $this->form->get('user')->get('email');
                        echo $this->formElement($email);
                        echo $this->formElementErrors($email, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p><label><?= $this->translate('Password'); ?></label>
                        <?php
                        $password = $this->form->get('user')->get('password');
                        echo $this->formElement($password);
                        echo $this->formElementErrors($password, ['class' => 'errors']);
                        ?>
                    </p>
                    <label class="small-form"><?= $this->translate("min. 8 caratteri, una maiuscola e un numero") ?> </label>
                </div>

                <div class="block-field bw-f w-1-3">
                    <p> <label><?= $this->translate("Citt&agrave; preferita"); ?></label>
                        <?php
                        $fleet = $this->form->get('user')->get('fleet');
                        echo $this->formElement($fleet);
                        echo $this->formElementErrors($fleet, ['class' => 'errors']);
                        ?>
                    </p>
                </div>

            </div>

            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <?php $privacyCondition = $this->form->get('user')->get('privacyCondition'); ?>
                <div class="block-field w-4-4" style="text-align: <?= ($this->formElementErrors($privacyCondition)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">
                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($privacyCondition) ?>
                        <span class='control-indicator' id="privacyConditionText" style="vertical-align: text-top;">
                            <?= $privacyCondition->getLabel(); ?>
                            <a href='<?= $this->basePath('pdf/sk/privacy.pdf'); ?>'>
                                <?= $this->translate("(clicca qui).") ?>
                            </a>
                        </span>
                    </label>
                    <?php echo $this->formElementErrors($privacyCondition, ['class' => 'errors']); ?>

                </div>
            </div>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <?php $newsletter = $this->form->get('user')->get('newsletter'); ?>
                <div class="block-field w-4-4" style="text-align: justify; <?= ($this->formElementErrors($newsletter)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">
                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($newsletter) ?>
                        <span class='control-indicator' id="newsletterText" style="vertical-align: text-top;"><?= $newsletter->getLabel(); ?></span>
                    </label>
                    <?php echo $this->formElementErrors($newsletter, ['class' => 'errors']); ?>
                </div>
            </div>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <?php $generalCondition1 = $this->form->get('user')->get('generalCondition1'); ?>
                <div class="block-field w-4-4" style="text-align: justify; <?= ($this->formElementErrors($generalCondition1)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">
                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($generalCondition1) ?>
                        <span class='control-indicator' id="generalCondition1Text" style="vertical-align: text-top;"><?= $generalCondition1->getLabel(); ?></span>
                    </label>
                    <?php echo $this->formElementErrors($generalCondition1, ['class' => 'errors']); ?>
                </div>
            </div>
            <!-- block-row-field -->
            <div class="block-wrapper-button content-align-center">
                <input type="submit" name="nextBtn" id="nextBtn" value="<?= $this->translate("CREA IL TUO ACCOUNT") ?>">
                <p style="font-size: 12px; font-weight: 300; color: #07BA50; padding-top: 15px;">
                    <?= $this->translate("Cliccando sul tasto accetti i Termini e le Condizioni contrattuali di Sharengo")?>
                </p>
            </div>
            <br>
            <!-- block-row-field -->
            <div class="block-row-field clearfix">
                <?php $generalCondition2 = $this->form->get('user')->get('generalCondition2'); ?>
                <div class="block-field w-4-4" style="text-align: justify; <?= ($this->formElementErrors($generalCondition2)) ? 'justify; border: solid 1px red; padding: 5px;' : '' ?>">
                    <label class='control checkbox small-form'>
                        <?php echo $this->formElement($generalCondition2) ?>
                        <span class='control-indicator' id="generalCondition2Text" style="vertical-align: text-top;"><?= $this->translate("Il Cliente dichiara, dopo aver preso conoscenza delle Condizioni generali di contratto sulla base del Codice civile, di accettare le Condizioni generali e di approvarle integralmente, ed è a conoscenza dell'accordo relativo alla conclusione del contratto.") ?></span>
                    </label>
                    <?php echo $this->formElementErrors($generalCondition2, ['class' => 'errors']); ?>
                </div>
            </div>

            </form>

        </div>
        <!-- block-form -->

    </div>
    <!-- content -->
    <!-- overlay -->
    <div id="sng-overlay" class="sng-overlay" style="visibility: hidden">
        <div class="table">
            <div class="cell">
                <div class="box" style="background:#fff;">
                    <a href="#" class="sng-overlay-close" title="Chiudi"><span class="hidden"><?= $this->translate("Chiudi") ?></span></a>
                    <div id="sng-overlay-content1">
                        <div class="content-more"
                             style="background-color:rgba(102, 102, 102, 0.40); background-image: none;">
                            <h3 style="background: #07ba50;color: #fff;"><?= $this->translate("ATTENZIONE") ?></h3>
                            <br>
                            <ul>
                                <p style="color:black;text-align: justify; font-weight: 500;"><?= $this->translate("Domenica 11 Febbraio dalle ore 7:30 alle ore 13:30 una manutenzione programmata del sistema di verifica delle patenti potrebbe causare qualche rallentamento nella procedure di controllo. Le patenti verranno comunque convalidate entro luned&igrave; mattina.") ?></p>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->

    <!-- overlay already signup -->
    <div id="sng-overlay" class="overlay-signup" style="visibility: hidden; background: rgba(0, 0, 0, 0.3);">
        <div class="table">
            <div class="cell">
                <div class="box" id="popup" style="background:#45ad4e !important; max-width: 800px; border-radius: 50px; padding-top: 10px; font-family: 'Open Sans', sans-serif;">
                    <div id="sng-overlay-content1">
                        <div class="content-more" style="background-image: none; text-align: left !important;">
                            <br>
                            <p align="right"><a onclick="closeSignup()" style="color:#fff"><b>[X] <?= $this->translate("Chiudi");?></b></a></p>
                            <h2 style="color:#fff;text-align: center; font-weight: 800;font-family: 'Open Sans', sans-serif"><?= $this->translate("Sei già iscritto!");?></h2>
                            <hr style="height:2px;border:none;color:#fff;background-color:#fff;">
                            <p style="color:#fff;text-align: center; font-weight: 800; font-family: 'Open Sans', sans-serif">
                                <br>
                                <?= $this->translate("Per completare l'inserimento dei tuoi dati clicca sopra su ACCEDI e fai LOGIN"); ?>
                            </p>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- overlay -->

</div>
<!-- main -->

<?php
$this->inlineScript()->appendScript(
    '$(document).ready(function() {
$( ".datepicker-date" ).datepicker({
dateFormat: "dd-mm-yy",
changeMonth: true,
changeYear: true,
yearRange: "-100:+0",
maxDate: new Date(new Date().getFullYear(), 11, 31)
});
});'
);
?>

<script type="text/javascript">
    $(document).ready(function () {
        tryAPIGeolocation();

        overlay = $('#sng-overlay');

        var now = new Date(<?php echo date("Y, n - 1, d, H, i, s"); ?> );
        var dateStart = new Date(2018, 1, 11, 7, 0, 0, 0);
        var dateEnd = new Date(2018, 1, 11, 14, 0, 0, 0);

        //        var dateStart = new Date(2016, 11, 2, 0, 0, 0, 0);
        //        var dateEnd = new Date(2016, 11, 4, 18, 0, 0, 0);

        if (now >= dateStart && now <= dateEnd) {
            overlay.css("visibility", "visible");
        }

        $(".sng-overlay-close").click(function (e) {
            e.preventDefault();
            overlay.fadeOut(600, function () {
                overlay.remove();
            });
        });
    });

    /*signup favourite city draft*/

    function nearBy(fleetLat, fleetLon, userLat, userLon){
        return Math.abs(fleetLat-userLat)+Math.abs(fleetLon-userLon);
    }

    var apiGeolocationSuccess = function(position) {
        var arr = [];
        <?php
        $arr = "";
        foreach($this->fleets as $f){
            echo "arr[".$f->getId()."] = nearBy(".$f->getLatitude().",".$f->getLongitude().",position.coords.latitude,position.coords.longitude);\n";
            $arr .= "arr[".$f->getId()."]";$arr .= ",";
        }
        ?>
        var i = arr.indexOf(Math.min(<?= $arr; ?>));
        $('select#fleet>option:eq('+i+')').attr('selected', true);
    };

    <?php // in case taxCode is already present
    if($this->formElementErrors($this->form->get('user')->get('email')) == "<ul><li>".$this->translate("Esiste già un utente con lo stesso indirizzo email")."</li></ul>"){?>
    overlay = $('.overlay-signup');
    overlay.css("visibility", "visible");
    <?php } ?>

    var tryAPIGeolocation = function() {
        jQuery.post( "https://www.googleapis.com/geolocation/v1/geolocate?key=<?= $this->googleMapsConfig['key'] ?>", function(success) {
            apiGeolocationSuccess({coords: {latitude: success.location.lat, longitude: success.location.lng}});
        })
            .fail(function(err) {
                console.log(err);
            });
    };

    $(function() {
        $('#registration-form').on('submit', function(e) {
            $("#nextBtn").attr("disabled", true);
            addLoader();
        });
    });

    var addLoader = function() {
        $("#outer").prepend("<div class=\"load-overlay\"><div>" + "<p><i class=\"fa fa-refresh fa-spin\">" + "</i></p></div></div>");
    };
    var removeLoader = function() {
        $("#outer > div.load-overlay").remove();
    };

    function closeSignup() {
        overlay = $('.overlay-signup');
        overlay.fadeOut(400, function () {
            overlay.css("visibility", "hidden");
            overlay.css("display","initial");
        });
    }

</script>
