<?php
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css?v=0.1'));
?>

<!-- main -->
<div id="main">
    <div class="module-section-bookmark yellow content-align-center" style="padding:20px 10px 20px 10px">
        <h1 class="module-main-title"><?= $this->translate("Iscrizione al servizio al momento non disponibile"); ?></h1>
    </div>
    <div style="display: inline-block; text-align: justify; color: #1c2329; font-size:1.2em; font-weight:700; padding: 10px 10px 0px 10px ">
        <?= $this->translate("Stiamo lavorando ad un nuovo ed innovativo servizio di mobilità elettrica e sostenibile che lanceremo a breve e di cui presto ti daremo notizia sul sito Sharengo, sull' App e sulle nostre pagine social.") ?>
    </div>
</div>
<!-- main -->
