<?php
$this->headScript()
    ->appendFile($this->basePath('js/jquery-ui-1.8.22.custom.min.js'))
    ->appendFile($this->basePath('js/ui.datepicker-sk.js'))
    ->appendFile($this->basePath('js/signupSK.js?v=4.2'));
$this->headLink()
    ->appendStylesheet($this->basePath('css/jquery-ui-1.8.22.custom.css'))
    ->appendStylesheet($this->basePath('css/signup.css?v=0.1'));
?>
<style>
    .module-section-bookmark.yellow {
        padding-bottom: 20px;
    }
</style>
<!-- module-section-bookmark -->
<div class="module-section-bookmark yellow content-align-center">
<h1 class="module-main-title"><?= $this->translate('Registrati'); ?></h1>
</div>
<!-- module-section-bookmark -->

<!-- main -->
<div id="main">

    <!-- module-wizard -->
    <div class="module-wizard clearfix">
        <ul>
            <li class="active">1</i></li>
            <li class="active">2</li>
            <li class=""><i class="icon-auto"></i></li>
        </ul>
    </div>
    <!-- module-wizard -->

<!-- content -->
<div class="content">

 <!-- block-form -->
 <div class="block-form w-3-4 auto-margin clearfix">

    <div class="block-form-section content-align-center margin-bottom">
        <h2><i class="fa fa-thumbs-up"></i><?= $this->translate('Registrazione completata con successo!'); ?></h2>
    </div>

    <!-- block-alert -->
    <div class="block-alert margin-bottom right">
        <h2 class="block-title"><i class="fa fa-check-circle"></i><?= $this->translate('Attivazione account'); ?></h2>
        <p>
            <?= $this->translate('Ora puoi accedere con i dati inseriti in fase di registrazione all\'app e alla tua area utente.'); ?><br/>
        </p>
    </div>
    <!-- block-alert -->

</div>
<!-- block-form -->

</div>
<!-- content -->

</div>
<!-- main -->