<!-- content -->
<div class="content">

    <div class="module-wizard clearfix"></div>

    <!-- block-form -->
    <div class="block-form w-3-4 auto-margin clearfix">

        <div class="content-align-center margin-bottom">
            <h1><?= $this->translate('Pagamento annullato o rifutato')?></h1>
            <p><?= $this->translate('La procedura di pagamento con Cartasi ha dato esito ').strtoupper($this->outcome) ?></p>
        </div>

    </div>
    <!-- block-form -->

</div>
<!-- content -->