<!-- content -->
<div class="content">

    <div class="module-wizard clearfix"></div>

    <?php if ($this->outcome == 'OK'): ?>
        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <div class="content-align-center margin-bottom">
                <h1><?= $this->translate('Attivazione completata')?></h1>
                <p><?= $this->translate('Ti confermiamo la ricezione del pagamento')?></p>
            </div>

        </div>
        <!-- block-form -->
    <?php else: ?>
        <!-- block-form -->
        <div class="block-form w-3-4 auto-margin clearfix">

            <div class="content-align-center margin-bottom">
                <h1><?= $this->translate('Si è verificato un problema' )?></h1>
                <p><?= $this->translate('Il pagamento non è andato a buon fine.') ?>
                <p><?= $this->translate('Il messaggio di errore che abbiamo ricevuto è: "').$this->message.'"' ?>
                <p><?= $this->translate('Contattare l\'assistenza per maggiori informazioni')?></p>
            </div>

        </div>
        <!-- block-form -->
    <?php endif; ?>

</div>
<!-- content -->