<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

            <h1 class="block-title"><?= $this->translate('Come funziona'); ?></h1>

            <br>
            <h2><?= $this->translate('Iscrizione  al servizio'); ?></h2>
            <p><?= $this->translate('Per Iscriversi al servizio di car sharing SHARE ‘NGO  basta andare all’home page del nostro sito '); ?><a href="<?= $this->url('home'); ?>">www.sharengo.it.</a><?= $this->translate(' Per avere il proprio Piano Tariffario Personale l’iscrizione deve avvenire attraverso il sito '); ?><a href="http://www.equomobili.it">www.equomobili.it</a><?= $this->translate('. Riceverai il PIN per l’uso del servizio via email. '); ?></p>

            <h2><?= $this->translate('Trovare  e prenotare in rete un’Equomobile quando ti serve'); ?></h2>
            <p><?= $this->translate('Per trovare un’Equombile  basta andare all’home page del nostro sito '); ?><a href="<?= $this->url('home'); ?>">www.sharengo.it.</a><?= $this->translate(' per visualizzare la posizione di ogni vettura disponibile (che potrai prenotare gratuitamente per 30 minuti se sei iscritto al servizio SHARE’NGO). Localizzazione e prenotazione funzionano esattamente nello stesso modo se avrai scaricato sul tuo smartphone IOS oppure Android la nostra APP (Share‘ngo – disponibile da Giugno su Apple Store e Google Play). Sulla mappa potrai visualizzare l’indirizzo di sosta, le condizioni e lo status di ogni Equomibile disponibile.'); ?></p>

            <h2><?= $this->translate('Usare un’Equomobile che hai trovato parcheggiata'); ?></h2>
            <p><?= $this->translate('Puoi verificare la disponibilità del veicolo molto semplicemente. Nella parte bassa a destra del parabrezza anteriore è localizzata una centralina a led colorati: la luce verde indica che il veicolo è disponibile per il noleggio con almeno il 20% di carica (cioè un’autonomia di almeno 20 km), la luce gialla che il veicolo è già stato prenotato, la luce blu che l’auto è attualmente in uso. Se la luce è rossa quell’Equomobile non è disponibile. '); ?><u><?= $this->translate('Per utilizzarla devi prima prenotarla'); ?></u><?= $this->translate(' (vedi sopra). La prenotazione è gratuita e dura 30 minuti.'); ?></p>

            <h2><?= $this->translate('Apertura e chiusura delle portiere'); ?></h2>
            <p><?= $this->translate('Se usi il tuo smartphone per gestire il servizio (sia attraverso la APP che sul sito responsive '); ?><a href="<?= $this->url('home'); ?>">www.sharengo.it.</a>)<?= $this->translate(' hai mezz’ora di tempo per arrivare alla macchina e vedere comparire automaticamente sul tuo telefono il pulsante ‘’apri porta’’.
            All’avvio del servizio a Milano, il 15 giugno, saranno disponibili anche un '); ?><u><?= $this->translate('numero limitato'); ?></u><?= $this->translate(' di CARD per chi dichiarasse in area riservata di NON possedere uno smartphone, che invieremo all’indirizzo indicato in registrazione.  Il funzionamento della Card per l’apertura delle porte è semplice e intuitivo: dovrà essere accostata alla centralina a led colorati posta dietro il parabrezza anteriore e le porte si apriranno.'); ?></p>

            <h2><?= $this->translate('Status Veicolo'); ?></h2>
            <p><?= $this->translate('Quando accederai all’interno del veicolo prenotato, ti verrà chiesta dal display di bordo di confermare le condizioni del veicolo. Potrai indicare se presenta danni e il livello di pulizia del mezzo (sia interna che esterna) che hai riscontrato. Questo procedimento ci aiuta a mantenere le Equomobili sempre nelle migliori condizioni possibili.'); ?></p>

            <h2><?= $this->translate('Inizio del Noleggio'); ?></h2>
            <p><?= $this->translate('Dopo il controllo del veicolo ti verrà chiesto il tuo PIN da digitare sullo schermo del computer di bordo (il PIN  ti è stato inviato via email dopo la registrazione). Una volta inserito il codice PIN  il noleggio avrà inizio. Sul display di bordo è possibile selezionare la lingua italiana o quella inglese.
            ATTENZIONE! '); ?><u><?= $this->translate('La chiave dell’Equombile non è estraibile'); ?></u><?= $this->translate(' e resta sempre a bordo.'); ?></p>

            <h2><?= $this->translate('Avanti, folle, retromarcia'); ?></h2>
            <p><?= $this->translate("Con la stessa logica di una vettura con il cambio automatico, sulle Equomobili trovi solo tre pulsanti, appena sotto il display: 'R' indica la retromarcia, 'D' è la marcia avanti o 'drive' ’N’ la posizione di folle. Girata la chiave sotto il volante (che è sempre inserita) per  partire basta schiacciare il pulsante D o R e fare la manovra normale di uscita dal parcheggio, che è facilitata dal servosterzo. Durante la corsa per passare da 'drive' a 'retromarcia', o viceversa, è necessario passare per la posizione N. Alla fine del noleggio l’auto deve essere obbligatoriamente lasciata in posizione N. Prima della partenza accertati che il pulsante rosso di sicurezza posto tra i due sedili NON sia inserito, in tal caso tiralo su (serve solo in casi di emergenza a spegnere il motore)."); ?></p>

            <h2><?= $this->translate('Fine noleggio'); ?></h2>
            <p><?= $this->translate("Per terminare la sessione di noleggio è necessario selezionare l’opzione corrispondente sul display di bordo e seguire le istruzioni per lo spegnimento della vettura. Lo ripetiamo: la chiave non è estraibile e deve rimanere inserita nel cruscotto. Ricorda che l’auto deve essere lasciata con la marcia 'N' inserita e la leva del freno a mano tirata su. Il costo della sessione di noleggio verrà automaticamente addebitato sulla carta di credito inserita al momento della registrazione."); ?></p>

            <h2><?= $this->translate('Area operativa  e chilometraggio illimitato'); ?></h2>
            <p><?= $this->translate('Il servizio Share’nGo è operativo nella zona di Milano. E’ possibile uscire dall’area della città (confini comunali),  ma non sarà possibile chiudere la sessione di noleggio al di fuori di essa. Fino a che non riporterai l’auto all’interno dellarea operativa e chiuderai la corsa, pagherai per l’utilizzazione e la sosta dell’Equomobile in relazione al tuo Piano Tariffario Personale o in base alle Tariffe Nominali se hai preferito non averlo. Le corse di SHARE ‘NGO sono sempre a chilometraggio illimitato.'); ?></p>

            <h2><?= $this->translate('Coperture assicurative'); ?></h2>
            <p><?= $this->translate('Sui nostri veicoli è garantita una copertura RC fino a 10.000.000 €. Le macchine sono coperte da polizza Kasko (con franchigia di 500 €) e assicurazione Furto e Incendio, atti vandalici ed eventi atmosferici. Il Conducente è assicurato per infortuni (PAI) per un massimale di 50.000 €.'); ?></p>

            <h2><?= $this->translate('Bambini a bordo'); ?></h2>
            <p><?= $this->translate('Le Equomobili sono dotate di cinture di sicurezza omologate e quindi NON si applica l’art 172 del codice della strada che vieta il trasporto di minori di anni 3 sui veicoli a motore che ne siano sprovvisti (serve ovviamente il seggiolino omologato). Non avendo Airbag inoltre NON si applicano le limitazioni a portare i minori sul sedile del passeggero purchè il seggiolino di sicurezza sia rivolto all’indietro.'); ?></p>

            <h2><?= $this->translate('Pagamenti e fatturazione del servizio'); ?></h2>
            <p><?= $this->translate('I noleggi Share‘ngo sono pagabili con carta di credito e anche carta prepagata. Ad ogni corsa corrisponde una fattura che puoi scaricare quando vuoi nell’Area Riservata. Sempre in area riservata puoi controllare e aggiornare il tuo Piano Tariffario Personale e vedere quanti minuti gratuiti ti sono stati accreditati con la registrazione e quanti ne hai consumati. I noleggi nel giorno del tuo compleanno sono gratuiti e gratuite sono le corse per le donne di notte, dall’1 alle 6 del mattino.'); ?></p>

            <h2><?= $this->translate('Regolamento e condizioni di utilizzazione'); ?></h2>
            <p><?= $this->translate('Sono pubblicati sul nostro sito e inviati via email a tutti i registrati al servizio'); ?></p>

            <h2><?= $this->translate('Tariffe nominali e penali'); ?></h2>
            <p><?= $this->translate('Sono pubblicati sul nostro sito e inviati via email a tutti i registrati al servizio'); ?></p>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->