<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

            <h1 class="block-title">Guida al servizio</h1>

            <h1><u>Come utilizzare Share'nGo</u></h1>
            <br>
            <h2>Trovare un mezzo Share'nGo</h2>
            <p>Per visualizzare la posizione di ogni mezzo Share'nGo attivo &egrave sufficiente scaricare sul tuo smartphone la nostra APP (Sharengo).
            Sulla mappa potrai visualizzare l'indirizzo, le condizioni e lo status di ogni mezzo Share'nGo (attivo) in qualsiasi momento.</p>

            <h2>Disponibilit&agrave veicolo</h2>
            <p>Verificare la disponibilit&agrave del veicolo &egrave molto semplice. Basta infatti controllare il colore della luce sul lettore Smart Card posto sul parabrezza.
            La luce verde indica che il veicolo &egrave disponibile per il noleggio, la luce gialla che il veicolo &egrave gi&agrave stato prenotato.
            La luce blu indica che l'auto &egrave attualmente in uso.
            Infine la luce rossa indica la NON disponibilit&agrave del veicolo.</p>

            <h2>Prenotazione</h2>
            <p>Puoi noleggiare un veicolo tramite l'APP del tuo smartphone.</p>

            <h2>Apertura / Chiusura portiere</h2>
            <p>Una volta effettuata la prenotazione e passata la card sul lettore posto sul parabrezza, le portiere si sbloccheranno ed avrai un massimo di 2 minuti per accedere al veicolo.
            Esaurito quel tempo, dovrai ripetere la procedura da capo.</p>

            <h2>Status Veicolo</h2>
            <p>Quando accederai all'interno del veicolo prenotato, ti verr&agrave chiesta una descrizione delle condizioni del veicolo.
            Dovrai indicare se presenta danni (che magari non vi erano in precedenza) ed il livello di pulizia del mezzo (sia interna che esterna).
            Il simbolo rosso indica un'auto sporca, il giallo un valore nella media ed il verde simboleggia un'auto pulita.
            Questo procedimento ci aiuta a mantenere le auto Share'nGo sempre in ottime condizioni, cos&igrave; che risultino gradite ai nostri clienti.</p>

            <h2>Inizio Noleggio</h2>
            <p>Dopo il controllo del veicolo ti verr&agrave chiesto un PIN da inserire (concordato al momento della registrazione).
            Una volta inserito (sul display all'interno del veicolo) il codice PIN, il noleggio avr&agrave inizio.</p>

            <h2>Lingua</h2>
            <p>E' possibile selezionare la lingua all'avvio del display. Le opzioni disponibili sono 'Italiano' e 'Inglese'.</p>

            <h2>Navigatore</h2>
            <p>Per selezionare il navigatore &egrave sufficiente cliccare sull'icona corrispondente della schermata del display.</p>

            <h2>Cambio Manuale</h2>
            <p>Il cambio delle vetture Share'nGo consiste nei tre pulsanti posti appena sotto il display. La 'N' sta ad indicare la marcia 'neutral', la 'R' indica la retromarcia mentre la 'D' &egrave la marcia 'drive'.
            Per muoversi con il veicolo sar&agrave sufficiente premere 'drive'.
            Per passare da 'drive' a 'retromarcia' &egrave necessario prima premere 'neutral' e successivamente premere la 'R' (retromarcia).
            Alla fine del noleggio l'auto deve essere obbligatoriamente lasciata con la marcia 'neutral' impostata.
            Prima della partenza accertati che il pulsante rosso posto tra i due sedili NON sia inserito, in tal caso tiralo su.</p>

            <h2>Fine noleggio</h2>
            <p>Per terminare la sessione di noleggio &egrave necessario selezionare l'opzione corrispondente sul display di bordo e seguire le istruzioni per lo spegnimento della vettura.
            Ricorda che l'auto deve essere lasciata con la marcia 'N' inserita e la leva del freno a mano tirata su.
            Il costo della sessione verr&agrave automaticamente addebitato sulla carta di credito inserita al momento della registrazione.</p>

            <h1><u>Regolamento</u></h1>
            <br>
            <h2>Area operativa</h2>
            <p>Il servizio Share'nGo &egrave operativo nella zona di Milano. E' possibile uscire dall'area della citt&agrave, ma non sar&agrave possibile chiudere la sessione di noleggio al di fuori di essa.
            Tutti i costi aggiuntivi di tempo (fino a che non riporter&agrave l'auto all'interno dell'area operativa) saranno a carico del cliente.</p>

            <h2>Condizioni di risoluzione contratto</h2>
            <p>L'utente deve rispettare le normali leggi del codice stradale ed, inoltre, attenersi alle seguenti normative :
            <br>- E' vietato il trasporto di oggetti e/o persone a scopo di lucro.
            <br>- E' vietato l'uso dell'auto Share'nGo per il traino di altri mezzi.
            <br>- E' vietato l'uso del veicolo per prove automobilistiche, lezioni di guida e per il trasporto di persone a scopo di lucro.
            <br>- E' vietato condurre l'auto (o permettere ad altri di farlo) sotto effetto di stupefacenti, alcol, narcotici e/o qualunque sostanza in grado di menomare le capacit&agrave di chi guida.
            <br>- E' vietato prender parte a competizioni e/o prove di velocit&agrave e/o abilit&agrave di guida.
            <br>- E' vietato trasportare, all'interno del veicolo, materiali infiammabili, velenosi o in generale pericolosi, in quantità superiori a quelle consentite per uso casalingo.
            <br>- E' vietato trasportare oggetti che, con la loro forma e/o dimensione, potrebbero danneggiare il veicolo e ridurne la sicurezza.
            <br>- E' vietato fumare all'interno dei veicoli Share'nGo.
            <br>- E' vietato trasportare neonati al di fuori delle norme del Codice della strada.
            <br>- E' vietato utilizzare l'auto per qualunque scopo al di fuori della legge.
            <br>- E' vietato il trasporto di animali all'interno dell'auto.
            <br>- E' vietato sporcare il veicolo e lasciarvi all'interno qualsiasi forma di rifiuto.
            <br>- E' vietato rimuovere dal veicolo parti o oggetti facenti parte dell'equipaggiamento della vettura stessa.
            <br>- E' vietato occupare il veicolo con più di due persone.
            <br>- E' vietato effettuare riparazioni o modifiche di alcun genere, sul veicolo, di propria iniziativa
            <br>- E' vietato utilizzare l'auto come persona che abbia fornito informazioni personali fittizie (identit&agrave, data di nascita, indirizzo, etcetera...).

            <br><br>La violazione di una delle precedenti normative comporter&agrave la risoluzione del contratto ed il risarcimento finanziario corrispondente alla/alle infrazione/i commessa/e.</p>

            <h1><u>Download Utili</u></h1>
            <br>
            <a href="<?= $this->basePath('pdf/Informativa_privacy.pdf'); ?>">Informativa sulla Privacy</a>
            <br>
            <a href="<?= $this->basePath('pdf/Regolamento_Sharengo.pdf'); ?>">Regolamento</a>
            <br>
            <br>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->