<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

        <h1 class="block-title"><?= $this->translate('Cosa &egrave Share\'nGo?')?></h1>

        <br><br>
        <p><?= $this->translate('<strong>Share\'nGo</strong> &egrave; un servizio di car sharing che offre la possibilit&agrave, a tutti coloro che non hanno un mezzo proprio, di spostarsi senza problemi nel centro-citt&agrave. Utilizzare Share\'nGo &egrave semplice: basta prenotare un veicolo (dal web o con il tuo smartphone), e poi sei libero di guidare. Paghi il tempo che passi alla guida. In pi&ugrave la nostra Profilazione ti fa pagare meno con l\'aumentare dell\'utilizzo del veicolo.')?>
        <br><u><?= $this->translate('Pi&ugrave guidi, meno paghi.')?></u>
        <br><br>
        <?= $this->translate('I veicoli Share\'nGo funzionano con la corrente elettrica, quindi sono COMPLETAMENTE ecologici e facili da guidare. Sono disponibili anche varie funzionalit&agrave che potrebbero servirti, quali navigatore, radio e molto altro.')?>
        <br>
        <?= $this->translate('Per qualsiasi informazione, infine, il nostro centro assistenza &egrave sempre disponibile al numero 0586 1975772.')?>
        <br><br>
        <strong><?= $this->translate('Share\'nGo, the new mobility.')?></strong></p>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->