<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- block-main-article -->
        <article class="block-main-article padding-top clearfix">

            <img src="<?= $this->basePath('img/nrm-img.jpg'); ?>" class="alignleft" alt="" >

            <h1 class="block-title"><?= $this->translate('Titolo della pagina'); ?></h1>

            <p>
                <?= $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec lorem pharetra, blandit sapien quis, sagittis mauris. Quisque efficitur tincidunt imperdiet. Ut et magna odio. Suspendisse at dui eu leo maximus tempus ut nec urna. Morbi nec pellentesque ipsum. Nunc nunc ex, dictum in tincidunt at, volutpat sit amet ante. Duis sagittis felis eu ligula sagittis, non vestibulum ipsum viverra. Curabitur eu tellus dictum, cursus mauris vel, interdum sapien. Cras in dapibus nibh. Integer finibus ac felis ac tincidunt.');
                ?>
            </p>

            <p>
                <?= $this->translate('Integer pulvinar congue tincidunt. Proin eget libero ipsum. Nunc auctor enim imperdiet lorem volutpat, feugiat efficitur arcu venenatis. In viverra, nunc ut pretium convallis, nisl nunc accumsan nunc, sed iaculis mi diam id felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc vel volutpat est. Proin dictum varius lacus, nec commodo elit ornare eu. Proin molestie velit nec enim fringilla, at viverra est maximus. Nulla sed sapien rutrum, tincidunt felis sed, vehicula libero. Nullam ac est sagittis, facilisis tortor sit amet, viverra est.');
                ?>
            </p>

            <img src="<?= $this->basePath('img/nrm-img.jpg'); ?>" class="aligncenter" alt="" >

            <p>
                <?= $this->translate('Praesent blandit odio eu dolor laoreet, vel pellentesque erat volutpat. Suspendisse vulputate eros mauris, vitae congue dui rhoncus eu. Proin a arcu mattis, eleifend mi at, facilisis libero. Vestibulum vitae risus consectetur, tincidunt enim vel, viverra lectus. Nam et nulla eget magna imperdiet scelerisque. Suspendisse vitae dolor id nibh mollis rhoncus quis eget mauris. Morbi tincidunt quis sapien a molestie. Quisque vitae cursus orci. Duis facilisis porta sem feugiat ultrices. Fusce efficitur massa nisl, ac cursus velit fringilla et.');
                ?>
            </p>

            <img src="<?= $this->basePath('img/nrm-img.jpg'); ?>" class="alignright" alt="" >


            <p>
                <?= $this->translate('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec lorem pharetra, blandit sapien quis, sagittis mauris. Quisque efficitur tincidunt imperdiet. Ut et magna odio. Suspendisse at dui eu leo maximus tempus ut nec urna. Morbi nec pellentesque ipsum. Nunc nunc ex, dictum in tincidunt at, volutpat sit amet ante. Duis sagittis felis eu ligula sagittis, non vestibulum ipsum viverra. Curabitur eu tellus dictum, cursus mauris vel, interdum sapien. Cras in dapibus nibh. Integer finibus ac felis ac tincidunt.');
                ?>
            </p>

        </article>
        <!-- block-main-article -->

    </div>
    <!-- content -->

</div>
<!-- main -->