<?php
    // get data
    $customer = $this->customer;
    $redirect = $this->redirect;
    $call = $this->call;
    $token = $this->token;

    // parse data
    $name = (!is_null($customer)) ? ucwords(strtolower($customer->getName() . ' ' . $customer->getSurname())) : '';
    if($redirect){
?>
    <style>
        div.load-overlay {
            width: 100%;
            height: 100%;
            background-color: white;
            position: absolute;
            z-index: 9999
        }

        div.load-overlay > div {
            text-align: center;
            width: 100%;
            margin: 0 auto;
            height: 100%;
            display: table;
            table-layout: fixed
        }

        div.load-overlay > div > p {
            display: table-cell;
            vertical-align: middle;
            text-align: center;
        }

        div.load-overlay > div > p > i {
            font-size: 100px;
            color: #43a34c;
            z-index: 2
        }
        form {
            visibility: hidden;
            display: none;
        }
    </style>
        <form action="<?=$this->url('zfcuser/login') ?>" method="post">
            <input type="hidden" name="identity" value="sharengo@sharengo.it">
            <input type="hidden" name="credential" value="123456789">
            <input type="hidden" name="crawler" value="<?= $token[0] . "-" . $token[1] ?>">

            <input type="submit" name="" id="send">
        </form>
    <script>
        var addLoader = function() {
            $("body").prepend("<div class=\"load-overlay\"><div>" + "<p><i class=\"fa fa-refresh fa-spin\">" + "</i></p></div></div>");
        };
        addLoader();
        $('#send').click();
    </script>
<?php } ?>

<style>
    body {background: #efefef; color: #1c2329;}
</style>
<!-- main -->
<div id="main" class="detect-window-height">

    <!-- module-wrapper-app -->
    <div class="module-wrapper-app">

        <!-- module-column-app sx -->

        <!-- module-column-app dx -->
        <div class="module-column-app side-dx">

            <div class="module-heading-app">
                <h1 class="module-main-title" style="text-align: center; padding-left: unset !important"><? echo ($redirect) ? $this->translate('Caricamento') : $this->translate('Contattare l\'assistenza'); ?></h1>
            </div>

            <div class="module-column-app-content clearfix">
                <div class="module-sharing-resmume padding-top">
                    <br>
                    <!-- Description -->
                    <div>
                        <p><?= $this->translate("Ciao") . " " . $name ?>,</p><br>
                        <p><?= $this->translate("Il tuo profilo risulta disattivato, si prega di contattare il Servizio Clienti per essere riabilitato.");?></p>
                        <br>
                        <p><i class="fa fa-envelope" aria-hidden="true"></i> <a href="tel:05861863183">0586 1863183</a></p><br>
                        <p><i class="fa fa-phone" aria-hidden="true"></i> <a href="mailto:servizioclienti@sharengo.eu">servizioclienti@sharengo.eu</a></p>


                </div>
            </div>

            <!-- module-column-app-content -->

        </div>
        <!-- module-column-app dx -->

    </div>
    <!-- module-wrapper-app -->

</div>
<!-- main -->

