<head>
    <script type="text/javascript" src="/eq-sharing/application/js/jquery.1.11.3.min.js"></script>
    <link href="/eq-sharing/application/css/bootstrap.css" rel="stylesheet">
    <script type="text/javascript" src="/eq-sharing/application/js/bootstrap.js"></script>
    <link href="/eq-sharing/application/css/style.css" rel="stylesheet">
</head>

<body class="bg-grey">
    <div class="container-fluid lato-bold">
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-5 col-sm-push-7 text-center">
                <p class="white strong">
                    <span>Sei socio di</span>
                    <span class="desk-block desk-inline">EQ SHARING?</span>
                </p>
                <p class="yellow">
                    <span class="strong desk-block">Con  un click e 1 euro; </span>
                    <span class="strong desk-block">passi a SHARE'NGO </span>
                    <span class="semistrong">con 100 minuti gratis</span>
                </p>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-desk">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-1.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-7 col-sm-pull-5 img-mobile">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-3.jpg" class="img-responsive"/>
            </div>
        </div>
        <div class="col-sm-12 bg-grey">
            <div class="col-sm-7 img-desk">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-2.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-7 img-mobile">
                <img src="/eq-sharing/application/images/sharengo-car-sharing-equomobili-4.jpg" class="img-responsive"/>
            </div>
            <div class="col-sm-5 text-center p-top-5">
                <p class="white smaller">Dal 15 settembre SHARE'NGO subentra ad EQ SHARING nella gestione del servizio di car sharing elettrico delle Isole Digitali con oltre 300 quadricicli ZD ad alte prestazioni (80 kmh, 120 km di autonomia).</p>
                <p class="yellow semistrong">
                    <a href="http://www.equomobili.it/">
                        <span>Registrati entro il 30/9</span>
                        <span>a SHARE'NGO su</span>
                        <span class="desk-block">www.equomobili.it</span>
                    </a>
                        <span>con il CODICE PROMO</span>
                </p>
                <a href="http://www.equomobili.it/">
                    <button class="semistrong">EQZD</button>
                </a>
                <p class="white semistrong">L'ISCRIZIONE AL SERVIZIO E I PRIMI 100 MINUTI TI COSTERANNO SOLO 1 EURO!</p>
            </div>

        </div>
    </div>
</body>
