<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- module-list-archive -->
        <section class="module-list-archive margin-top">
            <h1 class="module-main-title"><?= $this->translate('F.A.Q.'); ?></h1>
            
            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come posso registrarmi?'); ?></a></h1>

                <p>
                    <?= $this->translate('Registrarsi a Share\'nGo &egrave molto semplice. Puoi effettuare la registrazione dal sito www.sharengo.it o dall\'APP. Ricorda che per poterti registrare a Share\'nGo devi essere maggiorenne, in possesso di patente di guida valida almeno da un anno ed avere una carta di credito.');?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come faccio a trovare una macchina Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('E\' molto semplice. Puoi scaricare l\'APP (che visualizza in tempo reale la posizione di tutte le macchine attive) oppure puoi guardare sul sito (www.sharengo.it).'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quanto costa il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Il servizio Share\'nGo ha un costo basilare di 0,28 &euro; al minuto. Grazie, per&ograve, al nostro sistema di Profilazione il costo del servizio potrebbe calare con l\'aumentare del tuo utilizzo di Share\'nGo. In sostanza, pi&ugrave usi Share\'nGo, meno paghi.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Dove lascio l\'auto dopo il noleggio?'); ?></a></h1>

                <p>
                    <?= $this->translate('Puoi parcheggiare la macchina Share\'nGo dovunque sia possibile parcheggiare un normale mezzo a quattro ruote. Non &egrave, quindi, necessario riportare l\'auto nel punto dove l\'hai ritirata. In caso l’auto venga parcheggiata nei pressi di un punto di ricarica ti verrà riconosciuto un bonus.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come pago il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Il costo di ogni noleggio ti verr&agrave addebitato automaticamente, alla fine della corsa, sulla carta di credito che hai inserito al momento della registrazione. Inoltre ti verr&agrave inviata per mail una copia della fattura riguardante la corsa.');
                    ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Posso prestare l\'auto a qualcuno?'); ?></a></h1>

                <p>
                    <?= $this->translate('Assolutamente no. L\'unica persona autorizzata a guidare il mezzo Share\'nGo &egrave colui che ha firmato il contratto e prenotato il mezzo stesso. In nessun caso il guidatore deve differire da tale persona.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Non trovo l\'app per il mio telefono'); ?></a></h1>

                <p>
                    <?= $this->translate('Le app per smartphone saranno disponibili da metà Giugno, prima in versione HTML e successivamente in versione nativa. Continua a controllare il sito per sapere quando sarà disponibile.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Se mi sono già registrato SENZA usufruire dello sconto EQUOMOBILI?'); ?></a></h1>

                <p>
                    <?= $this->translate('Se hai fatto la registrazione tradizionale sul sito www.sharengo.it senza usufruire dello sconto con la profilazione offerta da <a href="http://www.equomobili.it">www.equomobili.it</a>, puoi andare sul sito <a href="http://www.equomobili.it">www.equomobili.it</a> ed inserire nome e indirizzo email forniti in fase di registrazione su www.sharengo.it, per aggiungere al tuo profilo lo sconto. Un messaggio ti confermerà il buon esito dell’operazione..'); ?>
                </p>

            </article>
            <!-- block-item-post -->

        </section>
        <!-- module-list-archive -->

    </div>
    <!-- content -->

</div>
<!-- main -->