<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- module-list-archive -->
        <section class="module-list-archive margin-top">
            <h1 class="module-main-title"><?= $this->translate('F.A.Q.'); ?></h1>
            
            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Dove è attivo il servizio SHARE\'NGO?'); ?></a></h1>

                <p>
                    <?= $this->translate('Dal 22 giugno è attivo a Milano il servizio di car sharing a flusso libero, con le nostre Equomobili elettriche. Le iscrizioni al servizio sono aperte su <a href="http://www.equomobili.it">www.equomobili.it</a><br>Dal 1° maggio inoltre 10 veicoli SHARE\'NGO sono disponibili c/o la stazione delle Ferrovie Nord di Busto Arsizio e possono essere prenotate telefonando al n 370.3325086. Gli orari per il ritiro e la consegna sono 7.30-10.30 oppure 17.00-19.00 tutti i giorni della settimana.');?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Perché Share\'ngo è diverso dagli altri?'); ?></a></h1>

                <p>
                    <?= $this->translate('Le nostre sono macchine elettriche, a impatto zero. Zero CO2, Zero PMI, Zero Rumore. Non ti devi preoccupare della ricarica e le tariffe sono variabili perché dipendono dal tuo bisogno di mobilità a 4 ruote (più nei hai bisogno meno costano!). I nostri noleggi sono sempre a KM illimitato e  <u>sono gratuiti per le donne di notte dall’1.00 alle 6.00 del mattino</u>. E diversissima è la  community degli equomobili che raccoglie gli utenti di SHARE\'NGO. Scoprila sui social più importanti.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quanto costa il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('SHARE\'NGO ha introdotto, primi al mondo, un sistema di prezzi variabili che dipendono dal bisogno individuale di mobilità e che premia i comportamenti orientati alla condivisione. La tariffa base di 0,28 € al minuto è quindi solo nominale. Quella effettiva può  essere inferiore del 50%. Per scoprire in 4 click "quello che ti spetta" basta seguire la profilazione su <a href="http://www.equomobili.it">www.equomobili.it</a> e poi completare la registrazione.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come posso registrarmi?'); ?></a></h1>

                <p>
                    <?= $this->translate('Per registrarsi  al servizio di car sharing operativo a Milano dal 22 Giugno basta andare su <a href="http://www.equomobili.it">www.equomobili.it</a> oppure su <a href="http://www.sharengo.it">www.sharengo.it</a>. Prima della registrazione è proposta una profilazione del bisogno di mobilità che determina uno sconto % sulle tariffe nominali e quindi un piano tariffario personale. Per poterti registrare a Share\'nGo e utilizzare il servizio devi essere
                    maggiorenne, in possesso di patente di guida valida da almeno un anno ed avere una carta di credito anche prepagata.<br>Per registrarsi al servizio dislocato di Busto Arsizio basta andare allo sportello in orario di ufficio.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quando saranno disponibili le APP per il mio smartphone?'); ?></a></h1>

                <p>
                    <?= $this->translate('Per utilizzare le macchine di SHARE’NGO con lo smartphone basta andare su mobile.sharengo.it (senza www). Dalla applicazione è possibile localizzare e prenotare un’auto sulla mappa per 30 minuti e aprire echiudere le porte. Una volta a bordo il controllo sulla corsa lo gestisce la applicazione di bordo (inserimento PIN, navigazione, messa in sosta, termine corsa…). '); ?>
                    <?= $this->translate('La nostra App è adesso scaricabile su Google Play al nome Sharengo e a brevissimo anche su Apple Store.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come faccio a trovare una macchina Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Puoi cercarla su mobile.sharengo.it e prenotarla. I primi 30 minuti di prenotazione sono sempre gratuiti. Da Luglio la stessa funzione potrai gestirla con le APP . Se hai una CARD APRIPORTA di SHARE’NGO (che puoi richiedere in area riservata su www.sharengo.it ) e trovi per strada una macchina in status ‘’LIBERA’’ puoi semplicemente aprire le porte con la card e avviare la tua corsa. '); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come faccio a usare una macchina Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Le nostre macchine sono facilissime da usare e parcheggiare anche grazie al cambio automatico, il servosterzo, il servofreno, un ridotto raggio di sterzo e un limitato ingombro a terra. Si impara in pochi minuti ad utilizzarla ma per le prime volte puoi fare affidamento sulla'); ?> <a href="<?= $this->basePath('pdf/Come_si_usa_un_equomobile.pdf'); ?>">‘’<?= $this->translate('GUIDA ALL’USO DELLE EQUOMOBILI'); ?>’’</a> <?= $this->translate('che puoi scaricare con un click o nel nostro sito (nella parte bassa centrale).'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Dove lascio l\'auto dopo il noleggio?'); ?></a></h1>

                <p>
                    <?= $this->translate('Puoi parcheggiare la macchina Share\'nGo dovunque sia possibile parcheggiare un normale mezzo a quattro ruote all\'interno dell’area operativa (a Milano sono i confini del Comune di Milano e in questa città puoi sostare gratuitamente anche sulle striscie gialle e blu). Non è, quindi, necessario riportare l\'auto nel punto dove l\'hai ritirata.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come pago il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Il costo di ogni noleggio ti verrà addebitato automaticamente, alla fine della corsa, sulla carta di credito che hai inserito al momento della registrazione. Inoltre potrai scaricare tutte le fatture relative alle tue corse in Area Riservata.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

        </section>
        <!-- module-list-archive -->

    </div>
    <!-- content -->

</div>
<!-- main -->