<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content">

        <!-- module-list-archive -->
        <section class="module-list-archive margin-top">
            <h1 class="module-main-title"><?= $this->translate('F.A.Q.'); ?></h1>
            
            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Dove è attivo il servizio SHARE\'NGO?'); ?></a></h1>

                <p>
                    <?= $this->translate('Dal 15 giugno sarà attivo a Milano il servizio di car sharing a flusso libero, con le prime Equomobili elettriche. Le iscrizioni al servizio sono aperte su <a href="http://www.equomobili.it">www.equomobili.it</a><br>Dal 1° maggio inoltre 10 veicoli SHARE\'NGO sono disponibili c/o la stazione delle Ferrovie Nord di Busto Arsizio e possono essere prenotate telefonando al n 370.3325086. Gli orari per il ritiro e la consegna sono 7.30-10.30 oppure 17.00-19.00 tutti i giorni della settimana.');?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Perché Share\'ngo è diverso dagli altri?'); ?></a></h1>

                <p>
                    <?= $this->translate('Le nostre sono macchine elettriche, a impatto zero. Zero CO2, Zero PMI, Zero Rumore. Non ti devi preoccupare della ricarica e le tariffe sono variabili perché dipendono dal tuo bisogno di mobilità a 4 ruote (più nei hai bisogno meno costano!). I nostri noleggi sono sempre a KM illimitato e  sono gratuiti per le donne di notte dall’1.00 alle 6.00 del mattino. E diversissima è la  community degli equomobili che raccoglie gli utenti di SHARE\'NGO. Scoprila sui social più importanti.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quanto costa il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('SHARE\'NGO ha introdotto, primi al mondo, un sistema di prezzi variabili che dipendono dal bisogno individuale di mobilità e che premia i comportamenti orientati alla condivisione. La tariffa base di 0,28 € al minuto è quindi solo nominale. Quella effettiva può  essere inferiore del 50%. Per scoprire in 4 click "quello che ti spetta" basta seguire la profilazione su <a href="http://www.equomobili.it">www.equomobili.it</a> e poi completare la registrazione.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come posso registrarmi?'); ?></a></h1>

                <p>
                    <?= $this->translate('Per registrarsi  al servizio di car sharing operativo a Milano dal 15 Giugno basta andare su <a href="http://www.equomobili.it">www.equomobili.it</a> oppure su <a href="http://www.sharengo.it">www.sharengo.it</a>. Prima della registrazione è proposta una profilazione del bisogno di mobilità che determina uno sconto % sulle tariffe nominali e quindi un piano tariffario personale. Per poterti registrare a Share\'nGo devi essere maggiorenne, in possesso di patente di guida valida ed avere una carta di credito o un conto Paypal.<br>Per registrarsi al servizio dislocato di Busto Arsizio basta andare allo sportello in orario di ufficio.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quando saranno disponibili le APP per il mio smartphone?'); ?></a></h1>

                <p>
                    <?= $this->translate('L’inizio del servizio di car sharing è previsto a Milano il 15/6. Per quella data il sito (responsive) <a href="http://www.sharengo.it">www.sharengo.it</a> sarà utilizzabile al 100% per usufruire del servizio. Il rilascio delle APP dipende dai nulla osta di Google Play (Android) e Apple (IOS). Certamente avverrà entro giugno.');
                    ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come faccio a trovare una macchina Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('E\' molto semplice. Da Giugno potrai scaricare l\'APP (che visualizza in tempo reale la posizione di tutte le macchine attive) oppure puoi cercarla sul sito <a href="http://www.sharengo.it">www.sharengo.it</a> e prenotarla. I primi 30 minuti di prenotazione sono sempre gratuiti.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Dove lascio l\'auto dopo il noleggio?'); ?></a></h1>

                <p>
                    <?= $this->translate('Puoi parcheggiare la macchina Share\'nGo dovunque sia possibile parcheggiare un normale mezzo a quattro ruote all\'interno dell’area operativa (a Milano sono i confini del Comune di Milano). Non è, quindi, necessario riportare l\'auto nel punto dove l\'hai ritirata.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Come pago il servizio Share\'nGo?'); ?></a></h1>

                <p>
                    <?= $this->translate('Il costo di ogni noleggio ti verrà addebitato automaticamente, alla fine della corsa, sulla carta di credito o il conto paypal che hai inserito al momento della registrazione. Inoltre potrai scaricare tutte le fatture relative alle tue corse in Area Riservata.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

            <!-- block-item-post -->
            <article class="block-item-post list">

                <h1 class="block-title"><a href=""><?= $this->translate('Quale copertura assicurativa è prevista?'); ?></a></h1>

                <p>
                    <?= $this->translate('Sui nostri veicoli è prestata una copertura RC AUTO fino a € 10.000.000,00. E’ presente, inoltre, una garanzia “AllRisks”  per qualsiasi danno che possa subire la macchina. Anche il  Conducente è assicurato contro gli infortuni alla guida  per un capitale  di € 50.000,00.'); ?>
                </p>

            </article>
            <!-- block-item-post -->

        </section>
        <!-- module-list-archive -->

    </div>
    <!-- content -->

</div>
<!-- main -->