<!-- module-slider-place -->
<?php /*
<div class="module-slider-place padding-top padding-bottom">

    <!-- content -->
    <div class="content clearfix">

        <h1 class="module-main-title text-align-center"><?= $this->translate('Dove ti serve l\'auto?'); ?></h1>

        <!-- slider-place -->
        <div class="slider slider-place">

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Firenze'); ?></h2>

                    <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Pisa'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('/images/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Milano'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Napoli'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Roma'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

        </div>
        <!-- slider-place -->

    </div>
    <!-- content -->

</div>
<!-- module-slider-place -->
*/?>

<!-- module-car-map -->
<div class="module-car-map">

    <script>
        jQuery(function($) {
            // Asynchronously Load the map API
            var script = document.createElement('script');
            script.src = "http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
            document.body.appendChild(script);
        });

        function initialize() {
            var map,
            // Set the latitude & longitude for our location (London Eye)
                myLatlng = new google.maps.LatLng(45.4627338,9.1777323),
                mapOptions = {
                    center: myLatlng, // Set our point as the centre location
                    zoom: 13, // Set the zoom level
                    scrollwheel: false,
                    mapTypeId: 'roadmap' // set the default map type
                },
                marker;

            // Display a map on the page
            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            // Allow our satellite view have a tilted display (This only works for certain locations)
            map.setTilt(45);

            $.get("<?= $this->url('cars'); ?>", function (data) {
                data.forEach(function (position) {
                    new google.maps.Marker({
                        position: new google.maps.LatLng(position[0], position[1]),
                        map: map,
                        icon: "<?= $this->basePath('images/marker.png'); ?>"
                    });
                });
            });
        }
    </script>

    <div id="map_wrapper">
        <div id="map_canvas" class="mapping"></div>
    </div>

    <!-- block-map-tool-filter -->
    <div class="block-map-tool-filter margin-right margin-top g-top g-right">
        <ul>
            <li><a href=""><i class="icon-car-in-circle-ct2"><?= $this->translate('auto'); ?></i></a></li>
            <li><a href=""><i class="icon-energy-in-circle-ct2"><?= $this->translate('rifornimenti'); ?></i></a></li>
        </ul>
    </div>
    <!-- block-map-tool-filter -->

    <div id="map-overlay">
        <a href="http://www.equomobili.it">
            <img src="<?= $this->basePath('images/banner_sito_sharengo.png'); ?>">
        </a>
        <?= $this->translate('Stiamo arrivando'); ?>
    </div>

    <!-- module-map-tool-search -->
    <?php /*<div class="module-map-tool-search bg-ct2 g-bottom g-left">

        <!-- block-switch-user -->
        <div class="block-switch-user">
            <ul>
                <li>
                    <a class="js-show-element"><i class="fa fa-user"></i> <?= $this->translate('Privato'); ?> <i class="fa fa-caret-down"></i></a>
                    <ul class="hidden js-collapse-box">
                        <li><a href=""><?= $this->translate('Azienda'); ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- block-switch-user -->

        <!-- block-find -->
        <div class="block-find">
            <form>
                <p>
                    <label><i class="fa fa-map-marker"></i> <?= $this->translate('Dove sono?'); ?></label>
                    <input type="text" name="" value="" placeholder="<?= $this->translate('es: Milano'); ?>" >
                    <input type="submit" class="" name="" value="">
                </p>
            </form>
        </div>
        <!-- block-find -->

    </div>*/?>
    <!-- module-map-tool-search -->

    <!-- module-map-tool -->
    <div class="module-map-tool bg-ct2 g-bottom g-right">

        <!-- block-list-map-tool -->
        <div class="block-list-map-tool">
            <ul>
                <li>
                    <a class="js-toggle-map-height" >
                        <span class="block-info-1"><?= $this->translate('Riduci la mappa'); ?></span>
                        <span class="block-info-2"><?= $this->translate('Estendi la mappa'); ?></span> <i class="fa fa-angle-up"></i>
                    </a>
                </li>
                <?php /*<li><a><i class="fa fa-plus-circle"></i></a></li>
                <li><a><i class="fa fa-minus-circle"></i></a></li>*/?>
            </ul>
        </div>
        <!-- block-list-map-tool -->

    </div>
    <!-- module-map-tool -->

</div>
<!-- module-car-map -->

<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content padding-top clearfix">

        <!-- module-list-archive-faq -->
        <section class="module-list-archive-faq margin-bottom">

            <h1 class="block-title"><?= $this->translate('FAQ'); ?></h1>
            <h2 class="block-sub-title"><?= $this->translate('Le domande più frequenti'); ?></h2>

            <!-- slider -->
            <div class="slider single-item-autoplay">

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come posso registrarmi?'); ?></h1>

                        <p>
                            <?= $this->translate('Registrarsi a Share\'nGo &egrave molto semplice. Puoi effettuare la registrazione dal sito www.sharengo.it o dall\'APP. Ricorda che per poterti registrare a Share\'nGo devi essere maggiorenne, in possesso di patente di guida valida almeno da un anno ed avere una carta di credito.');?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come faccio a trovare una macchina Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('E\' molto semplice. Puoi scaricare l\'APP (che visualizza in tempo reale la posizione di tutte le macchine attive) oppure puoi guardare sul sito (www.sharengo.it).'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Quanto costa il servizio Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('Il servizio Share\'nGo ha un costo basilare di 0,20 &euro; al minuto. Grazie, per&ograve, al nostro sistema di Profilazione il costo del servizio potrebbe calare con l\'aumentare del tuo utilizzo di Share\'nGo. In sostanza, pi&ugrave usi Share\'nGo, meno paghi.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Dove lascio l\'auto dopo il noleggio?'); ?></h1>

                        <p>
                            <?= $this->translate('Puoi parcheggiare la macchina Share\'nGo dovunque sia possibile parcheggiare un normale mezzo a quattro ruote. Non &egrave, quindi, necessario riportare l\'auto nel punto dove l\'hai ritirata. In caso l’auto venga parcheggiata nei pressi di un punto di ricarica ti verrà riconosciuto un bonus.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come pago il servizio Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('Il costo di ogni noleggio ti verr&agrave addebitato automaticamente, alla fine della corsa, sulla carta di credito che hai inserito al momento della registrazione. Inoltre ti verr&agrave inviata per mail una copia della fattura riguardante la corsa.');?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Posso prestare l\'auto a qualcuno?'); ?></h1>

                        <p>
                            <?= $this->translate('Assolutamente no. L\'unica persona autorizzata a guidare il mezzo Share\'nGo &egrave colui che ha firmato il contratto e prenotato il mezzo stesso. In nessun caso il guidatore deve differire da tale persona.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

            </div>
            <!-- slider -->

        </section>
        <!-- module-list-archive-faq -->

        <!-- module-wrapper-button -->
        <div class="module-wrapper-button margin-bottom content-align-center">
            <a href="<?= $this->url('signup') ?>" class="btn-link x-large ct2"><?= $this->translate('Registrati subito'); ?> <i class="fa fa-plus-circle"></i></a>
        </div>
        <!-- module-wrapper-button -->

    </div>
    <!-- content -->

    <!-- module-preview-section -->
    <div class="module-preview-section padding-top padding-bottom bg-ct3">

        <!-- content -->
        <article class="content clearfix">

            <!-- block-text -->
            <div class="block-text bw-f w-2-3">

                <h1 class="block-title"><?= $this->translate('Presentato Share\'ngo: il nuovo car sharing "democratico"'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Elettriche, Ecologiche, Economiche'); ?></h2>

                <p>
                    <?= $this->translate('Martedì 19 maggio è stato presentato il nuovo car sharing elettrico di Milano: le auto potranno circolare liberamente all’interno della città, dal 15 giugno, senza preoccuparci della ricarica. I costi al minuto varieranno da un massimo di 0,28 euro a un minimo di 0,14€ euro, a secondo della profilazione dell’utente, e le donne non pagheranno il servizio dall’una di notte fino alle sei del mattino. Alla presentazione del servizio hanno partecipato Barbara Bacci, sale manager di Cs Group Srl (gestore del servizio), l’assessore alla Mobilità e Ambiente Pierfrancesco Maran e Emiliano Niccolai, amministratore delegato di CS Group.');
                    ?>
                </p>

            </div>
            <!-- block-text -->

            <!-- module-car-point -->
            <aside class="module-car-point bw-f w-1-3 last">
                <h1 class="block-title"><?= $this->translate('Share’nGo Point'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Il tuo negozio vicino a te'); ?></h2>

                <div class="slider nav-bottom single-item">

                    <!-- block-car-point-info -->
                    <div class="slide block-car-point-info">
                        <h2 class="block-title"><?= $this->translate('Share’nGo Point c/o Share’nGo Srl'); ?></h2>
                        <span class="map-pointer"></span>
                        <div class="block-car-point-info-text">
                            <p><i class="fa fa-map-marker"></i> <?= $this->translate('Prossima apertura'); ?></p>
                            <p><i class="fa fa-clock-o"></i> <?= $this->translate('Orari: lunedì - sabato: 10.00 – 18.00'); ?></p>
                        </div>
                    </div>
                    <!-- block-car-point-info -->

                </div>

            </aside>
            <!-- module-car-point -->

        </article>
        <!-- content -->

    </div>
    <!-- module-preview-section -->

    <!-- module-preview-section -->
    <div class="module-preview-section">

        <!-- content -->
        <div class="content">

            <!-- block-text -->
            <div class="block-text padding-top">
                <img src="<?= $this->basePath('/images/nrm-img.jpg'); ?>" class="alignleft" alt="" >
                <h1 class="block-title"><?= $this->translate('Mobilit&agrave; Elettrica Condivisa'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Ecologici, agili, interconnessi...'); ?></h2>
                <p>
                    <?= $this->translate('Milano è una città tanto bella quanto caotica: con il car sharing Share’nGo ce l’hai a portata di mano.');
                    ?>
                </p>
                <p>
                    <?= $this->translate('Paghi solo quello che utilizzi e puoi muoverti liberamente per la città iniziando e terminando il noleggio dell’auto parcheggiando dove più ti è comodo, anche su strisce gialle e blu.');
                    ?>
                </p>
                <p>
                    <?= $this->translate('Entrare nel mondo di Share’nGo è facilissimo: ti basta registrarti e recarti presso uno dei nostri Point per ritirare la tua personale Share\'nGo Card.');
                    ?>
                </p>
            </div>
            <!-- block-text -->

            <!-- module-wrapper-button -->
            <div class="module-wrapper-button margin-bottom content-align-center">
                <a href="<?= $this->url('signup') ?>" class="btn-link x-large ct2"><?= $this->translate('Registrati subito'); ?> <i class="fa fa-plus-circle"></i></a>
            </div>
            <!-- module-wrapper-button -->

        </div>
        <!-- content -->

    </div>
    <!-- module-preview-section -->

</div>
<!-- main -->