<!-- module-slider-place -->
<?php /*
<div class="module-slider-place padding-top padding-bottom">

    <!-- content -->
    <div class="content clearfix">

        <h1 class="module-main-title text-align-center"><?= $this->translate('Dove ti serve l\'auto?'); ?></h1>

        <!-- slider-place -->
        <div class="slider slider-place">

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Firenze'); ?></h2>

                    <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Pisa'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('/images/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Milano'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Napoli'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

            <!-- block-item-place -->
            <div class="block-item-place slide">

                <img src="<?= $this->basePath('img/firenze.jpg'); ?>" alt="" />

                <h2 class="block-title text-align-center"><?= $this->translate('Roma'); ?></h2>

                <a href="" class="link-to-continue"><?= $this->translate('Continua'); ?></a>

            </div>
            <!-- block-item-place -->

        </div>
        <!-- slider-place -->

    </div>
    <!-- content -->

</div>
<!-- module-slider-place -->
*/?>

<!-- module-car-map -->
<div class="module-car-map">

    <script>
        jQuery(function($) {
            // Asynchronously Load the map API
            var script = document.createElement('script');
            script.src = "http://maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
            document.body.appendChild(script);
        });

        function initialize() {
            var map,
            // Set the latitude & longitude for our location (London Eye)
                myLatlng = new google.maps.LatLng(45.4627338,9.1777323),
                mapOptions = {
                    center: myLatlng, // Set our point as the centre location
                    zoom: 13, // Set the zoom level
                    scrollwheel: false,
                    mapTypeId: 'roadmap' // set the default map type
                },
                marker;

            // Display a map on the page
            map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
            // Allow our satellite view have a tilted display (This only works for certain locations)
            map.setTilt(45);

            $.get("<?= $this->url('cars'); ?>", function (data) {
                data.forEach(function (position) {
                    new google.maps.Marker({
                        position: new google.maps.LatLng(position[0], position[1]),
                        map: map,
                        icon: "<?= $this->basePath('images/marker.png'); ?>"
                    });
                });
            });
        }
    </script>

    <div id="map_wrapper">
        <div id="map_canvas" class="mapping"></div>
    </div>

    <!-- block-map-tool-filter -->
    <div class="block-map-tool-filter margin-right margin-top g-top g-right">
        <ul>
            <li><a href=""><i class="icon-car-in-circle-ct2"><?= $this->translate('auto'); ?></i></a></li>
            <li><a href=""><i class="icon-energy-in-circle-ct2"><?= $this->translate('rifornimenti'); ?></i></a></li>
        </ul>
    </div>
    <!-- block-map-tool-filter -->

    <div id="map-overlay">
        <a href="http://www.equomobili.it">
            <img src="<?= $this->basePath('images/banner_sito_sharengo.png'); ?>">
        </a>
        <?= $this->translate('Stiamo arrivando'); ?>
    </div>

    <!-- module-map-tool-search -->
    <?php /*<div class="module-map-tool-search bg-ct2 g-bottom g-left">

        <!-- block-switch-user -->
        <div class="block-switch-user">
            <ul>
                <li>
                    <a class="js-show-element"><i class="fa fa-user"></i> <?= $this->translate('Privato'); ?> <i class="fa fa-caret-down"></i></a>
                    <ul class="hidden js-collapse-box">
                        <li><a href=""><?= $this->translate('Azienda'); ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- block-switch-user -->

        <!-- block-find -->
        <div class="block-find">
            <form>
                <p>
                    <label><i class="fa fa-map-marker"></i> <?= $this->translate('Dove sono?'); ?></label>
                    <input type="text" name="" value="" placeholder="<?= $this->translate('es: Milano'); ?>" >
                    <input type="submit" class="" name="" value="">
                </p>
            </form>
        </div>
        <!-- block-find -->

    </div>*/?>
    <!-- module-map-tool-search -->

    <!-- module-map-tool -->
    <div class="module-map-tool bg-ct2 g-bottom g-right">

        <!-- block-list-map-tool -->
        <div class="block-list-map-tool">
            <ul>
                <li>
                    <a class="js-toggle-map-height" >
                        <span class="block-info-1"><?= $this->translate('Riduci la mappa'); ?></span>
                        <span class="block-info-2"><?= $this->translate('Estendi la mappa'); ?></span> <i class="fa fa-angle-up"></i>
                    </a>
                </li>
                <?php /*<li><a><i class="fa fa-plus-circle"></i></a></li>
                <li><a><i class="fa fa-minus-circle"></i></a></li>*/?>
            </ul>
        </div>
        <!-- block-list-map-tool -->

    </div>
    <!-- module-map-tool -->

</div>
<!-- module-car-map -->

<!-- main -->
<div id="main">

    <!-- content -->
    <div class="content padding-top clearfix">

        <!-- module-list-archive-faq -->
        <section class="module-list-archive-faq margin-bottom">

            <h1 class="block-title"><?= $this->translate('FAQ'); ?></h1>
            <h2 class="block-sub-title"><?= $this->translate('Le domande più frequenti'); ?></h2>

            <!-- slider -->
            <div class="slider single-item-autoplay">

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Dove è attivo il servizio SHARE\'NGO?'); ?></h1>

                        <p>
                            <?= $this->translate('Dal 15 giugno sarà attivo a Milano il servizio di car sharing a flusso libero, con le prime Equomobili elettriche. Le iscrizioni al servizio sono aperte su <a href="http://www.equomobili.it">www.equomobili.it</a><br>Dal 1° maggio inoltre 10 veicoli SHARE\'NGO sono disponibili c/o la stazione delle Ferrovie Nord di Busto Arsizio e possono essere prenotate telefonando al n 370.3325086. Gli orari per il ritiro e la consegna sono 7.30-10.30 oppure 17.00-19.00 tutti i giorni della settimana.');?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Perché Share\'ngo è diverso dagli altri?'); ?></h1>

                        <p>
                            <?= $this->translate('Le nostre sono macchine elettriche, a impatto zero. Zero CO2, Zero PMI, Zero Rumore. Non ti devi preoccupare della ricarica e le tariffe sono variabili perché dipendono dal tuo bisogno di mobilità a 4 ruote (più nei hai bisogno meno costano!). I nostri noleggi sono sempre a KM illimitato e  sono gratuiti per le donne di notte dall’1.00 alle 6.00 del mattino. E diversissima è la  community degli equomobili che raccoglie gli utenti di SHARE\'NGO. Scoprila sui social più importanti.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Quanto costa il servizio Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('SHARE\'NGO ha introdotto, primi al mondo, un sistema di prezzi variabili che dipendono dal bisogno individuale di mobilità e che premia i comportamenti orientati alla condivisione. La tariffa base di 0,28 € al minuto è quindi solo nominale. Quella effettiva può  essere inferiore del 50%. Per scoprire in 4 click "quello che ti spetta" basta seguire la profilazione su <a href="http://www.equomobili.it">www.equomobili.it</a> e poi completare la registrazione.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come posso registrarmi?'); ?></h1>

                        <p>
                            <?= $this->translate('Per registrarsi  al servizio di car sharing operativo a Milano dal 15 Giugno basta andare su <a href="http://www.equomobili.it">www.equomobili.it</a> oppure su <a href="http://www.sharengo.it">www.sharengo.it</a>. Prima della registrazione è proposta una profilazione del bisogno di mobilità che determina uno sconto % sulle tariffe nominali e quindi un piano tariffario personale. Per poterti registrare a Share\'nGo devi essere maggiorenne, in possesso di patente di guida valida ed avere una carta di credito o un conto Paypal.<br>Per registrarsi al servizio dislocato di Busto Arsizio basta andare allo sportello in orario di ufficio.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Quando saranno disponibili le APP per il mio smartphone?'); ?></h1>

                        <p>
                            <?= $this->translate('L’inizio del servizio di car sharing è previsto a Milano il 15/6. Per quella data il sito (responsive) <a href="http://www.sharengo.it">www.sharengo.it</a> sarà utilizzabile al 100% per usufruire del servizio. Il rilascio delle APP dipende dai nulla osta di Google Play (Android) e Apple (IOS). Certamente avverrà entro giugno.');?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come faccio a trovare una macchina Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('E\' molto semplice. Da Giugno potrai scaricare l\'APP (che visualizza in tempo reale la posizione di tutte le macchine attive) oppure puoi cercarla sul sito <a href="http://www.sharengo.it">www.sharengo.it</a> e prenotarla. I primi 30 minuti di prenotazione sono sempre gratuiti.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Dove lascio l\'auto dopo il noleggio?'); ?></h1>

                        <p>
                            <?= $this->translate('Puoi parcheggiare la macchina Share\'nGo dovunque sia possibile parcheggiare un normale mezzo a quattro ruote all\'interno dell’area operativa (a Milano sono i confini del Comune di Milano). Non è, quindi, necessario riportare l\'auto nel punto dove l\'hai ritirata.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

                <!-- slide -->
                <div class="slide">

                    <!-- block-item-faq -->
                    <article class="block-item-faq">

                        <h1 class="block-title"><?= $this->translate('Come pago il servizio Share\'nGo?'); ?></h1>

                        <p>
                            <?= $this->translate('Il costo di ogni noleggio ti verrà addebitato automaticamente, alla fine della corsa, sulla carta di credito o il conto paypal che hai inserito al momento della registrazione. Inoltre potrai scaricare tutte le fatture relative alle tue corse in Area Riservata.'); ?>
                        </p>

                    </article>
                    <!-- block-item-faq -->

                </div>
                <!-- slide -->

            </div>
            <!-- slider -->

        </section>
        <!-- module-list-archive-faq -->

        <!-- module-wrapper-button -->
        <div class="module-wrapper-button margin-bottom content-align-center">
            <a href="<?= $this->url('signup') ?>" class="btn-link x-large ct2"><?= $this->translate('Registrati subito'); ?> <i class="fa fa-plus-circle"></i></a>
        </div>
        <!-- module-wrapper-button -->

    </div>
    <!-- content -->

    <!-- module-preview-section -->
    <div class="module-preview-section padding-top padding-bottom bg-ct3">

        <!-- content -->
        <article class="content clearfix">

            <!-- block-text -->
            <div class="block-text bw-f w-2-3">

                <h1 class="block-title"><?= $this->translate('SHARE’NGO PARTE DA MILANO'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Il car sharing elettrico a flusso libero è un nuovo primato europeo per la città'); ?></h2>

                <p>
                    <?= $this->translate('Martedì 19 maggio al Politecnico di Milano è stato presentato il nuovo car sharing elettrico di Milano SHARE‘NGO: le auto potranno circolare liberamente all’interno della città, dal 15 giugno, senza preoccuparci della ricarica. I costi al minuto varieranno da un massimo di 0,28 euro a un minimo di 0,14 euro, a secondo della profilazione dell’utente, e le donne non pagheranno il servizio dall’una di notte fino alle sei del mattino. Alla presentazione del servizio hanno partecipato Alfredo  Bacci, l’inventore delle EQUOMOBILI,  l’Assessore alla Mobilità e Ambiente Pierfrancesco Maran e Emiliano Niccolai, Amministratore Delegato di CS Group che gestirà il servizio (nella foto). Penso sia una grande innovazione che piacerà molto ai milanesi- ha detto Maran- e la velocità con cui sono partite e crescono le registrazioni al servizio  sembrano confermarlo.');
                    ?>
                </p>

            </div>
            <!-- block-text -->

            <aside class="module-car-point bw-f w-1-3 last" style="margin-top: 7%;">
                <img src="<?= $this->basePath('images/maranniccolai.jpg'); ?>">
            </aside>

            <!-- module-car-point -->
            <!--aside class="module-car-point bw-f w-1-3 last">
                <h1 class="block-title"><?= $this->translate('Share’nGo Point'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Il tuo negozio vicino a te'); ?></h2>

                <div class="slider nav-bottom single-item">

                    <!-- block-car-point-info -->
                    <!--div class="slide block-car-point-info">
                        <h2 class="block-title"><?= $this->translate('Share’nGo Point c/o Share’nGo Srl'); ?></h2>
                        <span class="map-pointer"></span>
                        <div class="block-car-point-info-text">
                            <p><i class="fa fa-map-marker"></i> <?= $this->translate('Prossima apertura'); ?></p>
                            <p><i class="fa fa-clock-o"></i> <?= $this->translate('Orari: lunedì - sabato: 10.00 – 18.00'); ?></p>
                        </div>
                    </div-->
                    <!-- block-car-point-info -->

                <!--/div>

            </aside-->
            <!-- module-car-point -->

        </article>
        <!-- content -->

    </div>
    <!-- module-preview-section -->

    <!-- module-preview-section -->
    <div class="module-preview-section">

        <!-- content -->
        <div class="content">

            <!-- block-text -->
            <div class="block-text padding-top">
                <img src="<?= $this->basePath('/images/equomobile.jpg'); ?>" class="alignleft" alt="" >
                <h1 class="block-title"><?= $this->translate('Equomobile'); ?></h1>
                <h2 class="block-sub-title"><?= $this->translate('Tutto quello che ti serve in città'); ?></h2>
                <p>
                    <?= $this->translate('100% elettrica (zero emissioni, zero rumore)');
                    ?>
                </p>
                <p>
                    <?= $this->translate('2 posti e bagagliaio da 300 litri.');
                    ?>
                </p>
                <p>
                    <?= $this->translate('120 km di autonomia e velocità di 80 km/h');
                    ?>
                </p>
                <p>
                    <?= $this->translate('Raggio di sterzo di 4 mt (con servosterzo)');
                    ?>
                </p>
                <p>
                    <?= $this->translate('Trazione anteriore');
                    ?>
                </p>
                <p>
                    <?= $this->translate('Sospensioni anteriori indipendenti');
                    ?>
                </p>
                <p>
                    <?= $this->translate('FOOTPRINT di soli 4,5 MQ');
                    ?>
                </p>
            </div>
            <!-- block-text -->

            <!-- module-wrapper-button -->
            <div class="module-wrapper-button margin-bottom content-align-center">
                <a href="<?= $this->url('signup') ?>" class="btn-link x-large ct2"><?= $this->translate('Registrati subito'); ?> <i class="fa fa-plus-circle"></i></a>
            </div>
            <!-- module-wrapper-button -->

        </div>
        <!-- content -->

    </div>
    <!-- module-preview-section -->

</div>
<!-- main -->